using System;
using System.IO;
using System.Linq;
using System.Diagnostics;
using System.Threading;
using System.Drawing;
using System.Windows.Forms;
using Touchfish;

static class UpdaterProgram {
 [STAThread]static void Main(string[] args){string root=AppDomain.CurrentDomain.BaseDirectory;try{if(args.Length==2&&args[0]=="--install"){Install(args[1]);return;}if(args.Length==2&&args[0]=="--recover"){var plan=UpdateCore.Read<UpdatePlan>(args[1]);UpdateCore.Restore(plan.Root,plan.Backup);StartApp(plan.Root,null);return;}if(args.Length==1)root=Path.GetFullPath(args[0]);Application.EnableVisualStyles();Manager(root);}catch(Exception ex){try{Directory.CreateDirectory(Path.Combine(root,"_updates"));File.WriteAllText(Path.Combine(root,"_updates","error.txt"),ex.ToString());}catch{}MessageBox.Show("更新未完成："+ex.Message+"\n当前版本或临时恢复数据已保留，可重新打开更新器。","更新",MessageBoxButtons.OK,MessageBoxIcon.Information);}}
 static void Install(string path){var plan=UpdateCore.Read<UpdatePlan>(path);if(plan.ParentPid>0){try{var parent=Process.GetProcessById(plan.ParentPid);if(!parent.WaitForExit(60000))throw new InvalidOperationException("游戏窗口尚未退出，未执行更新。");}catch(ArgumentException){}}
  plan.InstallerPid=Process.GetCurrentProcess().Id;string backup=UpdateCore.Apply(plan);Process child=null;try{child=StartApp(plan.Root,plan.Manifest.HealthCheck?plan.Token:null);string health=Path.Combine(plan.Root,"_updates","health-"+plan.Token);var watch=Stopwatch.StartNew();bool healthy=false;while(watch.ElapsedMilliseconds<20000){if(child.HasExited)break;if(plan.Manifest.HealthCheck?File.Exists(health):watch.ElapsedMilliseconds>3000&&child.MainWindowHandle!=IntPtr.Zero){healthy=true;break;}Thread.Sleep(100);}if(!healthy)throw new InvalidOperationException("新版未能正常启动。");try{UpdateCore.Finish(plan.Root);}catch(IOException){}if(File.Exists(health))File.Delete(health);try{UpdateCore.ClearTemporary(plan.Root,plan.Stage);}catch(IOException){} }catch{if(child!=null&&!child.HasExited){child.Kill();child.WaitForExit(5000);}UpdateCore.Restore(plan.Root,backup);StartApp(plan.Root,null);throw;}}
 static Process StartApp(string root,string token){return Process.Start(new ProcessStartInfo(Path.Combine(root,"Touchfish.exe"),token==null?"":"--update-token "+token){WorkingDirectory=root,UseShellExecute=true});}
 static bool Running(string root){string app=Path.Combine(root,"Touchfish.exe");return Process.GetProcesses().Any(p=>{try{return p.MainModule.FileName.Equals(app,StringComparison.OrdinalIgnoreCase);}catch{return false;}});}
 static void Manager(string root){string pending=Path.Combine(root,"_updates","pending.json");if(File.Exists(pending)){var plan=UpdateCore.Read<UpdatePlan>(pending);if(plan.Phase=="committed")UpdateCore.Finish(root);else UpdateCore.Restore(root,plan.Backup);}
  var form=new Form{Text="版本更新",ClientSize=new Size(380,230),StartPosition=FormStartPosition.CenterScreen,BackColor=Color.FromArgb(13,17,23),ForeColor=Color.FromArgb(230,237,243),Font=new Font("Microsoft YaHei UI",9,FontStyle.Regular),FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false};var title=new Label{Text="GitHub 更新 / 历史版本回退",Left=12,Top=14,Width=350};var versions=new ComboBox{Left=12,Top=44,Width=350,DropDownStyle=ComboBoxStyle.DropDownList};var notice=new Label{Left=12,Top=80,Width=350,Height=95,Text="历史版本保存在 GitHub，本地不保留旧版。\n回退旧版本后仍可通过此更新器重新升级。"};var check=new Button{Text="检查版本",Left=12,Top=186,Width=92};var install=new Button{Text="安装所选版本",Left=112,Top=186,Width=118,Enabled=false};form.Controls.AddRange(new Control[]{title,versions,notice,check,install});
  check.Click+=(s,e)=>{check.Enabled=false;new Thread(()=>{try{var items=UpdateCore.Releases(CancellationToken.None);form.BeginInvoke(new Action(()=>{versions.DataSource=items;install.Enabled=items.Length>0;check.Enabled=true;notice.Text=items.Length==0?"暂未发布可更新版本。":"选择版本后安装，个人卡组和设置保留。";}));}catch(Exception ex){form.BeginInvoke(new Action(()=>{check.Enabled=true;notice.Text=ex.Message;}));}}){IsBackground=true}.Start();};
  install.Click+=(s,e)=>{if(Running(root)){notice.Text="请先结束对局并关闭游戏窗口，再安装。";return;}var chosen=(GitHubRelease)versions.SelectedItem;if(chosen==null)return;install.Enabled=check.Enabled=false;notice.Text="正在下载并校验…";new Thread(()=>{try{string stage=UpdateCore.Download(chosen,root,CancellationToken.None);string plan=UpdateCore.Prepare(root,stage,0);UpdateCore.LaunchInstaller(root,plan);form.BeginInvoke(new Action(()=>form.Close()));}catch(Exception ex){form.BeginInvoke(new Action(()=>{install.Enabled=check.Enabled=true;notice.Text=ex.Message;}));}}){IsBackground=true}.Start();};Application.Run(form);
 }
}
