using System;
using System.Linq;
using System.IO;
using System.Windows;
using System.Windows.Controls;
namespace Touchfish {
public partial class PanelWindow {
 void VerifyChoices(string folder){int before=checks;string[] ids={"EX1_154","EX1_155","EX1_160","EX1_164","EX1_165","EX1_166","EX1_178","EX1_573","NEW1_007","NEW1_008"};foreach(string id in ids)foreach(var option in matchRules.Choices(catalog.Card("VAN_"+id))){var game=MatchFixture("DRUID");game.Summon(0,"VAN_CS2_182");var enemy=game.Summon(1,"VAN_CS2_182");int hand=Inject(game,id);var card=game.Card("VAN_"+id);int cost=game.CardCost(0,card);string mask=game.Rules.Target(card,option.Key);MatchTarget target=mask=="NONE"?null:new MatchTarget(id=="EX1_155"?0:1,id=="EX1_155"?game.Players[0].Board[0].Id:enemy.Id);Check(game.Play(0,hand,target,0,option.Key).Success&&game.Players[0].Mana>=0&&game.Log.Any(line=>line.Contains("抉择：")),"Both effects execute and record choice "+id+" "+option.Key);}
  var g=MatchFixture("DRUID");int spell=Inject(g,"EX1_154");int logs=g.Log.Count;Check(!g.Play(0,spell,null,-1,"invalid").Success&&g.Players[0].Mana==10&&g.Players[0].Hand.Count==1&&g.Log.Count==logs,"Invalid choice never spends or logs");Check(!g.Play(0,spell,new MatchTarget(1),-1,"three").Success&&g.Players[0].Mana==10,"Invalid choice target is atomic");
  g=MatchFixture("DRUID");spell=Inject(g,"NEW1_007");Check(g.Play(0,spell,null,-1,"area").Success,"Starfall area has no targeting requirement even on empty board");g=MatchFixture("DRUID");var a=g.Summon(1,"VAN_CS2_182");var b=g.Summon(1,"VAN_CS2_182");spell=Inject(g,"NEW1_007");Check(g.Play(0,spell,null,-1,"area").Success&&a.Health==3&&b.Health==3,"Starfall area hits all enemy minions");
  g=MatchFixture("DRUID");g.Summon(0,"VAN_EX1_563");a=g.Summon(1,"VAN_CS2_182");spell=Inject(g,"EX1_166");Check(g.Play(0,spell,new MatchTarget(1,a.Id),0,"damage").Success&&a.Health==3,"Keeper battlecry ignores spell power");
  g=MatchFixture("DRUID");spell=Inject(g,"EX1_165");Check(g.Play(0,spell,null,0,"taunt").Success&&g.Players[0].Board[0].BaseHealth==6,"Druid of Claw uses frozen Bear form");a=g.Players[0].Board[0];g.Silence(new MatchTarget(0,a.Id));Check(a.MaxHealth==6&&!a.Taunt,"Silenced Bear keeps transformed base health");g=MatchFixture("DRUID");spell=Inject(g,"EX1_165");g.Play(0,spell,null,0,"charge");Check(g.Attack(0,g.Players[0].Board[0].Id,new MatchTarget(1)).Success,"Charge form can attack immediately");
  foreach(int mana in new[]{8,9,10}){g=MatchFixture("DRUID");g.Players[0].MaxMana=g.Players[0].Mana=mana;spell=Inject(g,"EX1_164");Check(g.Play(0,spell,null,-1,"mana").Success&&g.Players[0].MaxMana==10&&g.Players[0].Mana==5,"Nourish grants only crystals actually added "+mana);}
  g=MatchFixture("DRUID");for(int n=0;n<7;n++)g.Summon(0,"VAN_CS2_231");spell=Inject(g,"EX1_160");Check(!g.Play(0,spell,null,-1,"panther").Success&&g.Players[0].Mana==10&&g.Players[0].Hand.Count==1,"Full board Panther choice rejects before spending");Check(g.Play(0,spell,null,-1,"buff").Success&&g.Players[0].Board.All(u=>u.Health==2),"Full board buff choice remains playable");
  match=MatchFixture("DRUID");matchViewSeat=0;lanMode=false;awaitHandoff=false;ClearPending();inspectMatch=false;choosePosition=false;spell=Inject(match,"EX1_154");ApplyTheme(true,true);ApplyMode(true);RenderMatch();ShowPage("match");BeginCard(spell);Check(ChoicePending()&&pendingChoice==null&&match.Players[0].Mana==10,"Spell waits for choice without paying");Render(Path.Combine(folder,"75-choice-minimal.png"));Check(Width==392&&Height==300,"Choice preserves minimal window");int deck=match.Players[0].Deck.Count;CancelPendingPlay();Check(pending==""&&match.Players[0].Hand.Any(h=>h.Id==spell)&&match.Players[0].Deck.Count==deck&&match.Players[0].Mana==10,"Right-click cancel keeps hand deck and mana");spell=Inject(match,"EX1_165");BeginCard(spell);ClickEmptySlot(0,0);Check(ChoicePending()&&match.Players[0].Board.Count==0,"Choose minion position before choosing effect, no early summon");ApplyMode(false);RenderMatch();Render(Path.Combine(folder,"76-choice-normal.png"));SelectChoice("charge");Check(match.Players[0].Board.Count==1&&match.Players[0].Board[0].Charge&&pending=="","UI confirms choice and summons transformed form");CheckNormalWeights(livePanel);JsonData.Write(Path.Combine(folder,"choice-verification.json"),new{Assertions=checks-before,Cards=ids,InvalidActionsAtomic=true,CancelKeepsHand=true,BottomChoices=true,NoTargetArea=true,KeeperNoSpellPower=true,ClawBaseHealth=true,NourishCap=true});
 }
}
}
