using System;
using System.IO;
using System.Linq;
using System.Windows.Controls;
namespace Touchfish {
public partial class PanelWindow {
 void VerifyClassRestrictions(string folder){int before=checks;
  var g=MatchFixture("WARRIOR");int fire=Inject(g,"CS2_029");int count=g.Log.Count;Check(!g.Play(0,fire,new MatchTarget(1)).Success&&g.Players[0].Mana==10&&g.Players[0].Hand.Count==1&&g.Players[1].Health==30&&g.Log.Count==count&&g.VisualEvents.Count==0,"Warrior cannot play injected Mage card atomically");int own=Inject(g,"CS2_106");Check(g.Play(0,own).Success,"Warrior may play own weapon");int neutral=Inject(g,"CS2_182");Check(g.Play(0,neutral).Success,"Warrior may play neutral minion");var invalid=matchRules.TrainingDeck("MAGE");invalid.ClassId="WARRIOR";Reject(()=>new MatchEngine(catalog,invalid,matchRules.TrainingDeck("MAGE"),42),"Mixed class deck rejected at match start");Reject(()=>DeckCode.Encode(catalog,invalid),"Mixed class deck rejected at export");
  var regular=matchRules.TrainingDeck("WARRIOR");var raw=new RawDeckCode{Format=3,Hero=catalog.Pool(regular.PoolId).HeroDbfIds["WARRIOR"],Cards=matchRules.TrainingDeck("MAGE").Cards.ToDictionary(pair=>catalog.Card(pair.Key).DbfId,pair=>pair.Value)};Reject(()=>DeckCode.Decode(catalog,DeckCode.EncodeRaw(raw),regular.PoolId),"Warrior hero with Mage card IDs rejected at import");
  var host=new LanHostGame(catalog,regular,matchRules.TrainingDeck("MAGE"),42);host.Game.Mulligan(0,new int[0]);host.Game.Mulligan(1,new int[0]);host.Game.Players[0].Mana=10;fire=Inject(host.Game,"CS2_029");Check(!host.Execute(0,new LanCommand{Kind="play",Source=fire,Target=new MatchTarget(1),Revision=0,Session=host.Session}).Success&&host.Revision==0&&host.Game.Players[0].Mana==10,"Host rejects cross-class play without revision change");
  match=g;matchViewSeat=0;awaitHandoff=false;ClearPending();BeginCard(fire=g.Players[0].Hand.First(h=>h.CardId=="VAN_CS2_029").Id);Check(pending==""&&status.Text.Contains("本职业"),"UI refuses cross-class card selection");
  var test=new MatchEngine(catalog,regular,matchRules.TrainingDeck("MAGE"),42,true);test.MarkMulliganCompleteForTests();test.Players[0].Deck.Add("VAN_CS2_029");count=test.Players[0].Deck.Count;Check(!test.TestTakeCard(0,"VAN_CS2_029").Success&&test.Players[0].Deck.Count==count,"Test take cannot bypass profession restriction");
  var savedDraft=draft;var saved=new SavedDeck{Id="class-binding-fixture",Name="职业绑定测试",PoolId=regular.PoolId,Code=DeckCode.Encode(catalog,regular)};savedDecks.Add(saved);try{draft=matchRules.TrainingDeck("MAGE");RefreshLanDecks();lanDeck.SelectedItem=((Choice[])lanDeck.ItemsSource).First(c=>c.Key==saved.Id);Check(((Choice)lanClass.SelectedItem).Key=="WARRIOR"&&!lanClass.IsEnabled,"Saved deck binds and locks LAN profession");Check(LobbyDeck(lanClass,lanDeck).ClassId=="WARRIOR","LAN starts using saved deck profession");lanDeck.SelectedItem=((Choice[])lanDeck.ItemsSource).First(c=>c.Key=="draft");Check(((Choice)lanClass.SelectedItem).Key=="MAGE"&&!lanClass.IsEnabled,"Draft binds and locks profession");RefreshLobbyDecks();myDeck.SelectedItem=((Choice[])myDeck.ItemsSource).First(c=>c.Key==saved.Id);opponentDeck.SelectedItem=((Choice[])opponentDeck.ItemsSource).First(c=>c.Key=="draft");Check(((Choice)myClass.SelectedItem).Key=="WARRIOR"&&!myClass.IsEnabled&&((Choice)opponentClass.SelectedItem).Key=="MAGE"&&!opponentClass.IsEnabled,"Both test players bind independent deck professions");myDeck.SelectedIndex=0;Check(myClass.IsEnabled,"Practice deck allows profession selection");lanDeck.SelectedIndex=0;Check(lanClass.IsEnabled,"Practice LAN deck allows profession selection");ShowPage("lobby");ApplyMode(true);Render(Path.Combine(folder,"64-deck-class-binding.png"));}finally{draft=savedDraft;savedDecks.Remove(saved);RefreshLobbyDecks();RefreshLanDecks();}
  JsonData.Write(Path.Combine(folder,"class-restriction-verification.json"),new{Assertions=checks-before,DeckClassBound=true,CrossClassPlayBlocked=true,ImportExportValidated=true,HostValidation=true,TestRestriction=true});
 }
}
}
