using System;
using System.IO;
using System.Linq;
namespace Touchfish {
public partial class PanelWindow {
 public void PreviewComboScope(string folder){
  previewRun=true;Directory.CreateDirectory(folder);int before=checks;
  var all=catalog.Deckable(catalog.Pool("classic-2014"));Check(all.Count(c=>c.Mechanics.Contains("COMBO"))==8&&all.Where(c=>c.Mechanics.Contains("COMBO")).All(c=>matchRules.Supports(c)),"All eight frozen Classic combo cards supported");
  foreach(bool combo in new[]{false,true}){
   var g=MatchFixture("ROGUE");if(combo)g.Play(0,Inject(g,"GAME_COIN"));var target=g.Summon(1,"VAN_CS2_182");int cold=Inject(g,"CS2_073");g.Play(0,cold,new MatchTarget(1,target.Id));Check(g.AttackValue(target)==4+(combo?4:2),"Cold Blood uses prior card count");
   g=MatchFixture("ROGUE");if(combo)g.Play(0,Inject(g,"GAME_COIN"));g.Summon(0,"VAN_EX1_563");g.Play(0,Inject(g,"EX1_124"),new MatchTarget(1));Check(g.Players[1].Health==30-(combo?9:7),"Eviscerate base/combo adds spell power");
   g=MatchFixture("ROGUE");if(combo)g.Play(0,Inject(g,"GAME_COIN"));g.Play(0,Inject(g,"EX1_131"),position:0);Check(g.Players[0].Board.Count==(combo?2:1)&&(!combo||g.Players[0].Board[1].CardId=="GAME_DEFIAS_BANDIT"&&g.Players[0].Board[1].BaseAttack==2&&g.Players[0].Board[1].Health==1),"Defias combo summons adjacent 2/1 bandit");
   g=MatchFixture("ROGUE");if(combo)g.Play(0,Inject(g,"GAME_COIN"));g.Summon(0,"VAN_EX1_563");g.Play(0,Inject(g,"EX1_133"),new MatchTarget(1));Check(g.Players[1].Health==(combo?28:29)&&g.Players[0].WeaponAttack==2&&g.Players[0].WeaponDurability==2,"Perdition Blade base/combo battlecry ignores spell power");
   g=MatchFixture("ROGUE");if(combo)g.Play(0,Inject(g,"GAME_COIN"));g.Summon(0,"VAN_EX1_563");Check(g.Play(0,Inject(g,"EX1_134"),combo?new MatchTarget(1):null).Success&&g.Players[1].Health==(combo?28:30),"SI7 target conditional and damage is not a spell");
   g=MatchFixture("ROGUE");if(combo)g.Play(0,Inject(g,"GAME_COIN"));target=g.Summon(1,"VAN_CS2_182");Check(g.Play(0,Inject(g,"NEW1_005"),combo?new MatchTarget(1,target.Id):null).Success&&g.Players[1].Board.Count==(combo?0:1)&&g.Players[1].Hand.Count==(combo?1:0),"Kidnapper only targets and bounces on combo");
   g=MatchFixture("ROGUE");if(combo)g.Play(0,Inject(g,"GAME_COIN"));g.Play(0,Inject(g,"EX1_137"));Check(g.Players[1].Health==28&&g.Players[0].Hand.Count==0,"Headcrack deals two and does not immediately return");g.EndTurn();Check(!g.Players[0].Hand.Any(h=>h.CardId=="VAN_EX1_137"),"Headcrack waits through opponent turn");g.EndTurn();Check(g.Players[0].Hand.Count(h=>h.CardId=="VAN_EX1_137")== (combo?1:0),"Only combo Headcrack returns on own turn start");
  }
  var game=MatchFixture("ROGUE");game.Play(0,Inject(game,"GAME_COIN"));game.Play(0,Inject(game,"GAME_COIN"));game.Play(0,Inject(game,"EX1_613"));var edwin=game.Players[0].Board.Single();Check(edwin.BaseAttack+edwin.BuffAttack==6&&edwin.MaxHealth==6,"Edwin counts two prior cards and excludes himself");game.Silence(new MatchTarget(0,edwin.Id));Check(edwin.MaxHealth==2&&game.AttackValue(edwin)==2,"Silence removes Edwin combo buff");
  game=MatchFixture("ROGUE");game.HeroPower(0);Check(!ComboRules.Active(game),"Hero power does not activate combo");int bad=Inject(game,"EX1_124");Check(!game.Play(0,bad).Success&&!ComboRules.Active(game)&&game.Players[0].Mana==8,"Invalid play does not activate combo or spend resources");game.Play(0,Inject(game,"GAME_COIN"));game.EndTurn();Check(!ComboRules.Active(game),"Turn change resets combo");
  game=MatchFixture("ROGUE");game.Play(0,Inject(game,"GAME_COIN"));for(int n=0;n<6;n++)game.Summon(0,"VAN_CS2_231");Check(game.Play(0,Inject(game,"EX1_131"),position:2).Success&&game.Players[0].Board.Count==7,"Defias combo respects seven slots");
  game=MatchFixture("ROGUE");game.Play(0,Inject(game,"GAME_COIN"));int si=Inject(game,"EX1_134");Check(!game.Play(0,si).Success&&game.Players[0].Hand.Any(h=>h.Id==si)&&game.Players[0].Mana==10,"Activated SI7 requires a valid target before spending");
  game=MatchFixture("ROGUE");game.Play(0,Inject(game,"GAME_COIN"));game.Play(0,Inject(game,"EX1_137"));for(int n=0;n<10;n++)Inject(game,"CS2_231");game.EndTurn();game.EndTurn();Check(game.Players[0].Hand.Count==10&&!game.Players[0].Hand.Any(h=>h.CardId=="VAN_EX1_137"),"Delayed return respects ten-card cap");
  Check(HeroEmotes.Opening("ROGUE")=="当心你的背后"&&HeroEmotes.Contains("ROGUE","当心你的背后"),"Valeera opening line updated and permitted");
  VerifyComboTcp(folder);var coverage=all.Select(c=>new{Id=c.Id,Name=c.Name,Supported=matchRules.Supports(c)}).ToArray();JsonData.Write(Path.Combine(folder,"match-rule-coverage.json"),new{SupportedCards=coverage.Count(c=>c.Supported),TotalCards=382,Cards=coverage,Scope="Combo registry and focused combo verification"});File.WriteAllText(Path.Combine(folder,"combo-verification.txt"),"PASS: "+(checks-before)+" targeted combo assertions; eight Classic combo cards, dynamic targets, prior count, limits, delayed returns, real loopback TCP and WPF preview.");
 }
 void VerifyComboTcp(string folder){
  LeaveLan();ApplyTheme(true,true);ApplyMode(false);SetFullEffects(false);var guest=new PanelWindow(true){ShowInTaskbar=false,Opacity=0};guest.Show();guest.ApplyMode(false);
  try{lanPort.Text=FreeLanPort().ToString();lanDeck.SelectedIndex=0;lanClass.SelectedItem=Classes.First(c=>c.Key=="MAGE");BeginLan(true);guest.lanDeck.SelectedIndex=0;guest.lanClass.SelectedItem=Classes.First(c=>c.Key=="ROGUE");guest.lanAddress.Text="127.0.0.1:"+lanPort.Text;guest.BeginLan(false);PumpLan(()=>lanReady&&guest.lanReady,"Combo TCP peers connect");DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>guest.match.Players[0].MulliganDone,"Host mulligan synchronizes");guest.DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>match.MulliganComplete&&!guest.lanWaiting,"Guest mulligan synchronizes");DoMatch("end");PumpLan(()=>guest.match.Active==1,"Guest rogue turn starts");var game=lanAuthority.Game;foreach(var p in game.Players){p.Hand.Clear();p.Board.Clear();}game.Players[1].Mana=game.Players[1].MaxMana=10;int coin=Inject(game,"GAME_COIN",1),agent=Inject(game,"EX1_134",1),crack=Inject(game,"EX1_137",1);PublishLan();PumpLan(()=>guest.match.Players[1].Hand.Count==3,"Guest combo hand reaches client");guest.BeginCard(coin);PumpLan(()=>!guest.lanWaiting&&guest.match.CardsPlayed==1,"Coin activates combo on both peers");guest.BeginCard(agent);guest.ClickEmptySlot(1,0);Check(guest.pending=="play"&&guest.pendingPosition==0&&guest.match.Players[1].Hand.Any(h=>h.Id==agent),"Combo SI7 UI selects position then target");guest.ClickMatchTarget(new MatchTarget(0));PumpLan(()=>!guest.lanWaiting&&game.Players[0].Health==28,"SI7 combo resolves on authority");guest.BeginCard(crack);PumpLan(()=>!guest.lanWaiting&&game.Players[0].Health==26,"Headcrack resolves and schedules return on authority");guest.Opacity=1;guest.Render(Path.Combine(folder,"111-rogue-combo-codex.png"));guest.Opacity=0;guest.DoMatch("end");PumpLan(()=>!guest.lanWaiting&&match.Active==0,"Rogue turn ends");DoMatch("end");PumpLan(()=>guest.match.Active==1&&guest.match.Players[1].Hand.Any(h=>h.CardId=="VAN_EX1_137"),"Delayed Headcrack returns over TCP on own turn");Check(match.Players[1].HandCount==guest.match.Players[1].Hand.Count&&LanProtocol.View(game,0,lanSession,lanRevision).Players[1].Hand.Length==0&&match.Log.SequenceEqual(guest.match.Log),"Return count synchronized without opponent hand identities");
  }finally{guest.LeaveLan();guest.Close();LeaveLan();}
 }
}
}
