using System;
using System.IO;
using System.Linq;

namespace Touchfish {
public partial class PanelWindow {
 public void PreviewTriggerScope(string folder){
  previewRun=true;Directory.CreateDirectory(folder);foreach(string id in new[]{"EX1_044","EX1_100","EX1_557","NEW1_029"})Check(matchRules.Supports(catalog.Card("VAN_"+id)),"Conditional card supported: "+id);
  var g=MatchFixture();int questCard=Inject(g,"EX1_044");Check(g.Play(0,questCard).Success,"Questing Adventurer may be played");var quest=g.Players[0].Board.Single();Check(quest.BaseAttack==2&&quest.Health==2,"Questing does not trigger on itself");int coin=Inject(g,"GAME_COIN");g.Play(0,coin);Check(g.AttackValue(quest)==3&&quest.Health==3,"Questing grows for a spell");int body=Inject(g,"CS2_182");g.Play(0,body);Check(g.AttackValue(quest)==4&&quest.Health==4,"Questing grows for a minion");int fire=Inject(g,"CS2_029");int mana=g.Players[0].Mana;Check(!g.Play(0,fire).Success&&g.AttackValue(quest)==4&&g.Players[0].Mana==mana,"Invalid play does not fire a trigger");g.Silence(new MatchTarget(0,quest.Id));coin=Inject(g,"GAME_COIN");g.Play(0,coin);Check(g.AttackValue(quest)==2&&quest.Health==2,"Silenced Questing stops growing");
  g=MatchFixture("WARRIOR");quest=g.Summon(0,"VAN_EX1_044");quest.DamageTaken=1;int whirl=Inject(g,"EX1_400");g.Play(0,whirl);Check(g.Players[0].Board.Contains(quest)&&quest.Health==1&&g.AttackValue(quest)==3,"Card-play growth resolves before spell damage");g.EndTurn();int opponent=Inject(g,"GAME_COIN",1);g.Play(1,opponent);Check(g.AttackValue(quest)==3,"Opponent plays do not grow Questing");
  g=MatchFixture();var cho=g.Summon(0,"VAN_EX1_100");fire=Inject(g,"CS2_029");Check(g.Play(0,fire,new MatchTarget(0,cho.Id)).Success&&!g.Players[0].Board.Contains(cho)&&g.Players[1].Hand.Count==1,"Cho copies a spell even if its resolution kills Cho");var copy=g.Players[1].Hand.Single();Check(copy.Generated&&copy.CardId=="VAN_CS2_029","Cho preserves spell identity and marks generated origin");g.EndTurn();g.Players[1].Mana=10;Check(g.Play(1,copy.Id,new MatchTarget(0)).Success&&g.Players[0].Health==24,"Generated Mage spell is usable by Warrior");Check(DeckRules.CanAdd(catalog,new DeckDocument{ClassId="WARRIOR"},catalog.Card("VAN_CS2_029"))!=null,"Cho does not loosen deck class restriction");
  g=MatchFixture();g.Summon(0,"VAN_EX1_100");g.Summon(1,"VAN_EX1_100");fire=Inject(g,"CS2_029");g.Play(0,fire,new MatchTarget(1));Check(g.Players[1].Hand.Count==2&&g.Players[0].Hand.Count==0,"Both Cho sources copy to the opposite caster without recursion");g=MatchFixture();cho=g.Summon(0,"VAN_EX1_100");cho.Silenced=true;coin=Inject(g,"GAME_COIN");g.Play(0,coin);Check(g.Players[1].Hand.Count==0,"Silenced Cho does not copy");cho.Silenced=false;for(int i=0;i<10;i++)Inject(g,"CS2_182",1);coin=Inject(g,"GAME_COIN");g.Play(0,coin);Check(g.Players[1].Hand.Count==10,"Cho respects the ten-card hand cap");
  g=MatchFixture();int mill=Inject(g,"NEW1_029");Check(g.Play(0,mill).Success&&g.CardCost(1,g.Card("VAN_CS2_029"))==0&&g.CardCost(0,g.Card("VAN_CS2_029"))==4,"Millhouse grants only the opponent free spells");var millBody=g.Players[0].Board.Single();g.Silence(new MatchTarget(0,millBody.Id));g.ReturnToHand(new MatchTarget(0,millBody.Id));Check(g.CardCost(1,g.Card("VAN_CS2_029"))==0&&g.CardCost(1,g.Card("VAN_CS2_182"))==4,"Free-spell effect persists without Millhouse and leaves minion costs intact");g.EndTurn();g.Players[1].ClassId="MAGE";g.Players[1].Mana=0;fire=Inject(g,"CS2_029",1);Check(g.Play(1,fire,new MatchTarget(0)).Success&&g.Players[1].Mana==0,"Opponent may spend zero mana to cast under Millhouse");g.EndTurn();Check(g.CardCost(1,g.Card("VAN_CS2_029"))==4&&g.Players[1].FreeSpellsUntilTurn==-1,"Timed spell cost expires at the opponent turn end");
  g=MatchFixture();var nat=g.Summon(0,"VAN_EX1_557");g.EndTurn();Check(g.Players[0].Hand.Count==0,"Nat does not draw at opponent turn start");nat.Silenced=true;g.EndTurn();Check(g.Players[0].Hand.Count==1,"Silenced Nat permits only the regular start draw");int hits=0,misses=0;bool catchesMatchDraws=true;for(int seed=1;seed<=32;seed++){var sample=new MatchEngine(catalog,matchRules.TrainingDeck("MAGE"),matchRules.TrainingDeck("WARRIOR"),seed);sample.MarkMulliganCompleteForTests();foreach(var p in sample.Players)p.Hand.Clear();sample.Summon(0,"VAN_EX1_557");sample.EndTurn();sample.EndTurn();catchesMatchDraws&=sample.VisualEvents.Count(e=>e.Kind=="fishing")==sample.Players[0].Hand.Count-1;if(sample.Players[0].Hand.Count==2)hits++;else if(sample.Players[0].Hand.Count==1)misses++;}Check(catchesMatchDraws,"Fishing feedback occurs only when the fifty-percent extra draw succeeds");Check(hits>0&&misses>0&&hits+misses==32,"Nat's fifty-percent roll has both outcomes with one normal draw");
  var snapshot=LanProtocol.ReadView(catalog,LanProtocol.Copy(LanProtocol.View(g,1,"trigger",1)));Check(snapshot.Players[0].Hand.Count==0&&snapshot.Players[0].HandCount==g.Players[0].Hand.Count,"Start-trigger drawing keeps opponent hand identities private");
  VerifyTriggerTcp(folder);VerifyClassRestrictions(folder);VerifyMinionSpeech(folder);var cards=catalog.Deckable(catalog.Pool("classic-2014")).Select(c=>new{Id=c.Id,Name=c.Name,Supported=matchRules.Supports(c)}).ToArray();JsonData.Write(Path.Combine(folder,"match-rule-coverage.json"),new{SupportedCards=cards.Count(c=>c.Supported),TotalCards=382,Cards=cards,Scope="Registry coverage; focused conditional and start-turn trigger checks"});File.WriteAllText(Path.Combine(folder,"conditional-trigger-verification.txt"),"PASS: "+checks+" targeted assertions. Questing play timing, Cho copies and generated classes, Millhouse duration and synchronized costs, Nat start timing and random outcomes, privacy, real loopback TCP and WPF previews.");
 }
 void VerifyTriggerTcp(string folder){
  LeaveLan();ApplyTheme(true,true);ApplyMode(false);SetFullEffects(false);var guest=new PanelWindow(true){previewRun=true,ShowInTaskbar=false,Opacity=0};guest.Show();guest.ApplyMode(false);guest.ApplyTheme(true,true);
  try{lanPort.Text=FreeLanPort().ToString();lanDeck.SelectedIndex=0;lanClass.SelectedItem=Classes.First(c=>c.Key=="MAGE");BeginLan(true);guest.lanDeck.SelectedIndex=0;guest.lanClass.SelectedItem=Classes.First(c=>c.Key=="WARRIOR");guest.lanAddress.Text="127.0.0.1:"+lanPort.Text;guest.BeginLan(false);PumpLan(()=>lanReady&&guest.lanReady,"Conditional fixture starts real TCP peers");DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>guest.match.Players[0].MulliganDone,"Host mulligan synchronized");guest.DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>match.MulliganComplete&&!guest.lanWaiting,"Guest mulligan starts fixture");
   foreach(var p in match.Players){p.Hand.Clear();p.Board.Clear();p.Mana=10;}var quest=match.Summon(0,"VAN_EX1_044");match.Summon(0,"VAN_EX1_100");match.Summon(0,"VAN_EX1_557");int mill=Inject(match,"NEW1_029");DoMatch("play",mill);PumpLan(()=>guest.match.Players[1].FreeSpellsUntilTurn==match.Turn+1,"Millhouse timed modifier synchronized");int fire=Inject(match,"CS2_029");DoMatch("play",fire,new MatchTarget(1));PumpLan(()=>guest.match.Players[1].Hand.Count==1,"Cho-generated private hand arrives on owning guest");Check(guest.match.Players[1].Hand[0].Generated&&guest.match.CardCost(1,guest.match.Card("VAN_CS2_029"))==0,"Generated origin and free cost agree on both peers");Check(guest.match.AttackValue(guest.match.Unit(new MatchTarget(0,quest.Id)))==match.AttackValue(quest),"Questing growth agrees across peers");DoMatch("end");PumpLan(()=>guest.match.Active==1,"Guest turn starts");int copy=guest.match.Players[1].Hand.First(h=>h.Generated).Id;guest.match.Players[1].Mana=0;match.Players[1].Mana=0;guest.BeginCard(copy);Check(pending==""&&guest.pending=="play","Guest UI selects generated foreign spell at zero cost");guest.ClickMatchTarget(new MatchTarget(0));PumpLan(()=>!guest.lanWaiting&&match.Players[0].Health==24,"Host accepts generated foreign spell and authoritative zero cost");guest.DoMatch("end");PumpLan(()=>match.Active==0&&guest.match.Active==0&&!guest.lanWaiting,"Nat start trigger and turn switch synchronized");Check(guest.match.CardCost(1,guest.match.Card("VAN_CS2_029"))==4,"Millhouse expires on both peers");Check(match.Log.SequenceEqual(guest.match.Log)&&guest.match.Players[0].Hand.Count==0&&guest.match.Players[0].HandCount==match.Players[0].Hand.Count,"Start-trigger log and private hand counts synchronize");var hostRenderer=(OfficeMatchVisualEffects)matchEffects;var guestRenderer=(OfficeMatchVisualEffects)guest.matchEffects;SetFullEffects(true);guest.SetFullEffects(true);int hostBubbles=hostRenderer.EmoteCount,guestBubbles=guestRenderer.EmoteCount,hostShakes=hostRenderer.CardShakeCount,guestShakes=guestRenderer.CardShakeCount;var nat=match.Players[0].Board.First(u=>u.CardId=="VAN_EX1_557");match.FishingDraw(nat);PublishLan();RenderMatch();PumpLan(()=>hostRenderer.EmoteCount==hostBubbles+1&&guestRenderer.EmoteCount==guestBubbles+1&&hostRenderer.CardShakeCount==hostShakes+1&&guestRenderer.CardShakeCount==guestShakes+1,"Fishing bubble and shake synchronize across real TCP peers");PublishLan();PumpLan(()=>guest.match.VisualEvents.Count==match.VisualEvents.Count,"Repeated fishing snapshot arrives");Check(guestRenderer.EmoteCount==guestBubbles+1&&guestRenderer.CardShakeCount==guestShakes+1,"Remote fishing feedback is deduplicated");Render(Path.Combine(folder,"88-conditional-cards-normal.png"));ApplyMode(true);Render(Path.Combine(folder,"89-conditional-cards-minimal.png"));Check(Width==392&&Height==300,"Conditional cards keep minimal dimensions");
  }finally{guest.LeaveLan();guest.Close();LeaveLan();}
 }
}
}
