using System;
using System.IO;
using System.Linq;

namespace Touchfish {
public partial class PanelWindow {
 public void PreviewDeathrattleScope(string folder){
  previewRun=true;Directory.CreateDirectory(folder);foreach(string id in new[]{"NEW1_021","EX1_097","EX1_534","EX1_577"})Check(matchRules.Supports(catalog.Card("VAN_"+id)),"Deathrattle batch supports "+id);
  var g=MatchFixture();var doom=g.Summon(0,"VAN_NEW1_021");var shield=g.Summon(1,"VAN_EX1_008");g.EndTurn();Check(g.Players[0].Board.Contains(doom)&&g.Players[1].Board.Contains(shield),"Doomsayer waits for its controller's turn start");g.EndTurn();Check(g.Players.All(p=>p.Board.Count==0)&&g.Players[0].Hand.Count==1,"Doomsayer destroys itself and both boards through Divine Shield before regular draw");
  g=MatchFixture();doom=g.Summon(0,"VAN_NEW1_021");g.Silence(new MatchTarget(0,doom.Id));shield=g.Summon(1,"VAN_EX1_008");g.EndTurn();g.EndTurn();Check(g.Players[0].Board.Count==1&&g.Players[1].Board.Count==1,"Silenced Doomsayer does not wipe board");
  g=MatchFixture();doom=g.Summon(0,"VAN_NEW1_021");var loot=g.Summon(0,"VAN_EX1_096");g.EndTurn();g.EndTurn();Check(g.Players[0].Hand.Count==2,"Doomsayer destruction resolves draw deathrattle then regular draw");
  g=MatchFixture();doom=g.Summon(0,"VAN_NEW1_021");g.Summon(0,"VAN_NEW1_021");var lion=g.Summon(0,"VAN_EX1_534");g.EndTurn();g.EndTurn();Check(g.Players[0].Board.Count==2&&g.Players[0].Board.All(u=>u.CardId=="GAME_HYENA"),"Second dead Doomsayer does not wipe newly summoned deathrattle tokens");
  g=MatchFixture();var left=g.Summon(0,"VAN_CS2_182");lion=g.Summon(0,"VAN_EX1_534");var right=g.Summon(0,"VAN_CS2_179");lion.DamageTaken=lion.MaxHealth;g.Cleanup();Check(g.Players[0].Board.Select(u=>u.CardId).SequenceEqual(new[]{left.CardId,"GAME_HYENA","GAME_HYENA",right.CardId}),"Highmane summons two adjacent tokens at its death position");Check(g.Players[0].Board.Where(u=>u.CardId=="GAME_HYENA").All(u=>u.BaseAttack==2&&u.Health==2&&u.Race=="BEAST"),"Hyenas have frozen 2/2 Beast stats");Check(DeckRules.CanAdd(catalog,new DeckDocument(),g.Card("GAME_HYENA"))!=null,"Hyenas cannot be put in a deck");
  g=MatchFixture();lion=g.Summon(0,"VAN_EX1_534");for(int i=0;i<6;i++)g.Summon(0,"VAN_CS2_182");lion.DamageTaken=lion.MaxHealth;g.Cleanup();Check(g.Players[0].Board.Count==7&&g.Players[0].Board.Count(u=>u.CardId=="GAME_HYENA")==1,"Highmane respects seven slots with only one free slot");
  g=MatchFixture();var beast=g.Summon(0,"VAN_EX1_577");beast.DamageTaken=beast.MaxHealth;g.Cleanup();Check(g.Players[1].Board.Single().CardId=="VAN_EX1_finkle"&&g.Players[1].Board.Single().BaseAttack==3&&g.Players[1].Board.Single().Health==3,"The Beast summons frozen 3/3 Finkle for its opponent");
  g=MatchFixture();for(int i=0;i<7;i++)g.Summon(1,"VAN_CS2_182");beast=g.Summon(0,"VAN_EX1_577");beast.DamageTaken=beast.MaxHealth;g.Cleanup();Check(g.Players[1].Board.Count==7&&g.Players[1].Board.All(u=>u.CardId!="VAN_EX1_finkle"),"The Beast respects a full opponent board");
  g=MatchFixture();var abom=g.Summon(0,"VAN_EX1_097");var friend=g.Summon(0,"VAN_CS2_182");var enemy=g.Summon(1,"VAN_CS2_179");g.Summon(0,"VAN_EX1_563");abom.DamageTaken=abom.MaxHealth;g.Cleanup();Check(g.Players[0].Health==28&&g.Players[1].Health==28&&friend.Health==friend.MaxHealth-2&&enemy.Health==enemy.MaxHealth-2,"Abomination damages all remaining characters by two without spell power");
  g=MatchFixture();abom=g.Summon(0,"VAN_EX1_097");var leper=g.Summon(0,"VAN_EX1_029");abom.DamageTaken=abom.MaxHealth;g.Cleanup();Check(g.Players[0].Board.Count==0&&g.Players[1].Health==26&&g.Players[0].Health==28,"Abomination chains into Leper deathrattle without duplicate resolution");
  g=MatchFixture();abom=g.Summon(0,"VAN_EX1_097");g.Players[0].Health=g.Players[1].Health=2;abom.DamageTaken=abom.MaxHealth;g.Cleanup();Check(g.Finished&&g.Winner==-1,"Abomination simultaneous hero lethal is a draw");
  foreach(string id in new[]{"EX1_097","EX1_534","EX1_577"}){g=MatchFixture();var source=g.Summon(0,"VAN_"+id);g.Silence(new MatchTarget(0,source.Id));source.DamageTaken=source.MaxHealth;g.Cleanup();Check(g.Players.All(p=>p.Board.Count==0&&p.Health==30),"Silence suppresses deathrattle "+id);}
  g=MatchFixture();doom=g.Summon(0,"VAN_NEW1_021");lion=g.Summon(0,"VAN_EX1_534");abom=g.Summon(0,"VAN_EX1_097");g.EndTurn();g.EndTurn();Check(g.Players[0].Board.Count==0,"Later Abomination deathrattle destroys earlier Highmane tokens");
  g=MatchFixture();doom=g.Summon(0,"VAN_NEW1_021");abom=g.Summon(0,"VAN_EX1_097");lion=g.Summon(0,"VAN_EX1_534");g.EndTurn();g.EndTurn();Check(g.Players[0].Board.Count==2,"Later Highmane tokens survive earlier Abomination deathrattle");
  foreach(string id in new[]{"EX1_096","EX1_012"}){g=MatchFixture();var source=g.Summon(0,"VAN_"+id);source.DamageTaken=source.MaxHealth;g.Cleanup();Check(g.Players[0].Hand.Count==1,"Existing draw deathrattle preserved: "+id);}
  g=MatchFixture();var harvest=g.Summon(0,"VAN_EX1_556");harvest.DamageTaken=harvest.MaxHealth;g.Cleanup();Check(g.Players[0].Board.Single().CardId=="VAN_skele21"&&g.Players[0].Board.Single().Health==1,"Harvest Golem deathrattle preserved");g=MatchFixture();var tirion=g.Summon(0,"VAN_EX1_383");tirion.DamageTaken=tirion.MaxHealth;g.Cleanup();Check(g.Players[0].WeaponAttack==5&&g.Players[0].WeaponDurability==3,"Tirion weapon deathrattle preserved");
  g=MatchFixture();lion=g.Summon(0,"VAN_EX1_534");var champion=g.Summon(0,"VAN_CS2_222");lion.DamageTaken=lion.MaxHealth;g.Cleanup();Check(g.Players[0].Board.Where(u=>u.CardId=="GAME_HYENA").All(u=>u.Health==3&&g.AttackValue(u)==3),"Deathrattle tokens receive live health and attack auras");champion.DamageTaken=champion.MaxHealth;g.Cleanup();Check(g.Players[0].Board.Count==2&&g.Players[0].Board.All(u=>u.Health==2&&g.AttackValue(u)==2),"Token aura stats restore when source dies");
  g=MatchFixture();beast=g.Summon(1,"VAN_EX1_577");g.StealRandomEnemyMinion(0);beast.DamageTaken=beast.MaxHealth;g.Cleanup();Check(g.Players[1].Board.Single().CardId=="VAN_EX1_finkle","Stolen Beast deathrattle uses current controller's opponent");
  VerifyLegacyLegendaries();VerifyDeathrattleTcp(folder);var cards=catalog.Deckable(catalog.Pool("classic-2014")).Select(c=>new{Id=c.Id,Name=c.Name,Supported=matchRules.Supports(c)}).ToArray();JsonData.Write(Path.Combine(folder,"match-rule-coverage.json"),new{SupportedCards=cards.Count(c=>c.Supported),TotalCards=382,Cards=cards,Scope="Registry coverage; focused Doomsayer and deathrattle checks"});File.WriteAllText(Path.Combine(folder,"deathrattle-verification.txt"),"PASS: "+checks+" targeted assertions. Doomsayer start timing, simultaneous destruction, deathrattle chains and entry order, silence, frozen tokens, board cap, spell power exclusion, existing legendaries, real loopback TCP and WPF previews.");
 }
 void VerifyDeathrattleTcp(string folder){
  LeaveLan();ApplyTheme(true,true);ApplyMode(false);SetFullEffects(false);var guest=new PanelWindow{previewRun=true,ShowInTaskbar=false,Opacity=0};guest.Show();guest.ApplyTheme(true,true);guest.ApplyMode(false);
  try{lanPort.Text=FreeLanPort().ToString();lanDeck.SelectedIndex=0;lanClass.SelectedItem=Classes.First(c=>c.Key=="HUNTER");BeginLan(true);guest.lanDeck.SelectedIndex=0;guest.lanClass.SelectedItem=Classes.First(c=>c.Key=="MAGE");guest.lanAddress.Text="127.0.0.1:"+lanPort.Text;guest.BeginLan(false);PumpLan(()=>lanReady&&guest.lanReady,"Deathrattle fixture starts real TCP peers");DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>guest.match.Players[0].MulliganDone,"Host mulligan synchronized");guest.DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>match.MulliganComplete&&!guest.lanWaiting,"Guest mulligan starts fixture");foreach(var p in match.Players){p.Hand.Clear();p.Board.Clear();p.Mana=10;}int lion=Inject(match,"EX1_534");DoMatch("play",lion);int doom=Inject(match,"NEW1_021");DoMatch("play",doom);match.Summon(1,"VAN_EX1_577");PublishLan();PumpLan(()=>guest.match.Players[0].Board.Count==2&&guest.match.Players[1].Board.Count==1,"Deathrattle fixture reaches guest");DoMatch("end");PumpLan(()=>guest.match.Active==1,"Guest turn starts without Doomsayer trigger");guest.DoMatch("end");PumpLan(()=>!guest.lanWaiting&&guest.match.Active==0&&guest.match.Players[0].Board.Count==3,"Host resolves guest end into Doomsayer and deathrattles");Check(match.Players[0].Board.Count(u=>u.CardId=="GAME_HYENA")==2&&match.Players[0].Board.Count(u=>u.CardId=="VAN_EX1_finkle")==1&&match.Players[1].Board.Count==0,"Doomsayer preserves deathrattle summons from both sides");Check(match.Players[0].Board.Select(u=>u.CardId).SequenceEqual(guest.match.Players[0].Board.Select(u=>u.CardId))&&match.Log.SequenceEqual(guest.match.Log),"Deathrattle order and public log agree across peers");Check(guest.match.Players[0].Hand.Count==0&&guest.match.Players[0].HandCount==match.Players[0].Hand.Count,"Start draw keeps opponent hand private");Render(Path.Combine(folder,"92-doomsayer-deathrattle-normal.png"));ApplyMode(true);Render(Path.Combine(folder,"93-doomsayer-deathrattle-minimal.png"));Check(Width==392&&Height==300,"Deathrattle minions preserve minimal dimensions");
  }finally{guest.LeaveLan();guest.Close();LeaveLan();}
 }
}
}
