using System;
using System.IO;
using System.Linq;
namespace Touchfish {
public partial class PanelWindow {
 void VerifyDiscard(string folder){int before=checks;
  Check(new[]{"EX1_308","EX1_306","EX1_310","NEW1_030"}.All(id=>matchRules.Supports(catalog.Card("VAN_"+id))),"Classic hand discard cards supported");Check(!matchRules.Supports(catalog.Card("VAN_DS1_184")),"Tracking remains blocked until deck-choice implemented");
  var g=MatchFixture("WARLOCK");int spell=Inject(g,"EX1_308");Check(g.Play(0,spell,new MatchTarget(1)).Success&&g.Players[1].Health==26&&g.Players[0].Hand.Count==0,"Last-card Soulfire deals damage without discard cost");g=MatchFixture("WARLOCK");spell=Inject(g,"EX1_308");int kept=Inject(g,"CS2_182");int count=g.Log.Count;Check(g.Play(0,spell,null).Success==false&&g.Players[0].Hand.Count==2&&g.Log.Count==count,"Invalid Soulfire target never discards");Check(g.Play(0,spell,new MatchTarget(1)).Success&&g.Players[0].Hand.Count==0&&g.Log.Last().Contains("弃牌："+g.Card("VAN_CS2_182").Name),"Soulfire discards remaining card and publishes discarded name");
  foreach(string id in new[]{"EX1_306","EX1_310"})for(int cards=0;cards<4;cards++){g=MatchFixture("WARLOCK");int played=Inject(g,id);for(int n=0;n<cards;n++)Inject(g,"CS2_182");int want=Math.Min(cards,id=="EX1_306"?1:2);int deck=g.Players[0].Deck.Count;int opponent=g.Players[1].Hand.Count;Check(g.Play(0,played).Success&&g.Players[0].Hand.Count==cards-want&&g.Players[0].Board.Count==1,"Discard battlecry handles limited hand "+id+" "+cards);Check(g.Log.Count(line=>line.Contains("弃牌："))==want&&g.Players[0].Deck.Count==deck&&g.Players[1].Hand.Count==opponent,"Discard touches own remaining hand only");if(id=="EX1_310")Check(g.Players[0].Board[0].Charge&&g.Attack(0,g.Players[0].Board[0].Id,new MatchTarget(1)).Success,"Doomguard retains immediate charge");}
  g=MatchFixture("WARLOCK");int guard=Inject(g,"EX1_310");Inject(g,"CS2_182");g.Players[0].Mana=4;Check(!g.Play(0,guard).Success&&g.Players[0].Hand.Count==2&&g.Players[0].Board.Count==0,"Insufficient mana never discards");g.Players[0].Mana=10;for(int n=0;n<7;n++)g.Summon(0,"VAN_CS2_231");Check(!g.Play(0,guard).Success&&g.Players[0].Hand.Count==2&&g.Players[0].Mana==10,"Full board never discards");
  var outcomes=new System.Collections.Generic.HashSet<int>();for(int seed=1;seed<=100;seed++){g=new MatchEngine(catalog,matchRules.TrainingDeck("WARLOCK"),matchRules.TrainingDeck("WARRIOR"),seed);g.Players[0].Hand.Clear();for(int n=0;n<5;n++)g.Players[0].Hand.Add(new HandCard{Id=n+100,CardId="VAN_CS2_182"});var removed=g.DiscardRandom(0,2);Check(removed.Length==2&&removed[0].Id!=removed[1].Id&&g.Players[0].Hand.Count==3,"Random discard selects distinct instances without replacement");foreach(var card in removed)outcomes.Add(card.Id);}Check(outcomes.Count==5,"Random discard can select every hand position");
  var first=new MatchEngine(catalog,matchRules.TrainingDeck("WARLOCK"),matchRules.TrainingDeck("WARRIOR"),77);var second=new MatchEngine(catalog,matchRules.TrainingDeck("WARLOCK"),matchRules.TrainingDeck("WARRIOR"),77);Check(first.DiscardRandom(0,2).Select(h=>h.Id).SequenceEqual(second.DiscardRandom(0,2).Select(h=>h.Id)),"Identical seed reproduces discard choices");Check(first.DiscardRandom(0,100).Length==1&&first.DiscardRandom(0,1).Length==0,"Excess discard stops at empty hand");
  g=MatchFixture("WARLOCK");var hoarder=g.Summon(0,"VAN_EX1_096");var shield=g.Summon(1,"VAN_EX1_008");shield.Shield=true;int wing=Inject(g,"NEW1_030");Inject(g,"CS2_182");Inject(g,"CS2_182",1);Check(g.Play(0,wing).Success&&g.Players[0].Board.Count==1&&g.Players[0].Board[0].CardId=="VAN_NEW1_030"&&g.Players[1].Board.Count==0,"Deathwing destroys all others including shielded minion");Check(g.Players[0].Hand.Count==1&&g.Players[1].Hand.Count==1,"Deathwing deathrattle draws after discard and leaves opponent hand");Check(g.Log.FindIndex(line=>line.Contains("弃牌："))<g.Log.FindIndex(line=>line.Contains("阵亡：")),"Deathwing resolves discard before deathrattle cleanup");
  match=g;matchViewSeat=0;awaitHandoff=false;ClearPending();inspectMatch=false;ShowPage("log");Render(Path.Combine(folder,"63-discard-records.png"));JsonData.Write(Path.Combine(folder,"discard-verification.json"),new{Assertions=checks-before,RandomWithoutReplacement=true,EmptyHandAllowed=true,PlayedCardExcluded=true,PublicDiscardNames=true,RemainingHandPrivate=true,DeathwingDeathrattleOrder=true});
 }
}
}
