using System;
using System.IO;
using System.Linq;

namespace Touchfish {
public partial class PanelWindow {
 public void PreviewDruidSpellScope(string folder){
  previewRun=true;Directory.CreateDirectory(folder);var spells=catalog.Deckable(catalog.Pool("classic-2014")).Where(c=>c.CardClass=="DRUID"&&c.Type=="SPELL").ToArray();Check(spells.Length==19&&spells.All(c=>matchRules.Supports(c)),"All nineteen frozen Classic Druid spells are supported");
  var g=MatchFixture("DRUID");g.Players[0].MaxMana=g.Players[0].Mana=5;int growth=Inject(g,"CS2_013");Check(g.Play(0,growth).Success&&g.Players[0].MaxMana==6&&g.Players[0].Mana==3,"Wild Growth adds an empty crystal after paying frozen two-mana cost");
  g=MatchFixture("DRUID");g.Players[0].MaxMana=g.Players[0].Mana=9;growth=Inject(g,"CS2_013");g.Play(0,growth);Check(g.Players[0].MaxMana==10&&g.Players[0].Mana==7&&g.Players[0].Hand.Count==0,"Nine crystals grow to ten without generating Excess Mana");
  g=MatchFixture("DRUID");growth=Inject(g,"CS2_013");g.Play(0,growth);var excess=g.Players[0].Hand.Single();Check(excess.CardId=="GAME_EXCESS_MANA"&&g.Players[0].MaxMana==10&&g.Players[0].Mana==8,"At ten crystals Wild Growth generates Excess Mana");Check(g.Card(excess.CardId).Cost==0&&matchRules.Supports(g.Card(excess.CardId))&&DeckRules.CanAdd(catalog,new DeckDocument{ClassId="DRUID"},g.Card(excess.CardId))!=null,"Excess Mana is a supported zero-cost generated spell outside deckbuilding");g.Players[0].Deck.Clear();g.Players[0].Deck.Add("VAN_CS2_182");Check(g.Play(0,excess.Id).Success&&g.Players[0].Hand.Single().CardId=="VAN_CS2_182"&&g.Players[0].Mana==8,"Excess Mana draws exactly one card without spending mana");
  g=MatchFixture("MAGE");growth=Inject(g,"CS2_013");g.Play(0,growth);excess=g.Players[0].Hand.Single();Check(g.Play(0,excess.Id).Success,"Foreign Druid Wild Growth and its helper spell can be used from hand");
  g=MatchFixture("DRUID");g.GenerateExcessMana(0);excess=g.Players[0].Hand.Single();g.Players[0].Deck.Clear();g.Play(0,excess.Id);Check(g.Players[0].Health==29&&g.Players[0].Fatigue==1,"Excess Mana obeys fatigue on an empty deck");
  g=MatchFixture("DRUID");var quest=g.Summon(0,"VAN_EX1_044");growth=Inject(g,"CS2_013");g.Play(0,growth);g.Play(0,g.Players[0].Hand.Single().Id);Check(g.AttackValue(quest)==4&&quest.Health==4,"Wild Growth and Excess Mana each trigger Questing once");
  g=MatchFixture("DRUID");var source=g.Summon(0,"VAN_CS2_182");var enemy=g.Summon(1,"VAN_CS2_182");int soul=Inject(g,"EX1_158");g.Play(0,soul);Check(source.ForestDeathrattles==1&&enemy.ForestDeathrattles==0,"Soul of the Forest enchants all and only existing friendly minions");var later=g.Summon(0,"VAN_CS2_231");Check(later.ForestDeathrattles==0,"Future summons do not inherit Soul of the Forest");source.DamageTaken=source.MaxHealth;g.Cleanup();var tree=g.Players[0].Board.First(u=>u.CardId=="VAN_EX1_tk9");Check(tree.BaseAttack==2&&tree.Health==2&&!tree.Charge&&!tree.Taunt&&tree.ForestDeathrattles==0,"Soul summons frozen permanent 2/2 Treant without inherited enchantments");g.EndTurn();Check(g.Players[0].Board.Contains(tree),"Soul Treant does not expire like Force of Nature Treants");
  g=MatchFixture("DRUID");var left=g.Summon(0,"VAN_CS2_182");source=g.Summon(0,"VAN_EX1_556");var right=g.Summon(0,"VAN_CS2_179");soul=Inject(g,"EX1_158");g.Play(0,soul);source.DamageTaken=source.MaxHealth;g.Cleanup();Check(g.Players[0].Board.Select(u=>u.CardId).SequenceEqual(new[]{left.CardId,"VAN_skele21","VAN_EX1_tk9",right.CardId}),"Native then granted deathrattle summon at the original position");
  g=MatchFixture("DRUID");source=g.Summon(0,"VAN_CS2_231");soul=Inject(g,"EX1_158");g.Play(0,soul);soul=Inject(g,"EX1_158");g.Play(0,soul);Check(source.ForestDeathrattles==2,"Repeated Soul of the Forest stacks");source.DamageTaken=source.MaxHealth;g.Cleanup();Check(g.Players[0].Board.Count==2&&g.Players[0].Board.All(u=>u.CardId=="VAN_EX1_tk9"),"Two granted deathrattles summon two Treants");
  g=MatchFixture("DRUID");source=g.Summon(0,"VAN_EX1_556");soul=Inject(g,"EX1_158");g.Play(0,soul);g.Silence(new MatchTarget(0,source.Id));source.DamageTaken=source.MaxHealth;g.Cleanup();Check(g.Players[0].Board.Count==0,"Silence removes native and granted deathrattles");
  g=MatchFixture("DRUID");source=g.Summon(0,"VAN_EX1_556");g.Silence(new MatchTarget(0,source.Id));soul=Inject(g,"EX1_158");g.Play(0,soul);source.DamageTaken=source.MaxHealth;g.Cleanup();Check(g.Players[0].Board.Single().CardId=="VAN_EX1_tk9","Soul applied after silence works while native deathrattle stays silenced");
  g=MatchFixture("DRUID");source=g.Summon(0,"VAN_CS2_231");soul=Inject(g,"EX1_158");g.Play(0,soul);g.Transform(new MatchTarget(0,source.Id),"VAN_CS2_tk1");source=g.Players[0].Board.Single();source.DamageTaken=source.MaxHealth;g.Cleanup();Check(g.Players[0].Board.Count==0,"Transform discards Soul enchantment");
  g=MatchFixture("DRUID");source=g.Summon(0,"VAN_CS2_231");soul=Inject(g,"EX1_158");g.Play(0,soul);g.ReturnToHand(new MatchTarget(0,source.Id));g.Play(0,g.Players[0].Hand.Single().Id);Check(g.Players[0].Board.Single().ForestDeathrattles==0,"Returning to hand and replaying clears the granted deathrattle");
  g=MatchFixture("DRUID");source=g.Summon(0,"VAN_CS2_231");soul=Inject(g,"EX1_158");g.Play(0,soul);g.StealRandomEnemyMinion(1);source.DamageTaken=source.MaxHealth;g.Cleanup();Check(g.Players[0].Board.Count==0&&g.Players[1].Board.Single().CardId=="VAN_EX1_tk9","Granted deathrattle follows current controller after a steal");
  g=MatchFixture("DRUID");source=g.Summon(0,"VAN_CS2_231");for(int i=0;i<6;i++)g.Summon(0,"VAN_CS2_182");soul=Inject(g,"EX1_158");g.Play(0,soul);source.DamageTaken=source.MaxHealth;g.Cleanup();Check(g.Players[0].Board.Count==7,"Soul tokens obey seven-slot capacity");
  g=MatchFixture("DRUID");soul=Inject(g,"EX1_158");Check(g.Play(0,soul).Success&&g.Players[0].Mana==6,"Soul may be cast on an empty board");
  g=MatchFixture("DRUID");enemy=g.Summon(1,"VAN_CS2_182");int savage=Inject(g,"EX1_578");Check(g.Play(0,savage,new MatchTarget(1,enemy.Id)).Success&&enemy.Health==enemy.MaxHealth,"Savage Strike is legal with zero hero attack and deals zero base damage");
  g=MatchFixture("DRUID");enemy=g.Summon(1,"VAN_CS2_182");g.Buff(new MatchTarget(1,enemy.Id),0,10);g.Players[0].TempAttack=3;g.EquipRaw(0,"GAME_DAGGER",1,2,false);g.Summon(0,"VAN_EX1_563");savage=Inject(g,"EX1_578");Check(g.Play(0,savage,new MatchTarget(1,enemy.Id)).Success&&enemy.Health==enemy.MaxHealth-9,"Savage Strike combines hero weapon and temporary attack plus spell damage");Check(g.Players[0].HeroAttacks==0&&g.Players[0].WeaponDurability==2,"Savage Strike does not consume a hero attack or weapon durability");
  g=MatchFixture("DRUID");savage=Inject(g,"EX1_578");Check(!g.Play(0,savage,new MatchTarget(1)).Success&&g.Players[0].Mana==10&&g.Players[0].Hand.Count==1,"Savage Strike cannot target a hero and invalid play is atomic");enemy=g.Summon(1,"VAN_NEW1_023");Check(!g.Play(0,savage,new MatchTarget(1,enemy.Id)).Success&&g.Players[0].Mana==10,"Savage Strike respects spell-target immunity");
  VerifyDruidSpellTcp(folder);var cards=catalog.Deckable(catalog.Pool("classic-2014")).Select(c=>new{Id=c.Id,Name=c.Name,Supported=matchRules.Supports(c)}).ToArray();JsonData.Write(Path.Combine(folder,"match-rule-coverage.json"),new{SupportedCards=cards.Count(c=>c.Supported),TotalCards=382,Cards=cards,Scope="Registry coverage; all Druid spells audit and focused remaining spell checks"});File.WriteAllText(Path.Combine(folder,"druid-spell-verification.txt"),"PASS: "+checks+" targeted assertions. All 19 Classic Druid spells supported; Wild Growth and Excess Mana, Soul enchant stacking, silence/re-enchant, native deathrattles, transformation, bounce, controller, capacity, Savage Strike costs/targets/damage, actual TCP and WPF previews.");
 }
 void VerifyDruidSpellTcp(string folder){
  LeaveLan();ApplyTheme(true,true);ApplyMode(false);SetFullEffects(false);var guest=new PanelWindow{previewRun=true,ShowInTaskbar=false,Opacity=0};guest.Show();guest.ApplyMode(false);guest.ApplyTheme(true,true);
  try{lanPort.Text=FreeLanPort().ToString();lanDeck.SelectedIndex=0;lanClass.SelectedItem=Classes.First(c=>c.Key=="MAGE");BeginLan(true);guest.lanDeck.SelectedIndex=0;guest.lanClass.SelectedItem=Classes.First(c=>c.Key=="DRUID");guest.lanAddress.Text="127.0.0.1:"+lanPort.Text;guest.BeginLan(false);PumpLan(()=>lanReady&&guest.lanReady,"Druid spell fixture connects real TCP peers");DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>guest.match.Players[0].MulliganDone,"Host mulligan synchronized");guest.DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>match.MulliganComplete&&!guest.lanWaiting,"Guest mulligan starts fixture");DoMatch("end");PumpLan(()=>guest.match.Active==1,"Guest receives its spell turn");var game=lanAuthority.Game;foreach(var player in game.Players){player.Hand.Clear();player.Board.Clear();}game.Players[1].MaxMana=game.Players[1].Mana=10;var body=game.Summon(1,"VAN_EX1_556");int soul=Inject(game,"EX1_158",1);PublishLan();PumpLan(()=>guest.match.Players[1].Hand.Any(h=>h.Id==soul),"Soul fixture arrives on guest");guest.BeginCard(soul);PumpLan(()=>!guest.lanWaiting&&body.ForestDeathrattles==1,"Guest Soul effect is settled by host");Check(guest.match.Unit(new MatchTarget(1,body.Id)).ForestDeathrattles==1,"Granted deathrattle counter is public and synchronized");Check(guest.UnitTags(guest.match.Unit(new MatchTarget(1,body.Id))).Contains("亡语"),"Granted deathrattle has a visible battlefield keyword");guest.InspectMatchCard(guest.match.Card(body.CardId),guest.match.Unit(new MatchTarget(1,body.Id)));Check(guest.ForestDetail().Contains("附加亡语 ×1"),"Unit details explain the granted deathrattle");guest.Opacity=1;guest.Render(Path.Combine(folder,"94-soul-of-forest-detail.png"));guest.Opacity=0;guest.inspectMatch=false;
   game.Players[1].Mana=10;int growth=Inject(game,"CS2_013",1);PublishLan();PumpLan(()=>guest.match.Players[1].Hand.Any(h=>h.Id==growth),"Wild Growth fixture arrives");guest.BeginCard(growth);PumpLan(()=>!guest.lanWaiting&&guest.match.Players[1].Hand.Any(h=>h.CardId=="GAME_EXCESS_MANA"),"Host generates private Excess Mana for guest");var publicView=LanProtocol.View(game,0,lanSession,lanRevision);Check(publicView.Players[1].Hand.Length==0,"Generated Excess Mana remains hidden from opponent hand payload");int excess=guest.match.Players[1].Hand.First(h=>h.CardId=="GAME_EXCESS_MANA").Id;guest.BeginCard(excess);PumpLan(()=>!guest.lanWaiting&&!game.Players[1].Hand.Any(h=>h.Id==excess),"Guest may use generated helper through authoritative host");
   game.Players[1].Mana=10;game.Players[1].TempAttack=3;var target=game.Summon(0,"VAN_CS2_182");int savage=Inject(game,"EX1_578",1);PublishLan();PumpLan(()=>guest.match.Players[1].Hand.Any(h=>h.Id==savage),"Savage Strike fixture arrives");int health=target.Health;guest.BeginCard(savage);guest.ClickMatchTarget(new MatchTarget(0,target.Id));PumpLan(()=>!guest.lanWaiting&&target.Health==health-3,"Guest Savage Strike uses authoritative hero attack");body.DamageTaken=body.MaxHealth;game.Cleanup();PublishLan();PumpLan(()=>guest.match.Players[1].Board.Count==2,"Native and granted deathrattle summons synchronize");Check(game.Players[1].Board.Select(u=>u.CardId).SequenceEqual(new[]{"VAN_skele21","VAN_EX1_tk9"})&&guest.match.Players[1].Board.Select(u=>u.CardId).SequenceEqual(game.Players[1].Board.Select(u=>u.CardId)),"Host and guest agree on deathrattle token order");Check(game.Log.SequenceEqual(guest.match.Log),"Druid spell public history agrees on both peers");Render(Path.Combine(folder,"95-druid-spells-normal.png"));ApplyMode(true);Render(Path.Combine(folder,"96-druid-spells-minimal.png"));Check(Width==392&&Height==300,"Druid spell UI preserves minimal dimensions");
  }finally{guest.LeaveLan();guest.Close();LeaveLan();}
 }
}
}
