using System;
using System.IO;
using System.Linq;

namespace Touchfish {
public partial class PanelWindow {
 public void PreviewEmoteSelectionScope(string folder){
  previewRun=true;Directory.CreateDirectory(folder);var authority=new LanHostGame(catalog,matchRules.TrainingDeck("MAGE"),matchRules.TrainingDeck("WARRIOR"),42);authority.Game.Mulligan(0,new int[0]);authority.Game.Mulligan(1,new int[0]);var body=authority.Game.Summon(0,"VAN_CS2_182");body.SummonTurn=0;int revision=authority.Revision;var emote=new LanCommand{Kind="emote",Emote=HeroEmotes.Options("WARRIOR")[0].Value,Session=authority.Session,Revision=revision,RequestId=5};Check(authority.Execute(1,emote).Success&&authority.Revision==revision,"Opponent emote leaves gameplay revision unchanged");Check(authority.Execute(0,new LanCommand{Kind="attack",Source=body.Id,Target=new MatchTarget(1),Session=authority.Session,Revision=revision,RequestId=1}).Success&&authority.Game.Players[1].Health==26,"Attack prepared before emote remains valid");emote.RequestId=6;Check(authority.Execute(1,emote).Success,"Presentation emote accepts an older gameplay revision without changing gameplay");int log=authority.Game.Log.Count;Check(!authority.Execute(1,emote).Success&&authority.Game.Log.Count==log,"Duplicate emote request is rejected without replaying dialogue");Check(!authority.Execute(0,new LanCommand{Kind="end",Session=authority.Session,Revision=revision,RequestId=2}).Success,"Stale gameplay request is still rejected");Check(authority.Snapshot(presentationOnly:true).PresentationOnly&&!authority.Snapshot().PresentationOnly,"Snapshots explicitly distinguish presentation updates");
  VerifyEmoteSelectionTcp(folder);File.WriteAllText(Path.Combine(folder,"emote-selection-verification.txt"),"PASS: "+checks+" targeted assertions. Host and guest preserve selected attack, spell, power and placement while receiving opponent dialogue; prepared attack stays valid, gameplay stale checks remain, duplicate emotes blocked, actual loopback TCP and WPF preview.");
 }
 void VerifyEmoteSelectionTcp(string folder){
  LeaveLan();ApplyMode(false);ApplyTheme(true,true);SetFullEffects(false);var guest=new PanelWindow{previewRun=true,ShowInTaskbar=false,Opacity=0};guest.Show();guest.ApplyMode(false);guest.ApplyTheme(true,true);
  try{lanPort.Text=FreeLanPort().ToString();lanDeck.SelectedIndex=0;lanClass.SelectedItem=Classes.First(c=>c.Key=="MAGE");BeginLan(true);guest.lanDeck.SelectedIndex=0;guest.lanClass.SelectedItem=Classes.First(c=>c.Key=="WARRIOR");guest.lanAddress.Text="127.0.0.1:"+lanPort.Text;guest.BeginLan(false);PumpLan(()=>lanReady&&guest.lanReady,"Selection fixture connects real TCP peers");DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>guest.match.Players[0].MulliganDone,"Host mulligan synchronized");guest.DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>match.MulliganComplete&&!guest.lanWaiting,"Guest mulligan starts fixture");foreach(var p in match.Players){p.Hand.Clear();p.Board.Clear();p.Mana=10;}var own=match.Summon(0,"VAN_CS2_182");var other=match.Summon(1,"VAN_CS2_182");own.SummonTurn=other.SummonTurn=0;PublishLan();PumpLan(()=>guest.match.Players[1].Board.Count==1,"Attack source fixture synchronized");ClickMatchTarget(new MatchTarget(0,own.Id));int revision=lanRevision;guest.DoMatch("emote",emote:HeroEmotes.Options("WARRIOR")[0].Value);PumpLan(()=>match.Players[1].EmoteText==HeroEmotes.Options("WARRIOR")[0].Value&&!guest.lanWaiting,"Guest opponent dialogue reaches host");Check(pending=="attack"&&pendingId==own.Id&&lanRevision==revision,"Host attack selection and revision survive opponent dialogue");Render(Path.Combine(folder,"97-host-attack-through-dialogue.png"));ClickMatchTarget(new MatchTarget(1));PumpLan(()=>guest.match.Players[1].Health==26,"Selected host attack continues after dialogue");Check(pending==""&&own.AttacksUsed==1,"Completed gameplay still clears host pending selection");DoMatch("end");PumpLan(()=>guest.match.Active==1,"Guest becomes active");guest.ClickMatchTarget(new MatchTarget(1,other.Id));revision=lanRevision;DoMatch("emote",emote:HeroEmotes.Options("MAGE")[0].Value);PumpLan(()=>guest.match.Players[0].EmoteText==HeroEmotes.Options("MAGE")[0].Value,"Host dialogue reaches selected guest");Check(guest.pending=="attack"&&guest.pendingId==other.Id&&guest.lanRevision==revision,"Guest attack selection survives presentation-only state replacement");guest.ClickMatchTarget(new MatchTarget(0));PumpLan(()=>!guest.lanWaiting&&match.Players[0].Health==26,"Selected guest attack continues after dialogue");Check(guest.pending=="","Completed guest gameplay still clears pending selection");
   int spell=Inject(match,"CS2_029",1);match.Players[1].Mana=10;PublishLan();PumpLan(()=>guest.match.Players[1].Hand.Any(h=>h.Id==spell),"Foreign hand spell fixture reaches guest");guest.BeginCard(spell);DoMatch("emote",emote:HeroEmotes.Options("MAGE")[1].Value);PumpLan(()=>guest.match.Players[0].EmoteText==HeroEmotes.Options("MAGE")[1].Value,"Dialogue arrives while spell awaits target");Check(guest.pending=="play"&&guest.pendingId==spell,"Pending spell selection survives opponent dialogue");guest.CancelPendingPlay();match.Players[1].ClassId="MAGE";match.Players[1].Mana=10;PublishLan();PumpLan(()=>guest.match.Players[1].ClassId=="MAGE","Targeted power fixture reaches guest");guest.BeginPower();DoMatch("emote",emote:HeroEmotes.Options("MAGE")[2].Value);PumpLan(()=>guest.match.Players[0].EmoteText==HeroEmotes.Options("MAGE")[2].Value,"Dialogue arrives while power awaits target");Check(guest.pending=="power","Pending hero power survives opponent dialogue");guest.ClearPending();match.Players[1].ClassId="DRUID";int claw=Inject(match,"EX1_165",1);PublishLan();PumpLan(()=>guest.match.Players[1].Hand.Any(h=>h.Id==claw),"Choice minion fixture reaches guest");guest.BeginCard(claw);guest.ClickEmptySlot(1,0);DoMatch("emote",emote:HeroEmotes.Options("MAGE")[3].Value);PumpLan(()=>guest.match.Players[0].EmoteText==HeroEmotes.Options("MAGE")[3].Value,"Dialogue arrives during positioned choose-one");Check(guest.pending=="play"&&guest.pendingId==claw&&guest.pendingPosition==0&&guest.ChoicePending(),"Pending placement and choice survive opponent dialogue");Check(match.Log.SequenceEqual(guest.match.Log),"Preserving selections does not change shared ordered history");
  }finally{guest.LeaveLan();guest.Close();LeaveLan();}
 }
}
}
