using System;
using System.IO;
using System.Linq;
namespace Touchfish {
public partial class PanelWindow {
 void VerifyEnrage(string folder){
  int before=checks;fullEffects=true;var ids=EnrageRules.Ids.ToArray();Check(ids.Length==6&&ids.All(id=>matchRules.Supports(catalog.Card("VAN_"+id))),"All six frozen Classic enrage cards supported");
  foreach(string id in ids){var game=MatchFixture("WARRIOR");var unit=game.Summon(0,"VAN_"+id);var target=new MatchTarget(0,unit.Id);if(id=="EX1_009")game.Buff(target,0,2);int bonus=id=="EX1_009"?5:id=="EX1_390"||id=="EX1_393"?3:id=="EX1_412"?1:id=="EX1_414"?6:0;
   Check(!game.IsEnraged(unit)&&game.AttackValue(unit)==unit.BaseAttack,"Healthy enrage inactive "+id);game.Damage(target,1);Check(game.IsEnraged(unit)&&game.AttackValue(unit)==unit.BaseAttack+bonus,"Wounded enrage bonus "+id);game.Damage(target,1);Check(game.AttackValue(unit)==unit.BaseAttack+bonus,"Repeated damage never stacks enrage "+id);game.Heal(target,1);Check(game.IsEnraged(unit),"Partial healing retains enrage "+id);game.Heal(target,1);Check(!game.IsEnraged(unit)&&game.AttackValue(unit)==unit.BaseAttack,"Full healing removes enrage "+id);game.Damage(target,1);game.Silence(target);Check(!game.IsEnraged(unit)&&game.AttackValue(unit)==unit.BaseAttack&&!game.HasWindfury(unit),"Silence removes enrage "+id);
  }
  var g=MatchFixture();var u=g.Summon(0,"VAN_EX1_412");u.SummonTurn=0;var t=new MatchTarget(0,u.Id);Check(g.Attack(0,u.Id,new MatchTarget(1)).Success&&!g.Attack(0,u.Id,new MatchTarget(1)).Success,"Healthy Worgen attacks once");g.Damage(t,1);Check(g.HasWindfury(u)&&g.Attack(0,u.Id,new MatchTarget(1)).Success&&!g.Attack(0,u.Id,new MatchTarget(1)).Success,"Enraged Worgen gains exactly second attack");g.Heal(t,1);g.Damage(t,1);Check(!g.Attack(0,u.Id,new MatchTarget(1)).Success,"Enrage retrigger cannot reset attacks");g.Heal(t,1);Check(!g.HasWindfury(u),"Worgen loses derived windfury when healed");u.Windfury=true;Check(g.HasWindfury(u),"Independent granted windfury survives healing");
  g=MatchFixture("WARRIOR");u=g.Summon(0,"VAN_CS2_221");t=new MatchTarget(0,u.Id);g.Damage(t,1);Check(g.HeroAttack(0)==0,"Enraged smith grants no bare hero attack");g.Equip(0,"VAN_CS2_106");Check(g.WeaponAttackValue(0)==5&&g.Players[0].WeaponAttack==3,"Smith buffs equipped weapon without altering base");var second=g.Summon(0,"VAN_CS2_221");g.Damage(new MatchTarget(0,second.Id),1);Check(g.HeroAttack(0)==7,"Two wounded smiths stack weapon aura");g.Heal(t,1);Check(g.HeroAttack(0)==5,"Healed smith removes own aura");g.Silence(new MatchTarget(0,second.Id));Check(g.HeroAttack(0)==3,"Silenced smith removes weapon aura");g.Damage(t,1);g.EquipRaw(0,"GAME_DAGGER",1,2,false);Check(g.HeroAttack(0)==3,"Replacement weapon receives current aura");g.ReturnToHand(t);Check(g.HeroAttack(0)==1,"Returned smith removes aura");g.Summon(0,"VAN_CS2_221");Check(g.HeroAttack(0)==1,"Resummoned smith starts healthy");g.BreakWeapon(0);Check(g.HeroAttack(0)==0,"Broken weapon has no aura attack");
  g=MatchFixture();u=g.Summon(0,"VAN_EX1_414");Check(g.Attack(0,u.Id,new MatchTarget(1)).Success&&g.Players[1].Health==26,"Healthy Grommash charges for four");u.AttacksUsed=0;g.Damage(new MatchTarget(0,u.Id),1);Check(g.Attack(0,u.Id,new MatchTarget(1)).Success&&g.Players[1].Health==16,"Enraged Grommash attacks for ten");
  g=MatchFixture();u=g.Summon(0,"VAN_EX1_393");u.SummonTurn=0;var enemy=g.Summon(1,"VAN_EX1_393");enemy.SummonTurn=0;Check(g.Attack(0,u.Id,new MatchTarget(1,enemy.Id)).Success&&u.Health==1&&enemy.Health==1&&g.AttackValue(u)==5&&g.AttackValue(enemy)==5,"Combat captures damage before simultaneous enrage");g.SetHealth(new MatchTarget(0,u.Id),1);Check(!g.IsEnraged(u),"Set health clears injury and enrage");u.Shield=true;g.Damage(new MatchTarget(0,u.Id),1);Check(!g.IsEnraged(u),"Absorbed damage cannot enrage");g.Damage(new MatchTarget(0,u.Id),1);g.Cleanup();Check(!g.Players[0].Board.Contains(u),"Lethal injury removes minion");
  g=MatchFixture("WARRIOR");u=g.Summon(0,"VAN_CS2_221");g.Damage(new MatchTarget(0,u.Id),1);var w=g.Summon(0,"VAN_EX1_412");g.Damage(new MatchTarget(0,w.Id),1);g.Equip(0,"VAN_CS2_106");var remote=LanProtocol.ReadView(catalog,LanProtocol.Copy(LanProtocol.View(g,1,"enrage",1)));Check(remote.WeaponAttackValue(0)==5&&remote.AttackValue(remote.Players[0].Board[1])==4&&remote.HasWindfury(remote.Players[0].Board[1]),"Masked LAN snapshot derives identical enrage and weapon effects");Check(remote.Players[0].Hand.Count==0,"Enrage snapshot preserves opponent hand privacy");
  var legendary=g.Summon(0,"VAN_EX1_414");g.Damage(new MatchTarget(0,legendary.Id),1);match=g;matchViewSeat=0;awaitHandoff=false;ClearPending();inspectMatch=false;ApplyMode(false);RenderMatch();ShowPage("match");Render(Path.Combine(folder,"57-enrage-normal.png"));Check(UnitTags(w).Contains("激怒")&&UnitTags(w).Contains("风怒"),"Normal UI shows active enrage and windfury");ApplyMode(true);RenderMatch();Render(Path.Combine(folder,"58-enrage-minimal.png"));CheckNormalWeights(livePanel);ApplyTheme(true,true);ApplyMode(false);RenderMatch();Render(Path.Combine(folder,"59-enrage-colors-dark.png"));ApplyMode(true);RenderMatch();Render(Path.Combine(folder,"60-enrage-colors-minimal-dark.png"));CheckNormalWeights(livePanel);JsonData.Write(Path.Combine(folder,"enrage-verification.json"),new{Cards=ids,Assertions=checks-before,Scope="Frozen Classic; damage, healing, silence, combat, weapon aura, windfury, masked network snapshot and WPF rendering"});
 }
}
}
