using System;
using System.IO;
using System.Linq;
namespace Touchfish {
public partial class PanelWindow {
 void VerifyGiants(string folder){int before=checks;Check(GiantRules.Ids.All(id=>matchRules.Supports(catalog.Card("VAN_"+id))),"All three Classic Giants supported");var mountain=catalog.Card("VAN_EX1_105");var sea=catalog.Card("VAN_EX1_586");var molten=catalog.Card("VAN_EX1_620");Check(mountain.Cost==12&&sea.Cost==10&&molten.Cost==20&&new[]{mountain,sea,molten}.All(card=>card.Attack==8&&card.Health==8),"Frozen Classic Giant costs and stats preserved");
  var g=MatchFixture();int hand=Inject(g,"EX1_105");Check(g.CardCost(0,mountain)==12,"Mountain does not count itself");for(int n=0;n<9;n++)Inject(g,"CS2_182");Check(g.CardCost(0,mountain)==3,"Mountain counts all nine other hand entries");g.Players[0].Mana=3;Check(g.Play(0,hand).Success&&g.Players[0].Mana==0&&g.Players[0].Hand.Count==9&&g.Players[0].Board[0].BaseAttack==8,"Mountain spends pre-play cost before removing itself");
  g=MatchFixture();hand=Inject(g,"EX1_105");int otherMountain=Inject(g,"EX1_105");Check(g.CardCost(0,mountain)==11,"Two Mountains count each other");g.Draw(0,1);Check(g.CardCost(0,mountain)==10,"Draw immediately discounts Mountain");g.DiscardRandom(0,1);Check(g.CardCost(0,mountain)==11,"Discard increases remaining Mountain cost");
  g=MatchFixture();hand=Inject(g,"EX1_586");Check(g.CardCost(0,sea)==10,"Empty board Sea Giant costs ten");for(int seat=0;seat<2;seat++)for(int n=0;n<3;n++)g.Summon(seat,"VAN_CS2_231");Check(g.CardCost(0,sea)==4,"Sea Giant counts both boards");g.Players[0].Mana=4;Check(g.Play(0,hand).Success&&g.Players[0].Mana==0&&g.Players[0].Board.Last().BaseHealth==8,"Sea Giant excludes its own future body from paid cost");g=MatchFixture();for(int seat=0;seat<2;seat++)for(int n=0;n<5;n++)g.Summon(seat,"VAN_CS2_231");hand=Inject(g,"EX1_586");g.Players[0].Mana=0;Check(g.CardCost(0,sea)==0&&g.Play(0,hand).Success,"Sea Giant can be played for zero");var removed=g.Players[1].Board[0];removed.DamageTaken=removed.MaxHealth;g.Cleanup();Check(g.CardCost(0,sea)==0,"Sea cost tracks deaths and remaining board");
  g=MatchFixture();hand=Inject(g,"EX1_620");Check(g.CardCost(0,molten)==20,"Full-health Molten Giant costs twenty");g.Players[0].Armor=10;g.Damage(new MatchTarget(0),8);Check(g.CardCost(0,molten)==20,"Armor absorption does not discount Molten");g.Damage(new MatchTarget(0),7);Check(g.CardCost(0,molten)==15,"Only lost hero health discounts Molten");g.Heal(new MatchTarget(0),3);Check(g.CardCost(0,molten)==18,"Healing raises Molten cost again");g.Players[0].Health=10;g.Players[0].Mana=0;Check(g.CardCost(0,molten)==0&&g.Play(0,hand).Success,"Classic Molten becomes free at ten health");g.Players[0].Health=1;Check(g.CardCost(0,molten)==0,"Giant cost never negative");
  g=MatchFixture("WARLOCK");g.Summon(0,"VAN_EX1_315");g.Summon(0,"VAN_EX1_315");hand=Inject(g,"EX1_105");for(int n=0;n<9;n++)Inject(g,"CS2_182");Check(g.CardCost(0,mountain)==0,"Mountain intrinsic reduction follows Portal floor");g.Players[0].Health=10;Check(g.CardCost(0,molten)==0,"Molten intrinsic reduction follows Portal floor");g=MatchFixture();hand=Inject(g,"EX1_620");g.Players[0].Health=10;var tax=g.Summon(1,"VAN_EX1_616");Check(g.CardCost(0,molten)==1,"Mana Wraith tax combines with Giant discount");g.Silence(new MatchTarget(1,tax.Id));Check(g.CardCost(0,molten)==0,"Removed tax updates Giant cost");
  g=MatchFixture();hand=Inject(g,"EX1_105");g.Players[0].Mana=10;int beforeHand=g.Players[0].Hand.Count;Check(!g.Play(0,hand).Success&&g.Players[0].Hand.Count==beforeHand&&g.Players[0].Mana==10&&g.Players[0].Board.Count==0,"Unaffordable Giant leaves state unchanged");g.Players[0].Health=10;int free=Inject(g,"EX1_620");for(int n=0;n<7;n++)g.Summon(0,"VAN_CS2_231");Check(!g.Play(0,free).Success&&g.Players[0].Hand.Count==2,"Free Giant still respects seven-slot cap");
  g=MatchFixture();hand=Inject(g,"EX1_105");for(int n=0;n<4;n++)Inject(g,"CS2_182");Inject(g,"EX1_586");Inject(g,"EX1_620");g.Players[0].Health=14;g.Summon(0,"VAN_CS2_182");g.Summon(1,"VAN_CS2_182");var masked=LanProtocol.ReadView(catalog,LanProtocol.Copy(LanProtocol.View(g,1,"giants",1)));Check(masked.Players[0].Hand.Count==0&&masked.CardCost(0,mountain)==g.CardCost(0,mountain)&&masked.CardCost(0,sea)==g.CardCost(0,sea)&&masked.CardCost(0,molten)==g.CardCost(0,molten),"Public counts compute Giant costs without leaking opponent hand");match=g;matchViewSeat=0;awaitHandoff=false;ClearPending();inspectMatch=false;ApplyMode(false);RenderMatch();ShowPage("match");Render(Path.Combine(folder,"70-three-giants-normal.png"));InspectMatchCard(molten);Render(Path.Combine(folder,"71-giant-hand-details.png"));inspectMatch=false;ApplyMode(true);RenderMatch();Render(Path.Combine(folder,"72-three-giants-minimal.png"));CheckNormalWeights(livePanel);JsonData.Write(Path.Combine(folder,"giant-verification.json"),new{Assertions=checks-before,FrozenCosts=new[]{12,10,20},HandExcludesSelf=true,BothBoards=true,HealthLossNotArmor=true,HealingUpdatesCost=true,IntrinsicAfterAura=true,MaskedSnapshot=true});
 }
}
}
