using System;
using System.IO;
using System.Linq;
using System.Diagnostics;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;

namespace Touchfish {
public partial class PanelWindow {
 public void PreviewHeroVisualScope(string folder){
  previewRun=true;Directory.CreateDirectory(folder);LeaveLan();localTest=false;awaitHandoff=false;inspectMatch=false;testTakeOpen=false;ClearPending();
  match=MatchFixture("DRUID");matchViewSeat=0;ApplyTheme(true,true);ApplyMode(false);ShowPage("match");
  Check(match.HeroPower(0).Success&&match.HeroAttack(0)==1,"Druid power supplies one attack without a weapon");RenderMatch();UseWeaponSlot(0,true);Check(pending=="heroattack"&&HeroWeaponLabel(0)=="攻击 · 1","Weapon slot selects unarmed Druid attack");ClickMatchTarget(new MatchTarget(1));Check(match.Players[1].Health==29&&match.Players[0].HeroAttacks==1,"Druid slot attack damages target and consumes attack");UseWeaponSlot(0,true);Check(pending!="heroattack","Weapon slot cannot attack twice");
  match.Players[0].HeroAttacks=0;match.EquipRaw(0,"GAME_DAGGER",1,2,false);Check(match.HeroAttack(0)==2&&HeroWeaponLabel(0).Contains("2/2"),"Weapon slot adds weapon and Druid temporary attack");UseWeaponSlot(0,true);ClickMatchTarget(new MatchTarget(1));Check(match.Players[1].Health==27&&match.Players[0].WeaponDurability==1,"Combined attack consumes one weapon durability");match.EndTurn();Check(match.HeroAttack(0)==1,"Druid temporary attack expires while weapon remains");
  SetFullEffects(false);Check(RarityColor("LEGENDARY")==Muted&&RarityColor("EPIC")==Muted&&RarityColor("RARE")==Muted,"Deck rarity colors disabled by effects setting");SetFullEffects(true);Check(RarityColor("LEGENDARY")!=Muted&&RarityColor("EPIC")!=Muted,"Deck rarity colors enabled by effects setting");ShowPage("deck");Render(Path.Combine(folder,"83-deck-rarity-effects-on.png"));SetFullEffects(false);Render(Path.Combine(folder,"84-deck-rarity-effects-off.png"));ShowPage("match");
  match=MatchFixture();RenderMatch();var heroTarget=visualTargets[VisualKey(0,0)];heroTarget.RaiseEvent(new MouseButtonEventArgs(Mouse.PrimaryDevice,0,MouseButton.Right){RoutedEvent=UIElement.PreviewMouseRightButtonDownEvent});Check(emoteOpen,"Right-clicking a hero opens the emote menu");var emoteMenu=livePanel.Children.OfType<ScrollViewer>().Select(view=>view.Content as Grid).FirstOrDefault(grid=>grid!=null&&grid.Children.OfType<Border>().Count()==6);Check(emoteMenu!=null&&emoteMenu.ColumnDefinitions.Count==2&&emoteMenu.Children.OfType<Border>().Count(cell=>Grid.GetColumn(cell)==0)==3&&emoteMenu.Children.OfType<Border>().Count(cell=>Grid.GetColumn(cell)==1)==3,"Emote menu has the requested two columns of three choices");Render(Path.Combine(folder,"88-hero-emote-menu.png"));emoteOpen=false;RenderMatch();var renderer=(OfficeMatchVisualEffects)matchEffects;int bubbles=renderer.EmoteCount;match.Emote(0,HeroEmotes.Options("MAGE")[3].Value);RenderMatch();PumpLan(()=>renderer.EmoteCount==bubbles+1,"Emote bubble shows with full effects off");var visual=LanProtocol.ReadView(catalog,LanProtocol.Copy(LanProtocol.View(match,1,"bubble",1)));Check(visual.VisualEvents.Last().Kind=="emote"&&visual.VisualEvents.Last().CardName==HeroEmotes.Options("MAGE")[3].Value,"Validated emote event survives masked network snapshot");Check(OfficeMatchVisualEffects.EmoteFadeDelayMs==2000&&OfficeMatchVisualEffects.EmoteFadeDurationMs==500,"Hero dialogue stays visible for two seconds before fading");Render(Path.Combine(folder,"85-hero-speech-bubble.png"));RenderMatch();UpdateLayout();Check(renderer.EmoteCount==bubbles+1,"Same snapshot does not replay speech bubble");ApplyMode(true);int emoteLog=match.Log.Count;DoMatch("emote",emote:HeroEmotes.Options("MAGE")[3].Value);Check(match.Log.Count==emoteLog,"Minimal blocks local dialogue sending");emoteOpen=true;RenderMatch();Check(!emoteOpen,"Minimal closes dialogue panel and retains hand");bubbles=renderer.EmoteCount;match.Emote(0,HeroEmotes.Options("MAGE")[3].Value);RenderMatch();UpdateLayout();Check(renderer.EmoteCount==bubbles&&matchEffectsCanvas.Children.Count==0,"Minimal remains silent for emote events");ApplyMode(false);RenderMatch();UpdateLayout();Check(renderer.EmoteCount==bubbles,"Minimal events never replay on returning to normal");
  var g=MatchFixture();int wing=Inject(g,"NEW1_030");g.Players[0].Mana=9;Check(!g.Play(0,wing).Success&&g.VisualEvents.All(e=>e.Kind!="entrance"),"Rejected Deathwing play emits no entrance");g.Players[0].Mana=10;Check(g.Play(0,wing).Success&&g.VisualEvents.Count(e=>e.Kind=="entrance")==1,"Successful Deathwing emits one entrance event");
  SetFullEffects(false);int entrances=renderer.EntranceCount;renderer.Entrance(g.VisualEvents.First(e=>e.Kind=="entrance"));Check(renderer.EntranceCount==entrances,"Deathwing entrance is disabled without full effects");
  VerifyHeroVisualTcp(folder);File.WriteAllText(Path.Combine(folder,"hero-visuals-verification.txt"),"PASS: "+checks+" targeted assertions. Druid weapon-slot attack, combined attack and durability, rarity setting, speech bubbles, Deathwing 2-second entrance, minimal suppression, repeat suppression, actual WPF previews and real loopback TCP peers. No physical two-computer validation.");
 }
 void VerifyHeroVisualTcp(string folder){
  LeaveLan();ApplyTheme(true,true);ApplyMode(false);SetFullEffects(true);var guest=new PanelWindow{previewRun=true,ShowInTaskbar=false,Opacity=0};guest.Show();guest.ApplyMode(false);guest.ApplyTheme(true,true);guest.SetFullEffects(true);
  try{lanPort.Text=FreeLanPort().ToString();lanClass.SelectedItem=Classes.First(c=>c.Key=="DRUID");lanDeck.SelectedIndex=0;BeginLan(true);guest.lanClass.SelectedItem=Classes.First(c=>c.Key=="MAGE");guest.lanDeck.SelectedIndex=0;guest.lanAddress.Text="127.0.0.1:"+lanPort.Text;guest.BeginLan(false);PumpLan(()=>lanReady&&guest.lanReady,"Visual fixture connects two real TCP WPF peers");DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>guest.match.Players[0].MulliganDone,"Host mulligan reaches guest");guest.DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>match.MulliganComplete&&guest.match.MulliganComplete&&!guest.lanWaiting,"Guest mulligan completes real network game");match.Players[0].Mana=10;DoMatch("power");PumpLan(()=>guest.match.HeroAttack(0)==1,"Druid temporary attack survives public network snapshot");UseWeaponSlot(0,true);ClickMatchTarget(new MatchTarget(1));PumpLan(()=>guest.match.Players[1].Health==29,"Druid slot attack is authoritative over TCP");
   var hostRenderer=(OfficeMatchVisualEffects)matchEffects;var guestRenderer=(OfficeMatchVisualEffects)guest.matchEffects;int hostBubbles=hostRenderer.EmoteCount,guestBubbles=guestRenderer.EmoteCount;guest.DoMatch("emote",emote:HeroEmotes.Options("MAGE")[3].Value);PumpLan(()=>!guest.lanWaiting&&hostRenderer.EmoteCount==hostBubbles+1&&guestRenderer.EmoteCount==guestBubbles+1,"Non-active guest speech bubbles appear on both peers");
   match.Players[0].Mana=10;match.Players[0].Hand.Clear();int wing=Inject(match,"NEW1_030");Inject(match,"CS2_182");match.Summon(1,"VAN_CS2_182");PublishLan();PumpLan(()=>guest.match.Players[0].HandCount==2,"Deathwing fixture exposes hand count only");int hostEntrances=hostRenderer.EntranceCount,guestEntrances=guestRenderer.EntranceCount;DoMatch("play",wing);PumpLan(()=>hostRenderer.EntranceCount==hostEntrances+1&&guestRenderer.EntranceCount==guestEntrances+1,"Deathwing entrance is synchronized to both peers");Check(OfficeMatchVisualEffects.EntranceDurationMs==2000&&matchEffectsCanvas.Children.OfType<TextBlock>().Count(t=>t.Text=="火")==44,"Deathwing produces forty-four red fire glyphs for two seconds");var watch=Stopwatch.StartNew();PumpLan(()=>watch.ElapsedMilliseconds>=200,"Entrance reaches visible animation frame");Render(Path.Combine(folder,"86-deathwing-entrance.png"));Check(Width==548&&Height==474,"Entrance keeps standard office dimensions");PublishLan();PumpLan(()=>guest.match.VisualEvents.Count==match.VisualEvents.Count,"Repeat entrance snapshot arrives");UpdateLayout();Check(guestRenderer.EntranceCount==guestEntrances+1,"Repeated snapshots do not replay entrance");PumpLan(()=>watch.ElapsedMilliseconds>=2200,"Entrance clock expires");Check(!matchEffectsCanvas.Children.OfType<TextBlock>().Any(t=>t.Text=="火"),"Fire glyphs are removed after two seconds");Check(((TranslateTransform)shell.RenderTransform).X==0,"Two-second screen shake returns to rest");
   guest.SetFullEffects(false);int mutedEntrances=guestRenderer.EntranceCount;match.Players[0].Mana=10;wing=Inject(match,"NEW1_030");DoMatch("play",wing);PumpLan(()=>guest.match.AnimationPlaying,"Muted guest receives authoritative animation wait");Check(!CanMatchInput()&&!guest.CanMatchInput()&&guest.livePrompt.Text.Contains("正在播放动画"),"Both peers are locked and muted peer displays animation status");int revision=lanAuthority.Revision;var rejected=lanAuthority.Execute(1,new LanCommand{Kind="emote",Emote=HeroEmotes.Options("MAGE")[3].Value,Revision=revision,Session=lanSession});Check(!rejected.Success&&rejected.Message.Contains("播放动画")&&lanAuthority.Revision==revision,"Host rejects forged commands during entrance without state change");Check(guestRenderer.EntranceCount==mutedEntrances&&!guest.matchEffectsCanvas.Children.OfType<TextBlock>().Any(t=>t.Text=="火"),"Muted guest waits without displaying fire");PublishLan();PumpLan(()=>guest.match.AnimationPlaying,"Repeated waiting snapshot arrives");guest.Opacity=1;guest.Render(Path.Combine(folder,"87-muted-animation-wait.png"));guest.Opacity=0;guest.ApplyMode(true);int mutedRevision=lanAuthority.Revision;guest.DoMatch("emote",emote:HeroEmotes.Options("MAGE")[3].Value);Check(!guest.lanWaiting&&lanAuthority.Revision==mutedRevision&&guest.status.Text.Contains("禁用对话"),"Minimal blocks network dialogue requests");Check(guest.match.AnimationPlaying&&!guest.CanMatchInput()&&guest.livePrompt.Text.Contains("正在播放动画")&&guest.matchEffectsCanvas.Children.Count==0,"Switching to minimal cannot bypass shared animation lock");SetFullEffects(false);Check(match.AnimationPlaying&&!CanMatchInput(),"Disabling effects does not cancel an active shared wait");PumpLan(()=>!match.AnimationPlaying&&!guest.match.AnimationPlaying&&CanMatchInput(),"Both peers automatically unlock at animation end");
   match.Players[0].Mana=10;wing=Inject(match,"NEW1_030");DoMatch("play",wing);Check(!match.AnimationPlaying,"Both effects disabled causes no unnecessary entrance wait");
   guest.ApplyMode(false);guest.SetFullEffects(true);PumpLan(()=>match.EntranceAnimationsEnabled,"Guest presentation setting reaches muted host");match.Players[0].Mana=10;wing=Inject(match,"NEW1_030");int mutedHostEntrances=hostRenderer.EntranceCount;guestEntrances=guestRenderer.EntranceCount;DoMatch("play",wing);PumpLan(()=>guestRenderer.EntranceCount==guestEntrances+1&&guest.match.AnimationPlaying,"Guest-only effects animate while both peers wait");Check(hostRenderer.EntranceCount==mutedHostEntrances&&match.AnimationPlaying&&!CanMatchInput(),"Muted host is locked when only guest enables effects");PumpLan(()=>!match.AnimationPlaying&&!guest.match.AnimationPlaying,"Guest-only animation wait ends automatically");
   ApplyMode(true);SetFullEffects(true);int count=hostRenderer.EntranceCount;hostRenderer.Entrance(new MatchVisualEvent{Kind="entrance",CardName="NEW1_030"});Check(hostRenderer.EntranceCount==count&&matchEffectsCanvas.Children.Count==0,"Minimal blocks entrance even with effects enabled");ApplyMode(false);hostRenderer.Entrance(new MatchVisualEvent{Kind="entrance",CardName="NEW1_030"});SetFullEffects(false);Check(matchEffectsCanvas.Children.Count==0&&shell.RenderTransform==Transform.Identity,"Disabling effects clears active fire and screen shake");
  }finally{guest.LeaveLan();guest.Close();LeaveLan();}
 }
}
}
