using System;
using System.IO;
using System.Linq;
using System.Windows;
using System.Windows.Controls;

namespace Touchfish {
public partial class PanelWindow {
 Grid lanPanel;ComboBox lanClass,lanDeck;TextBox lanAddress,lanPort;TextBlock lanNotice;Button hostButton,joinButton,leaveButton,testButton,copyAddressButton,addressChoiceButton;
 LanPeer lanPeer;LanHostGame lanAuthority;DeckDocument lanChosenDeck;bool lanMode,lanReady,lanIsHost,lanWaiting,localTest;string lanFingerprint,lanSession;int lanRevision,lanRequestId,lanPendingRequest;
 void BuildLanUi(){
  lanPanel=new Grid{Margin=new Thickness(12,8,12,8),Visibility=Visibility.Collapsed};foreach(double h in new[]{22.0,48,42,-1,24})lanPanel.RowDefinitions.Add(new RowDefinition{Height=h<0?new GridLength(1,GridUnitType.Star):new GridLength(h)});Put(shell,lanPanel,4);lanPanel.Children.Add(T("局域网对战",12,Ink));
  var choice=new Grid();choice.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(90)});choice.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(8)});choice.ColumnDefinitions.Add(new ColumnDefinition());lanClass=Picker(Classes);lanClass.SelectedItem=Classes.First(c=>c.Key==draft.ClassId);lanDeck=Picker(new Choice[0]);choice.Children.Add(LobbyField("我的职业",lanClass));var deck=LobbyField("我的卡组",lanDeck);Grid.SetColumn(deck,2);choice.Children.Add(deck);Put(lanPanel,choice,1);BindDeckClass(lanClass,lanDeck);RefreshLanDecks();
  var fields=new Grid();fields.ColumnDefinitions.Add(new ColumnDefinition());fields.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(34)});fields.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(8)});fields.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(54)});lanAddress=Input("");lanAddress.ToolTip="朋友创建房间后，将其局域网 IPv4 地址填在这里，可带 :端口。";lanPort=Input(LanProtocol.Port.ToString());lanPort.ToolTip="创建房间的端口，默认 42671。";fields.Children.Add(LanField("房主地址",lanAddress));var port=LanField("端口",lanPort);Grid.SetColumn(port,3);fields.Children.Add(port);copyAddressButton=Btn("复制",34);copyAddressButton.Height=23;copyAddressButton.FontSize=9;copyAddressButton.VerticalAlignment=VerticalAlignment.Bottom;copyAddressButton.ToolTip="复制完整房主地址（含端口）";copyAddressButton.Click+=(s,e)=>CopyLanAddress();Grid.SetColumn(copyAddressButton,1);fields.Children.Add(copyAddressButton);addressChoiceButton=Btn("⌄",16);addressChoiceButton.Height=23;addressChoiceButton.HorizontalAlignment=HorizontalAlignment.Right;addressChoiceButton.VerticalAlignment=VerticalAlignment.Bottom;addressChoiceButton.Visibility=Visibility.Collapsed;addressChoiceButton.ToolTip="选择网卡地址";addressChoiceButton.Click+=(s,e)=>{if(addressChoiceButton.ContextMenu!=null){addressChoiceButton.ContextMenu.PlacementTarget=addressChoiceButton;addressChoiceButton.ContextMenu.IsOpen=true;}};fields.Children.Add(addressChoiceButton);lanAddress.Padding=new Thickness(3,0,18,0);copyAddressButton.IsEnabled=false;lanAddress.TextChanged+=(s,e)=>copyAddressButton.IsEnabled=!String.IsNullOrWhiteSpace(lanAddress.Text);Put(lanPanel,fields,2);
  lanNotice=T("双方连接同一局域网，各自选职业和卡组。一人创建房间，另一人填房主地址后加入。",10,Muted);lanNotice.TextWrapping=TextWrapping.Wrap;Put(lanPanel,new ScrollViewer{Content=lanNotice,VerticalScrollBarVisibility=ScrollBarVisibility.Auto},3);
  var actions=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};leaveButton=Btn("离开",40);leaveButton.Click+=(s,e)=>{LeaveLan();lanNotice.Text="已离开房间，可重新创建或加入。";};actions.Children.Add(leaveButton);var resume=Btn("返回对局",64);resume.Click+=(s,e)=>{if(lanMode&&match!=null){RenderMatch();ShowPage("match");}else lanNotice.Text="尚未开始局域网对局。";};actions.Children.Add(resume);hostButton=Btn("创建房间",64);hostButton.Click+=(s,e)=>BeginLan(true);actions.Children.Add(hostButton);joinButton=Btn("加入",40);joinButton.Click+=(s,e)=>BeginLan(false);actions.Children.Add(joinButton);Put(lanPanel,actions,4);SetLanFields(false);Closed+=(s,e)=>{if(lanPeer!=null)lanPeer.Dispose();};
 }
 FrameworkElement LanField(string caption,TextBox input){var stack=new StackPanel();stack.Children.Add(T(caption,9,Muted));input.Height=23;input.Margin=new Thickness(0,2,0,0);stack.Children.Add(input);return stack;}
 void RefreshLanDecks(){if(lanDeck==null)return;string previous=lanDeck.SelectedItem==null?"training":((Choice)lanDeck.SelectedItem).Key;var choices=new[]{new Choice("training","基础练习卡组"),new Choice("draft","当前编辑卡组")}.Concat(savedDecks.Select(d=>new Choice(d.Id,d.Name))).ToArray();lanDeck.ItemsSource=choices;lanDeck.SelectedItem=choices.FirstOrDefault(c=>c.Key==previous)??choices[0];}
 void SetLanFields(bool busy){lanClass.IsEnabled=lanDeck.IsEnabled=lanAddress.IsEnabled=lanPort.IsEnabled=hostButton.IsEnabled=joinButton.IsEnabled=!busy;leaveButton.IsEnabled=busy;lanAddress.IsReadOnly=busy&&lanIsHost;if(lanAddress.IsReadOnly)lanAddress.IsEnabled=true;if(!busy||!lanIsHost)addressChoiceButton.Visibility=Visibility.Collapsed;if(!busy)SyncChosenDeckClass(lanClass,lanDeck);}
 void SetHostAddresses(string addresses){var choices=addresses.Split(new[]{" / "},StringSplitOptions.RemoveEmptyEntries);lanAddress.Text=choices.FirstOrDefault()??"";var menu=new ContextMenu{Background=B("#FFFFFF"),Foreground=Ink,BorderBrush=Line,FontWeight=FontWeights.Normal};foreach(string value in choices){string address=value;var item=new MenuItem{Header=address,Foreground=Ink,Background=B("#FFFFFF"),FontSize=10,FontWeight=FontWeights.Normal};item.Click+=(s,e)=>lanAddress.Text=address;menu.Items.Add(item);}addressChoiceButton.ContextMenu=menu;addressChoiceButton.Visibility=choices.Length>1?Visibility.Visible:Visibility.Collapsed;}
 void CopyLanAddress(){string address=lanAddress.Text.Trim();if(address.Length==0)return;if(!address.Contains(":"))address+=":"+lanPort.Text.Trim();if(previewRun){status.Text="房主地址已复制："+address;return;}try{Clipboard.SetText(address);status.Text="房主地址已复制："+address;}catch(System.Runtime.InteropServices.ExternalException){status.Text="复制暂不可用，请选中地址后按 Ctrl+C。";}}
 void OpenLan(){if(localTest){match=null;ClearPending();localTest=false;}RefreshLanDecks();if(lanMode&&match!=null){RenderMatch();ShowPage("match");}else ShowPage("lan");}
 void OpenLocalTest(){if(lanMode){status.Text="先离开局域网房间，再打开本地 test。";return;}localTest=true;RefreshLobbyDecks();if(match!=null){RenderMatch();ShowPage("match");}else ShowPage("lobby");}
 void LeaveLan(){var peer=lanPeer;lanPeer=null;if(peer!=null)peer.Dispose();lanMode=lanReady=lanWaiting=false;lanAuthority=null;lanSession=null;match=null;awaitHandoff=false;ClearPending();inspectMatch=false;SetLanFields(false);ShowPage("lan");status.Text="未连接";}
 void UiLan(LanPeer peer,Action action){if(Dispatcher.HasShutdownStarted)return;Dispatcher.BeginInvoke(new Action(()=>{if(lanPeer==peer)action();}));}
 void BeginLan(bool hosting){
  if(lanPeer!=null)return;try{lanChosenDeck=LobbyDeck(lanClass,lanDeck);DeckRules.Validate(catalog,lanChosenDeck,true);var unsupported=lanChosenDeck.Cards.Keys.Where(id=>!matchRules.Supports(catalog.Card(id))).ToArray();if(unsupported.Length>0)throw new InvalidOperationException("卡组含【暂不可用】卡牌："+String.Join("、",unsupported.Take(3).Select(id=>catalog.Card(id).Name)));int port=LanProtocol.Port;System.Net.IPEndPoint endpoint=null;if(hosting){if(!Int32.TryParse(lanPort.Text,out port)||port<1024||port>65535)throw new InvalidOperationException("端口应为 1024–65535。");}else{string address=lanAddress.Text.Trim();if(!address.Contains(":")){if(!Int32.TryParse(lanPort.Text,out port)||port<1024||port>65535)throw new InvalidOperationException("端口应为 1024–65535。");address+=":"+port;}endpoint=LanProtocol.Endpoint(address);}
   lanFingerprint=LanProtocol.Fingerprint(catalog);lanIsHost=hosting;lanMode=true;localTest=false;lanReady=lanWaiting=false;match=null;lanAuthority=null;lanSession=null;var peer=new LanPeer();lanPeer=peer;peer.Connected+=()=>UiLan(peer,()=>{if(!hosting)peer.Send(new LanMessage{Kind="hello",FullEffectsEnabled=fullEffects&&!minimal,Fingerprint=lanFingerprint,PoolId=lanChosenDeck.PoolId,Code=DeckCode.Encode(catalog,lanChosenDeck)});lanNotice.Text="已连接，正在确认卡组与版本。";});peer.Received+=message=>UiLan(peer,()=>ReceiveLan(message));peer.Disconnected+=reason=>UiLan(peer,()=>DisconnectLan(reason));SetLanFields(true);
   if(hosting){peer.Host(port);string addresses=LanProtocol.Addresses(port);SetHostAddresses(addresses);lanNotice.Text="房间已创建，等待朋友加入。\n房主地址："+(addresses.Length>0?addresses:"未找到局域网 IPv4 地址")+"\n若 Windows 弹出防火墙提示，允许在专用网络中访问。";}else{peer.Join(endpoint);lanNotice.Text="正在连接 "+endpoint+" …";}status.Text=hosting?"等待连接":"正在连接";
  }catch(Exception ex){if(!(ex is InvalidOperationException||ex is InvalidDataException||ex is System.Net.Sockets.SocketException||ex is IOException))throw;if(lanPeer!=null){lanPeer.Dispose();lanPeer=null;}lanMode=false;SetLanFields(false);lanNotice.Text=ex.Message;}
 }
 void DisconnectLan(string reason){lanReady=lanWaiting=false;ClearPending();lanNotice.Text="连接已断开："+reason+" 可离开后重新建房或加入。";status.Text=lanNotice.Text;if(lanPeer!=null){lanPeer.Dispose();lanPeer=null;}if(match!=null)RenderMatch();else ShowPage("lan");}
 void ReceiveLan(LanMessage message){
  try{if(message.Protocol!=1)throw new InvalidDataException("联机协议不同，请使用相同版本程序。");if(lanIsHost){
    if(message.Kind=="hello"){if(lanReady||lanAuthority!=null)throw new InvalidDataException("房间已开始。");if(message.Fingerprint!=lanFingerprint)throw new InvalidDataException("程序或牌库版本不同，请双方使用同一份完整包。");if(message.PoolId!=lanChosenDeck.PoolId)throw new InvalidDataException("双方卡组的卡池不同。");if(String.IsNullOrWhiteSpace(message.Code)||message.Code.Length>17000)throw new InvalidDataException("卡组代码无效。");var guest=DeckCode.Decode(catalog,message.Code,message.PoolId);lanAuthority=new LanHostGame(catalog,lanChosenDeck,guest,Environment.TickCount);lanAuthority.SetPresentation(0,fullEffects&&!minimal);lanAuthority.SetPresentation(1,message.FullEffectsEnabled);match=lanAuthority.Game;lanSession=lanAuthority.Session;lanRevision=0;lanReady=true;matchViewSeat=0;awaitHandoff=false;ClearPending();inspectMatch=false;matchHandScroll=0;PublishLan();RenderMatch();ShowPage("match");status.Text="局域网已连接 · 我方先手";return;}
    if(message.Kind=="presentation"&&lanReady){lanAuthority.SetPresentation(1,message.FullEffectsEnabled);return;}
    if(message.Kind=="command"&&lanReady){var result=lanAuthority.Execute(1,message.Command);lanRevision=lanAuthority.Revision;PublishLan(result,message.Command==null?0:message.Command.RequestId);if(result.Success){ClearPending();inspectMatch=false;RenderMatch();}return;}
    throw new InvalidDataException("房间收到无效消息。");
   }else{if(message.Kind=="error"){DisconnectLan(message.Message);return;}if(message.Kind!="state"||message.State==null)throw new InvalidDataException("收到无效对局消息。");if(lanReady&&message.State.Session!=lanSession)throw new InvalidDataException("对局标识不一致。");if(lanReady&&message.State.Revision<lanRevision)return;bool ownReply=message.ReplyId!=0&&message.ReplyId==lanPendingRequest;int previousAnimation=match==null?-1:match.AnimationSequence,remaining=match==null?0:match.AnimationRemainingMs;match=LanProtocol.ReadView(catalog,message.State);if(previousAnimation==match.AnimationSequence&&remaining>0&&message.State.AnimationRemainingMs>0){match.LimitAnimationWait(remaining);}lanSession=message.State.Session;lanRevision=message.State.Revision;lanReady=true;matchViewSeat=1;awaitHandoff=false;if(ownReply||!lanWaiting){lanWaiting=false;ClearPending();inspectMatch=false;}matchHandScroll=Math.Max(0,matchHandScroll);RenderMatch();if(currentPage=="lan")ShowPage("match");status.Text=match.AnimationPlaying?"正在播放动画 · 暂停操作":message.Message;}
  }catch(Exception ex){if(!(ex is InvalidDataException||ex is InvalidOperationException||ex is ArgumentException))throw;if(lanIsHost&&lanPeer!=null)lanPeer.Send(new LanMessage{Kind="error",Message=ex.Message});lanReady=false;lanNotice.Text=ex.Message;status.Text=ex.Message;if(match!=null)RenderMatch();else ShowPage("lan");}
 }
 void PublishLan(ActionResult result=null,int replyId=0){if(lanPeer==null||!lanPeer.Send(lanAuthority.Snapshot(result,replyId)))DisconnectLan("发送失败。");}
 bool CanMatchInput(){if(match==null||match.Finished||awaitHandoff||match.AnimationPlaying)return false;if(lanMode&&!lanReady||lanWaiting)return false;if(!match.MulliganComplete)return !match.Players[matchViewSeat].MulliganDone;return !lanMode||match.Active==matchViewSeat;}
 void DoMatch(string kind,int source=0,MatchTarget target=null,int position=-1,string choice=null,int[] selectedIds=null,string emote=null){
  if(kind=="emote"&&minimal){status.Text="极简模式已禁用对话。";return;}
  if(lanMode){bool mayEmote=kind=="emote"&&match!=null&&match.MulliganComplete&&!match.AnimationPlaying&&!match.Finished&&lanReady&&!lanWaiting;if(!CanMatchInput()&&!mayEmote){status.Text=match!=null&&match.AnimationPlaying?"正在播放动画，请稍候。":!lanReady?"连接已断开，请重新建房。":lanWaiting?"等待同步。":"等待对方操作。";return;}var command=new LanCommand{Kind=kind,Source=source,Target=target,Position=position,Choice=choice,SelectedHandIds=selectedIds,Emote=emote,Session=lanSession,Revision=lanRevision,RequestId=++lanRequestId};if(lanIsHost){var result=lanAuthority.Execute(0,command);lanRevision=lanAuthority.Revision;PublishLan(result);ApplyMatchAction(result);}else{lanWaiting=true;lanPendingRequest=command.RequestId;if(lanPeer==null||!lanPeer.Send(new LanMessage{Kind="command",Command=command})){DisconnectLan("发送失败。");return;}RenderMatch();status.Text="等待同步。";}return;}
  ActionResult local;switch(kind){case "mulligan":local=match.Mulligan(matchViewSeat,selectedIds);if(local.Success){handoffSeat=match.MulliganComplete?match.Active:1-matchViewSeat;awaitHandoff=true;}break;case "emote":local=match.Emote(matchViewSeat,emote);break;case "play":local=match.Play(matchViewSeat,source,target,position,choice);break;case "attack":local=match.Attack(matchViewSeat,source,target);break;case "power":local=match.HeroPower(matchViewSeat,target);break;default:local=match.EndTurn();if(local.Success&&!match.Finished){handoffSeat=match.Active;awaitHandoff=true;}break;}ApplyMatchAction(local);
 }
 string LanTurnHint(){return !lanReady?"连接已断开":lanWaiting?"同步中…":match.Active==matchViewSeat?"我的回合":"对方回合";}
}
}
