using System;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Diagnostics;
using System.Windows;
using System.Windows.Threading;

namespace Touchfish {
public partial class PanelWindow {
 void PumpLan(Func<bool> condition,string description){var watch=Stopwatch.StartNew();while(!condition()&&watch.ElapsedMilliseconds<8000){var frame=new DispatcherFrame();var timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(10)};timer.Tick+=(s,e)=>{timer.Stop();frame.Continue=false;};timer.Start();Dispatcher.PushFrame(frame);}Check(condition(),description);}
 int FreeLanPort(){var socket=new TcpListener(IPAddress.Loopback,0);socket.Start();int port=((IPEndPoint)socket.LocalEndpoint).Port;socket.Stop();return port;}
 void VerifyLan(string folder){
  int before=checks;LeaveLan();OpenMatch();Check(currentPage=="lan"&&lobbyPanel.Visibility==Visibility.Collapsed,"Normal battle entry only opens LAN");Check(testButton.Width==28&&testButton.FontSize==8,"Local test has small top-bar entry");OpenLocalTest();Check(currentPage=="lobby"&&localTest,"Explicit test entry opens local lobby");OpenMatch();Check(!localTest&&currentPage=="lan","Normal battle exits test mode");ApplyMode(true);ApplyTheme(true,true);Render(Path.Combine(folder,"42-lan-lobby.png"));CheckNormalWeights(lanPanel);ApplyTheme(false,false);ApplyMode(false);Render(Path.Combine(folder,"43-lan-wps-normal.png"));ApplyTheme(true,true);ApplyMode(true);
  Check(LanProtocol.Endpoint("192.168.1.8").Port==42671&&LanProtocol.Endpoint("10.1.2.3:50000").Port==50000,"LAN endpoints and default port");bool rejected=false;try{LanProtocol.Endpoint("8.8.8.8");}catch(InvalidOperationException){rejected=true;}Check(rejected,"Public-address join is rejected");
  using(var stream=new MemoryStream()){LanProtocol.WriteFrame(stream,"中文同步");stream.Position=0;Check(LanProtocol.ReadFrame(stream)=="中文同步","UTF8 frame round trip");}using(var stream=new MemoryStream(BitConverter.GetBytes(IPAddress.HostToNetworkOrder(LanProtocol.MaxFrame+1)))){rejected=false;try{LanProtocol.ReadFrame(stream);}catch(InvalidDataException){rejected=true;}Check(rejected,"Oversized frame rejected before allocation");}
  var guest=new PanelWindow{previewRun=true,ShowInTaskbar=false,Opacity=0};guest.Show();guest.ApplyTheme(true,true);guest.ApplyMode(true);try{
   lanPort.Text=FreeLanPort().ToString();lanClass.SelectedItem=Classes.First(c=>c.Key=="MAGE");lanDeck.SelectedIndex=0;BeginLan(true);Check(lanPeer!=null&&!lanReady,"Host waits asynchronously for guest");Render(Path.Combine(folder,"46-room-address-copy.png"));guest.lanClass.SelectedItem=Classes.First(c=>c.Key=="WARRIOR");guest.lanAddress.Text="127.0.0.1:"+lanPort.Text;guest.BeginLan(false);PumpLan(()=>lanReady&&guest.lanReady,"Real TCP handshake starts both WPF peers");Check(matchViewSeat==0&&guest.matchViewSeat==1&&!awaitHandoff&&!guest.awaitHandoff,"LAN keeps each own seat without hotseat handoff");Check(CanMatchInput()&&guest.CanMatchInput(),"Each LAN player may privately choose their own mulligan");DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>guest.match.Players[0].MulliganDone,"Host mulligan state reaches guest");Check(!CanMatchInput()&&guest.CanMatchInput(),"Host waits after confirming their own mulligan");guest.DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>match.MulliganComplete&&guest.match.MulliganComplete,"Guest mulligan completes game start");Check(!guest.CanMatchInput()&&CanMatchInput(),"Only active side can issue turn actions after mulligan");int emoteRevision=lanRevision;DoMatch("emote",emote:HeroEmotes.Options("MAGE")[3].Value);PumpLan(()=>guest.match.Players[0].EmoteText==HeroEmotes.Options("MAGE")[3].Value,"Host hero emote synchronizes to guest");guest.DoMatch("emote",emote:HeroEmotes.Options("WARRIOR")[1].Value);PumpLan(()=>match.Players[1].EmoteText==HeroEmotes.Options("WARRIOR")[1].Value,"Inactive guest can send and synchronize emote");Check(lanRevision==emoteRevision+2,"Emotes are ordered through authoritative revisions");Check(match.Players[1].HandCount==5&&guest.match.Players[0].HandCount==3&&guest.match.Players[0].Hand.Count==0,"Initial opponent hand counts are public without hand contents");Check(enemyHandStatus.Text.Contains("手牌 5")&&guest.enemyHandStatus.Text.Contains("手牌 3"),"Both perspectives display opponent hand count");OpenLocalTest();Check(!localTest&&lanMode,"Test cannot replace a connected LAN match");
   var authority=lanAuthority.Game;foreach(var p in authority.Players){p.Hand.Clear();p.Board.Clear();p.Mana=p.MaxMana=10;}var a=authority.Summon(0,"VAN_CS2_231");var b=authority.Summon(0,"VAN_CS2_182");b.SummonTurn=0;var third=authority.Summon(0,"VAN_CS2_179");var enemy=authority.Summon(1,"VAN_CS2_179");int fire=Inject(authority,"CS2_029"),cobra=Inject(authority,"EX1_170");int guestBody=Inject(authority,"CS2_182",1),weapon=Inject(authority,"CS2_106",1);PublishLan();RenderMatch();PumpLan(()=>guest.match.Players[1].Hand.Count==2&&guest.match.Players[0].Board.Count==3,"Authoritative fixture reaches guest through TCP");
   var payload=LanProtocol.View(authority,1,lanSession,lanRevision);Check(payload.Players[0].Hand.Length==0&&payload.Players[0].Public.Hand.Count==0&&payload.Players.All(p=>p.Public.Deck.Count==0)&&payload.Players[1].Hand.Length==2,"Guest payload excludes enemy hand and both deck orders");Check(!String.Join("|",payload.Log).Contains("火球术")&&!String.Join("|",payload.Log).Contains("帝王眼镜蛇"),"Shared draw records do not disclose hidden hand names");Check(guest.match.Players[0].Hand.Count==0&&guest.match.Players.All(p=>p.Deck.All(id=>id=="HIDDEN")),"Guest never reconstructs secret card IDs");
   fullEffects=true;guest.fullEffects=true;ApplyMode(false);guest.ApplyMode(false);int guestFloats=((OfficeMatchVisualEffects)guest.matchEffects).FloatCount;int revision=lanRevision;ClickMatchTarget(new MatchTarget(0,b.Id));ClickMatchTarget(new MatchTarget(1,enemy.Id));PumpLan(()=>guest.lanRevision==revision+1,"Host attack synchronized");PumpLan(()=>((OfficeMatchVisualEffects)guest.matchEffects).FloatCount>=guestFloats+2,"Both normal-mode peers present synchronized combat floats");Check(guest.match.Unit(new MatchTarget(0,b.Id)).Health==2&&guest.match.Unit(new MatchTarget(1,enemy.Id)).Health==1,"Combat result identical on guest");
   revision=lanRevision;BeginCard(fire);ClickMatchTarget(new MatchTarget(1));PumpLan(()=>guest.lanRevision==revision+1,"Targeted spell synchronized");Check(guest.match.Players[1].Health==24,"Guest sees authoritative spell damage");Check(guest.enemyHandStatus.Text.Contains("手牌 1")&&guest.match.Players[0].Hand.Count==0,"Opponent playing a card updates count without exposing contents");choosePosition=true;revision=lanRevision;BeginCard(cobra);ClickRelativeSlot(0,b.Id,false);PumpLan(()=>guest.lanRevision==revision+1,"Relative minion placement synchronized");Check(guest.match.Players[0].Board.Select(u=>u.CardId).SequenceEqual(new[]{a.CardId,"VAN_EX1_170",b.CardId,third.CardId}),"Guest board preserves ADBC ordering");
   authority.Players[0].Mana=10;PublishLan();BeginPower();revision=lanRevision;ClickMatchTarget(new MatchTarget(1));PumpLan(()=>guest.lanRevision==revision+1,"Targeted hero power synchronized");Check(guest.match.Players[1].Health==23,"Power damage agrees");revision=lanRevision;DoMatch("end");PumpLan(()=>guest.lanRevision==revision+1&&guest.CanMatchInput(),"End turn transfers control without changing perspectives");Check(!CanMatchInput()&&matchViewSeat==0&&guest.matchViewSeat==1,"Host waits while guest retains own view");
   revision=lanRevision;guest.BeginPower();Check(guest.lanWaiting,"Guest waits for authority reply");PumpLan(()=>lanRevision==revision+1&&!guest.lanWaiting,"Guest hero power confirmed by host");Check(authority.Players[1].Armor==2&&guest.match.Players[1].Armor==2,"Guest power updates authoritative state");revision=lanRevision;guest.BeginCard(guestBody);guest.ClickEmptySlot(1,1);PumpLan(()=>lanRevision==revision+1&&!guest.lanWaiting,"Guest summon request reaches host");Check(authority.Players[1].Board.Count==2&&guest.match.Players[1].Board.Count==2,"Guest summon confirmed on both sides");revision=lanRevision;guest.BeginCard(weapon);PumpLan(()=>lanRevision==revision+1&&!guest.lanWaiting,"Guest weapon request confirmed");Check(authority.Players[1].WeaponAttack==3&&guest.match.Players[1].WeaponDurability==2,"Weapon stats agree");revision=lanRevision;guest.BeginHeroAttack();guest.ClickMatchTarget(new MatchTarget(0,third.Id));PumpLan(()=>lanRevision==revision+1&&!guest.lanWaiting,"Guest target payload serializes and weapon attack resolves");Check(authority.Players[0].Board.Last().Health==2&&authority.Players[1].WeaponDurability==1,"Guest weapon combat state correct");
   authority.Players[1].Mana=10;int battlecry=Inject(authority,"EX1_019",1);PublishLan();PumpLan(()=>guest.match.Players[1].Hand.Any(h=>h.Id==battlecry),"Targeted battlecry reaches own hand");guest.choosePosition=true;revision=lanRevision;guest.BeginCard(battlecry);guest.ClickRelativeSlot(1,authority.Players[1].Board[1].Id,false);Check(guest.pendingPosition==1&&!guest.lanWaiting,"Guest selects insertion position before battlecry target");guest.ClickMatchTarget(new MatchTarget(1,enemy.Id));PumpLan(()=>lanRevision==revision+1&&!guest.lanWaiting,"Guest positioned battlecry confirmed");Check(authority.Players[1].Board[1].CardId=="VAN_EX1_019"&&guest.match.Players[1].Board[1].CardId=="VAN_EX1_019"&&enemy.Health==2,"Battlecry position and buff agree across peers");authority.Players[1].ClassId="MAGE";var networkMalygos=authority.Summon(1,"VAN_EX1_563");int networkFire=Inject(authority,"CS2_029",1);PublishLan();PumpLan(()=>guest.match.Players[1].Hand.Any(h=>h.Id==networkFire),"Malygos state and guest spell arrive over TCP");Check(guest.match.SpellPower(1)==5&&guest.match.Unit(new MatchTarget(1,networkMalygos.Id)).SpellDamage==5,"Malygos +5 survives network snapshot");revision=lanRevision;guest.BeginCard(networkFire);guest.ClickMatchTarget(new MatchTarget(0));PumpLan(()=>lanRevision==revision+1&&!guest.lanWaiting,"Guest Malygos spell confirmed by host");Check(authority.Players[0].Health==19&&guest.match.Players[0].Health==19,"Guest Fireball deals eleven under Malygos on both peers");revision=lanRevision;int mana=authority.Players[1].Mana;guest.lanPeer.Send(new LanMessage{Kind="command",Command=new LanCommand{Kind="end",Revision=revision-1,Session=lanSession,RequestId=900}});PumpLan(()=>guest.status.Text.Contains("状态已更新"),"Stale request receives explicit rejection");Check(lanRevision==revision&&authority.Active==1&&authority.Players[1].Mana==mana,"Stale request is atomic");guest.lanPeer.Send(new LanMessage{Kind="command",Command=new LanCommand{Kind="attack",Revision=revision,Session=lanSession,Source=b.Id,Target=new MatchTarget(0),RequestId=901}});PumpLan(()=>guest.status.Text.Contains("己方随从"),"Forged enemy attacker rejected by server");Check(lanRevision==revision&&authority.Players[1].Mana==mana,"Rejected source cannot alter resources");
   authority.Players[1].ClassId="WARLOCK";authority.Players[1].Hand.Clear();authority.Players[1].Mana=10;int networkDiscard=Inject(authority,"EX1_306",1);Inject(authority,"CS2_182",1);int survivor=Inject(authority,"EX1_009",1);PublishLan();PumpLan(()=>guest.match.Players[1].Hand.Count==3,"Discard fixture reaches guest over TCP");fullEffects=false;guest.fullEffects=false;int hostDiscards=((OfficeMatchVisualEffects)matchEffects).DiscardCount,guestDiscards=((OfficeMatchVisualEffects)guest.matchEffects).DiscardCount;revision=lanRevision;guest.choosePosition=false;guest.BeginCard(networkDiscard);guest.ClickEmptySlot(1,authority.Players[1].Board.Count);PumpLan(()=>lanRevision==revision+1&&!guest.lanWaiting,"Guest discard battlecry is settled by host over TCP");Check(authority.Players[1].Hand.Count==1&&guest.match.Players[1].Hand.Count==1&&guest.match.Players[1].Hand[0].Id==authority.Players[1].Hand[0].Id,"Guest receives authoritative random survivor");PumpLan(()=>((OfficeMatchVisualEffects)matchEffects).DiscardCount==hostDiscards+1&&((OfficeMatchVisualEffects)guest.matchEffects).DiscardCount==guestDiscards+1,"Both peers show discard text with full effects off");PublishLan();PumpLan(()=>guest.match.VisualEvents.Count==authority.VisualEvents.Count,"Repeated discard snapshot received");Check(((OfficeMatchVisualEffects)guest.matchEffects).DiscardCount==guestDiscards+1,"Repeated snapshot never replays discard text");Check(authority.Log.Last().Contains("弃牌：")&&authority.Log.SequenceEqual(guest.match.Log),"Discard public log synchronized across peers");var discardPayload=LanProtocol.View(authority,0,lanSession,lanRevision);Check(discardPayload.Players[1].Hand.Length==0&&discardPayload.Players[1].HandCount==1,"Opponent receives only remaining hand count after discard");Check(enemyHandStatus.Text.Contains("手牌 1"),"Opponent hand count updates after discard");
   Check(authority.Log.SequenceEqual(guest.match.Log),"Both peers share identical ordered public history");ShowPage("log");guest.ShowPage("log");Check(recordRows.Children.Count==guest.recordRows.Children.Count&&recordScope.Text==guest.recordScope.Text,"Both record panes render shared history");Render(Path.Combine(folder,"49-shared-match-records.png"));ShowPage("match");guest.ShowPage("match");InspectMatchCard(match.Card("VAN_CS2_182"));Render(Path.Combine(folder,"50-hand-card-stats.png"));inspectMatch=false;RenderMatch();Render(Path.Combine(folder,"44-lan-host-view.png"));Render(Path.Combine(folder,"51-opponent-hand-count.png"));guest.Opacity=1;guest.Render(Path.Combine(folder,"45-lan-guest-view.png"));guest.Opacity=0;CheckNormalWeights(livePanel);guest.lanPeer.Dispose();PumpLan(()=>!lanReady,"Closing guest socket disables host actions");Check(!CanMatchInput()&&lanMode,"Disconnect freezes match without local fallback");guest.LeaveLan();LeaveLan();
   lanPort.Text=FreeLanPort().ToString();BeginLan(true);guest.lanAddress.Text="127.0.0.1:"+lanPort.Text;guest.BeginLan(false);guest.lanFingerprint="different-version";PumpLan(()=>guest.lanNotice.Text.Contains("版本不同"),"Version mismatch rejected over TCP");Check(!lanReady&&!guest.lanReady,"Mismatch never starts game");guest.LeaveLan();LeaveLan();
   var original=draft;draft=matchRules.TrainingDeck("MAGE");var replace=draft.Cards.First();draft.Cards.Remove(replace.Key);draft.Cards["VAN_EX1_287"]=replace.Value;RefreshLanDecks();lanDeck.SelectedItem=((Choice[])lanDeck.ItemsSource).First(v=>v.Key=="draft");BeginLan(true);Check(lanPeer==null&&lanNotice.Text.Contains("暂不可用"),"Unsupported deck blocked before room opens");draft=original;RefreshLanDecks();lanDeck.SelectedIndex=0;
  }finally{guest.LeaveLan();guest.Close();LeaveLan();}
  localTest=false;choosePosition=false;ApplyMode(true);JsonData.Write(Path.Combine(folder,"lan-verification.json"),new {Assertions=checks-before,Transport="Real TCP sockets on loopback, two WPF peers",OpponentHandCount=true,MalygosSpellPower=5,SharedPublicHistory=true,FixedOwnPerspective=true,EnemyHandHidden=true,DeckOrderHidden=true,RevisionValidation=true,VersionCheck=true,DisconnectStopsActions=true,TwoPhysicalComputersTested=false});
 }
}
}
