using System;
using System.Linq;
using System.IO;
using System.Windows;
using System.Windows.Controls;
namespace Touchfish {
public partial class PanelWindow {
 ComboBox testTakePicker;Button testTakeButton;
 FrameworkElement LiveTestTake(){
  var grid=new Grid();grid.RowDefinitions.Add(new RowDefinition{Height=new GridLength(13)});grid.RowDefinitions.Add(new RowDefinition());grid.Children.Add(T("test · 从剩余牌库取到手牌（最多十张）",9,Muted));
  var row=new Grid();row.ColumnDefinitions.Add(new ColumnDefinition());row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(38)});row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(34)});
  var p=match.Players[matchViewSeat];var choices=p.Deck.GroupBy(id=>id).OrderBy(g=>match.Card(g.Key).Cost).ThenBy(g=>match.Card(g.Key).Name).Select(g=>new Choice(g.Key,match.Card(g.Key).Cost+"费 · "+match.Card(g.Key).Name+" ×"+g.Count())).ToArray();
  testTakePicker=Picker(choices);testTakePicker.Height=21;testTakePicker.SelectedIndex=choices.Length>0?0:-1;row.Children.Add(testTakePicker);
  testTakeButton=Btn("取牌",38);testTakeButton.Height=21;testTakeButton.FontSize=9;testTakeButton.IsEnabled=CanMatchInput()&&choices.Length>0&&p.Hand.Count<10;testTakeButton.Click+=(s,e)=>TakeTestCard();Grid.SetColumn(testTakeButton,1);row.Children.Add(testTakeButton);
  var back=Btn("返回",34);back.Height=21;back.FontSize=9;back.Click+=(s,e)=>{testTakeOpen=false;RenderMatch();};Grid.SetColumn(back,2);row.Children.Add(back);Put(grid,row,1);return grid;
 }
 void TakeTestCard(){if(!localTest||lanMode||match==null||!match.TestMode||!CanMatchInput())return;var choice=testTakePicker.SelectedItem as Choice;if(choice!=null)ApplyMatchAction(match.TestTakeCard(matchViewSeat,choice.Key));}
 void VerifyLocalTestTools(string folder){
  foreach(int total in new[]{0,1,10,29}){var shortDeck=new DeckDocument{ClassId="MAGE",PoolId="classic-2014"};foreach(var pair in matchRules.TrainingDeck("MAGE").Cards){int add=Math.Min(pair.Value,total-shortDeck.Count);if(add>0)shortDeck.Cards[pair.Key]=add;}var shortGame=new MatchEngine(catalog,shortDeck,shortDeck,42,true);Check(shortGame.TestMode&&shortGame.Players.All(player=>player.MaxMana==10),"Local test permits incomplete decks "+total);Reject(()=>new MatchEngine(catalog,shortDeck,shortDeck,42),"Normal match still requires thirty cards");}
  var wrong=new DeckDocument{ClassId="WARRIOR"};wrong.Cards["VAN_CS2_029"]=1;Reject(()=>new MatchEngine(catalog,wrong,wrong,42,true),"Short test deck still rejects foreign profession");var unsupported=new DeckDocument{ClassId="MAGE"};unsupported.Cards["VAN_EX1_287"]=1;bool blocked=false;try{new MatchEngine(catalog,unsupported,unsupported,42,true);}catch(InvalidOperationException){blocked=true;}Check(blocked,"Short test deck still rejects unsupported effects");var tooMany=matchRules.TrainingDeck("MAGE");var extra=catalog.Deckable(catalog.Pool(tooMany.PoolId)).First(card=>card.CardClass=="NEUTRAL"&&!tooMany.Cards.ContainsKey(card.Id)&&card.Rarity!="LEGENDARY"&&matchRules.Supports(card));tooMany.Cards[extra.Id]=1;Reject(()=>new MatchEngine(catalog,tooMany,tooMany,42,true),"Test retains thirty-card maximum");
  var originalDraft=draft;try{draft=new DeckDocument{ClassId="MAGE"};draft.Cards["VAN_CS2_029"]=1;localTest=true;lanMode=false;RefreshLobbyDecks();myDeck.SelectedItem=((Choice[])myDeck.ItemsSource).First(choice=>choice.Key=="draft");opponentDeck.SelectedItem=((Choice[])opponentDeck.ItemsSource).First(choice=>choice.Key=="draft");StartConfiguredMatch();Check(match!=null&&match.TestMode&&match.Players.All(player=>player.ClassId=="MAGE")&&match.Players[0].Hand.Count==1&&match.Players[1].Hand.Count==2,"Test lobby opens one-card draft with bound profession");Render(Path.Combine(folder,"67-short-deck-test.png"));Reject(()=>LobbyDeck(myClass,myDeck),"Complete lobby validation stays default for LAN");}finally{draft=originalDraft;RefreshLobbyDecks();}
  var game=new MatchEngine(catalog,matchRules.TrainingDeck("MAGE"),matchRules.TrainingDeck("WARRIOR"),42,true);Check(game.Players.All(player=>player.MaxMana==10&&player.Mana==10),"Test starts both players at ten full crystals");var p=game.Players[0];string id=p.Deck.Last();var remaining=p.Deck.ToArray();int count=p.Hand.Count;Check(game.TestTakeCard(0,id).Success&&p.Hand.Count==count+1&&p.Hand.Last().CardId==id&&p.Deck.Count==remaining.Length-1,"Test selects requested remaining card");var expected=remaining.ToList();expected.Remove(id);Check(p.Deck.SequenceEqual(expected),"Test take preserves remaining deck order");Check(!game.TestTakeCard(1,game.Players[1].Deck[0]).Success,"Test take requires active seat");Check(!game.TestTakeCard(0,"GAME_COIN").Success,"Test cannot take absent card");while(p.Hand.Count<10)game.TestTakeCard(0,p.Deck[0]);int size=p.Deck.Count;Check(!game.TestTakeCard(0,p.Deck[0]).Success&&p.Deck.Count==size&&p.Hand.Count==10,"Full test hand rejects without consuming card");game.EndTurn();Check(game.Players[1].Mana==10,"Test next player retains ten crystals");var regular=new MatchEngine(catalog,matchRules.TrainingDeck("MAGE"),matchRules.TrainingDeck("WARRIOR"),42);size=regular.Players[0].Deck.Count;Check(!regular.TestTakeCard(0,regular.Players[0].Deck[0]).Success&&regular.Players[0].Deck.Count==size&&regular.Players[0].Mana==1,"Normal match rejects test operations and keeps normal mana");
  match=game;matchViewSeat=game.Active;awaitHandoff=false;localTest=true;lanMode=false;ClearPending();inspectMatch=false;testTakeOpen=true;ApplyMode(true);RenderMatch();ShowPage("match");Render(Path.Combine(folder,"55-test-take-minimal.png"));Check(testTakePicker.Items.Count>0&&testTakeButton.IsEnabled&&Width==392&&Height==300,"Test picker fits minimal window");id=((Choice)testTakePicker.SelectedItem).Key;TakeTestCard();Check(match.Players[matchViewSeat].Hand.Last().CardId==id&&!testTakeOpen,"Test UI takes selection and returns to hand");ApplyMode(false);testTakeOpen=true;RenderMatch();Render(Path.Combine(folder,"56-test-take-normal.png"));CheckNormalWeights(livePanel);testTakeOpen=false;localTest=false;
 }
}
}
