using System;
using System.Linq;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Touchfish {
public sealed class MatchRules {
 readonly Dictionary<string,CardEffect> effects=new Dictionary<string,CardEffect>();readonly CardCatalog catalog;
 public IEnumerable<string> RegisteredIds{get{return effects.Keys;}}
 static readonly string[] SimpleMechanics={"TAUNT","CHARGE","DIVINE_SHIELD","WINDFURY","POISONOUS","STEALTH","SPELLPOWER","CANT_ATTACK","CANT_BE_TARGETED_BY_ABILITIES","ELUSIVE","OVERLOAD"};
 public MatchRules(CardCatalog source){catalog=source;
  Register("GAME_COIN","NONE",c=>c.Game.Players[c.Seat].Mana=Math.Min(10,c.Game.Players[c.Seat].Mana+1));
  Damage("CS2_029",6);Damage("CS1_130",2);Damage("CS2_008",1);Damage("DS1_185",2);Damage("EX1_238",3);Damage("EX1_241",5);Damage("EX1_279",10);Damage("CS2_057",4,"MINION");Damage("CS2_072",2,"UNDAMAGED_MINION");
  Register("CS2_024","ANY_CHARACTER",c=>{Hit(c,3);c.Game.Freeze(c.Target);});Register("CS2_037","ENEMY_CHARACTER",c=>{Hit(c,1);c.Game.Freeze(c.Target);});Register("CS2_031","ANY_CHARACTER",c=>{var unit=c.Game.Unit(c.Target);bool frozen=c.Target.Hero?c.Game.Players[c.Target.Seat].Frozen:unit.Frozen;if(frozen)Hit(c,4);else c.Game.Freeze(c.Target);});
  Register("CS2_022","MINION",c=>c.Game.Transform(c.Target,"VAN_CS2_tk1"));
  Register("CS2_023","NONE",c=>c.Game.Draw(c.Seat,2));Register("CS2_077","NONE",c=>c.Game.Draw(c.Seat,4));
  Register("CS2_025","NONE",c=>Area(c,1-c.Seat,1,false));Register("CS2_032","NONE",c=>Area(c,1-c.Seat,4,false));Register("CS2_028","NONE",c=>{Area(c,1-c.Seat,2,false);foreach(var target in c.Game.Characters(1-c.Seat,false))c.Game.Freeze(target);});Register("CS2_026","NONE",c=>{foreach(var target in c.Game.Characters(1-c.Seat,false))c.Game.Freeze(target);});
  Register("CS2_027","NONE",c=>{c.Game.Summon(c.Seat,"VAN_CS2_mirror");c.Game.Summon(c.Seat,"VAN_CS2_mirror");},(g,s)=>g.Players[s].Board.Count>=7?"战场已满。":null);
  Register("EX1_277","NONE",c=>Missiles(c,3));Register("EX1_384","NONE",c=>Missiles(c,8));
  Register("CS2_007","ANY_CHARACTER",c=>c.Game.Heal(c.Target,8));Register("CS2_089","ANY_CHARACTER",c=>c.Game.Heal(c.Target,6));Register("EX1_354","ANY_CHARACTER",c=>{c.Game.Heal(c.Target,8);c.Game.Draw(c.Seat,3);});
  Register("CS2_005","NONE",c=>{c.Game.Players[c.Seat].Armor+=2;c.Game.Players[c.Seat].TempAttack+=2;});Register("EX1_570","NONE",c=>{c.Game.Players[c.Seat].Armor+=4;c.Game.Players[c.Seat].TempAttack+=4;});Register("EX1_169","NONE",c=>c.Game.Players[c.Seat].Mana=Math.Min(10,c.Game.Players[c.Seat].Mana+2));
  Register("CS2_009","MINION",c=>{c.Game.Buff(c.Target,2,2);c.Game.Unit(c.Target).Taunt=true;});Register("CS2_011","NONE",c=>{c.Game.Players[c.Seat].TempAttack+=2;foreach(var unit in c.Game.Players[c.Seat].Board)unit.TempAttack+=2;});
  Register("CS2_012","ENEMY_CHARACTER",c=>{Hit(c,4);foreach(var target in c.Game.Characters(1-c.Seat))if(target.UnitId!=c.Target.UnitId)c.Game.Damage(target,1+c.Game.SpellPower(c.Seat));});
  Register("EX1_173","ANY_CHARACTER",c=>{Hit(c,5);c.Game.Draw(c.Seat,1);});Register("EX1_161","MINION",c=>{Kill(c);c.Game.Draw(1-c.Seat,2);});
  Register("CS2_039","MINION",c=>c.Game.Unit(c.Target).Windfury=true);Register("CS2_041","MINION",c=>{c.Game.Heal(c.Target,1000);c.Game.Unit(c.Target).Taunt=true;});Register("CS2_045","FRIENDLY_CHARACTER",c=>{if(c.Target.Hero)c.Game.Players[c.Seat].TempAttack+=3;else c.Game.Unit(c.Target).TempAttack+=3;});Register("CS2_046","NONE",c=>{foreach(var unit in c.Game.Players[c.Seat].Board)unit.TempAttack+=3;});
  Register("EX1_245","MINION",c=>{c.Game.Silence(c.Target);Hit(c,1);});Register("EX1_248","NONE",c=>{c.Game.Summon(c.Seat,"VAN_EX1_tk11");c.Game.Summon(c.Seat,"VAN_EX1_tk11");},(g,s)=>g.Players[s].Board.Count>=7?"战场已满。":null);
  Register("EX1_259","NONE",c=>{foreach(var target in c.Game.Characters(1-c.Seat,false)){var roll=c.Game.RandomTarget(new[]{new MatchTarget(0),new MatchTarget(1)});c.Game.Damage(target,2+roll.Seat+c.Game.SpellPower(c.Seat));}});
  Register("CS2_061","ANY_CHARACTER",c=>{Hit(c,2);c.Game.Heal(new MatchTarget(c.Seat),2);});Register("CS2_062","NONE",c=>{Area(c,0,3,true);Area(c,1,3,true);});Register("EX1_308","ANY_CHARACTER",c=>{Hit(c,4);c.Game.DiscardRandom(c.Seat,1);});
  Register("EX1_306","NONE",c=>c.Game.DiscardRandom(c.Seat,1));Register("EX1_310","NONE",c=>c.Game.DiscardRandom(c.Seat,2));Register("NEW1_030","NONE",c=>c.Game.DeathwingBattlecry(c.Seat,c.Summoned));
  Register("EX1_302","MINION",c=>{Hit(c,1);if(c.Game.Unit(c.Target).Health<=0)c.Game.Draw(c.Seat,1);});Register("EX1_309","MINION",c=>{Kill(c);c.Game.Heal(new MatchTarget(c.Seat),3);});Register("EX1_312","NONE",c=>{foreach(var target in c.Game.Characters(0,false).Concat(c.Game.Characters(1,false)))c.Game.Unit(target).DamageTaken=c.Game.Unit(target).MaxHealth;});
  Register("CS2_073","MINION",c=>c.Game.Buff(c.Target,c.Combo?4:2,0));Register("EX1_124","ANY_CHARACTER",c=>Hit(c,c.Combo?4:2));Register("CS2_075","NONE",c=>c.Game.Damage(new MatchTarget(1-c.Seat),3+c.Game.SpellPower(c.Seat)));Register("CS2_076","ENEMY_MINION",Kill);Register("EX1_581","ENEMY_MINION",c=>c.Game.ReturnToHand(c.Target));
  Register("CS2_074","NONE",c=>c.Game.Players[c.Seat].WeaponAttack+=2,(g,s)=>g.Players[s].WeaponDurability==0?"需要先装备武器。":null);Register("EX1_278","ANY_CHARACTER",c=>{Hit(c,1);c.Game.Draw(c.Seat,1);});Register("EX1_129","NONE",c=>{Area(c,1-c.Seat,1,false);c.Game.Draw(c.Seat,1);});
  Register("CS2_084","MINION",c=>c.Game.SetHealth(c.Target,1));Register("EX1_539","ANY_CHARACTER",c=>Hit(c,c.Game.Players[c.Seat].Board.Any(m=>m.Race=="BEAST")?5:3));Register("EX1_617","NONE",c=>{var target=c.Game.RandomTarget(c.Game.Characters(1-c.Seat,false));if(target!=null)c.Game.Unit(target).DamageTaken=c.Game.Unit(target).MaxHealth;},(g,s)=>g.Players[1-s].Board.Count==0?"对方没有随从。":null);
  Register("NEW1_031","NONE",c=>{var token=c.Game.RandomTarget(new[]{new MatchTarget(0),new MatchTarget(1),new MatchTarget(2)});c.Game.Summon(c.Seat,new[]{"VAN_NEW1_032","VAN_NEW1_033","VAN_NEW1_034"}[token.Seat]);},(g,s)=>g.Players[s].Board.Count>=7?"战场已满。":null);
  Register("CS2_087","MINION",c=>c.Game.Buff(c.Target,3,0));Register("CS2_092","MINION",c=>c.Game.Buff(c.Target,4,4));Register("EX1_371","MINION",c=>c.Game.Unit(c.Target).Shield=true);Register("CS2_093","NONE",c=>Area(c,1-c.Seat,2,true));Register("CS2_094","ANY_CHARACTER",c=>{Hit(c,3);c.Game.Draw(c.Seat,1);});Register("EX1_619","NONE",c=>{foreach(var target in c.Game.Characters(0,false).Concat(c.Game.Characters(1,false)))c.Game.SetHealth(target,1);});Register("EX1_360","MINION",c=>{var unit=c.Game.Unit(c.Target);unit.BuffAttack=1-unit.BaseAttack;});Register("EX1_355","MINION",c=>{var unit=c.Game.Unit(c.Target);unit.BuffAttack+=c.Game.AttackValue(unit);});
  Register("DS1_233","NONE",c=>c.Game.Damage(new MatchTarget(1-c.Seat),5+c.Game.SpellPower(c.Seat)));Register("CS2_004","MINION",c=>{c.Game.Buff(c.Target,0,2);c.Game.Draw(c.Seat,1);});Register("CS2_234","LOW_ATTACK",Kill);Register("EX1_622","HIGH_ATTACK",Kill);Register("CS2_236","MINION",c=>c.Game.Buff(c.Target,0,c.Game.Unit(c.Target).Health));Register("CS1_129","MINION",c=>{var unit=c.Game.Unit(c.Target);unit.BuffAttack=unit.Health-unit.BaseAttack;});Register("EX1_332","MINION",c=>c.Game.Silence(c.Target));
  Register("CS1_112","NONE",c=>{Area(c,1-c.Seat,2,true);foreach(var target in c.Game.Characters(c.Seat))c.Game.Heal(target,2);});Register("EX1_621","NONE",c=>{foreach(var target in c.Game.Characters(0,false).Concat(c.Game.Characters(1,false)))c.Game.Heal(target,4);});Register("EX1_624","ANY_CHARACTER",c=>{Hit(c,5);c.Game.Heal(new MatchTarget(c.Seat),5);});Register("EX1_626","NONE",c=>{foreach(var target in c.Game.Characters(1-c.Seat,false))c.Game.Silence(target);c.Game.Draw(c.Seat,1);});
  Register("CS2_105","NONE",c=>c.Game.Players[c.Seat].TempAttack+=4);Register("EX1_606","NONE",c=>{c.Game.Players[c.Seat].Armor+=5;c.Game.Draw(c.Seat,1);});Register("EX1_400","NONE",c=>{Area(c,0,1,false);Area(c,1,1,false);});Register("CS2_108","ENEMY_DAMAGED_MINION",Kill,(g,s)=>null);
  Register("EX1_391","MINION",c=>{Hit(c,2);if(c.Game.Unit(c.Target).Health>0)c.Game.Draw(c.Seat,1);});Register("EX1_408","ANY_CHARACTER",c=>Hit(c,c.Game.Players[c.Seat].Health<=12?6:4));Register("EX1_410","MINION",c=>Hit(c,c.Game.Players[c.Seat].Armor));Register("EX1_607","MINION",c=>{Hit(c,1);c.Game.Buff(c.Target,2,0);});Register("CS2_103","FRIENDLY_MINION",c=>{c.Game.Buff(c.Target,2,0);c.Game.Unit(c.Target).Charge=true;});
  // Battlecries are explicit and do not inherit spell damage bonuses.
  Register("EX1_506","NONE",c=>c.Game.Summon(c.Seat,"VAN_EX1_506a",c.Game.Players[c.Seat].Board.IndexOf(c.Summoned)+1));
  Register("CS2_196","NONE",c=>c.Game.Summon(c.Seat,"VAN_CS2_boar",c.Game.Players[c.Seat].Board.IndexOf(c.Summoned)+1));
  Register("CS2_151","NONE",c=>c.Game.Summon(c.Seat,"VAN_CS2_152",c.Game.Players[c.Seat].Board.IndexOf(c.Summoned)+1));
  Register("EX1_066","NONE",c=>c.Game.BreakWeapon(1-c.Seat));Register("EX1_015","NONE",c=>c.Game.Draw(c.Seat,1));Register("CS2_147","NONE",c=>c.Game.Draw(c.Seat,1));Register("EX1_284","NONE",c=>c.Game.Draw(c.Seat,1));
  Register("CS2_189","ANY_CHARACTER",c=>c.Game.Damage(c.Target,1));Register("CS2_141","ANY_CHARACTER",c=>c.Game.Damage(c.Target,1));Register("CS2_150","ANY_CHARACTER",c=>c.Game.Damage(c.Target,2));Register("EX1_011","ANY_CHARACTER",c=>c.Game.Heal(c.Target,2));Register("CS2_117","ANY_CHARACTER",c=>c.Game.Heal(c.Target,3));
  Register("EX1_019","FRIENDLY_MINION",c=>c.Game.Buff(c.Target,1,1));Register("CS2_203","MINION",c=>c.Game.Silence(c.Target));Register("EX1_048","MINION",c=>c.Game.Silence(c.Target));Register("EX1_093","NONE",c=>Adjacent(c,1,1,true));Register("EX1_058","NONE",c=>Adjacent(c,0,0,true));
  Register("EX1_046","MINION",c=>c.Game.Unit(c.Target).TempAttack+=2);Register("CS2_188","MINION",c=>c.Game.Unit(c.Target).TempAttack+=2);Register("EX1_603","MINION",c=>{c.Game.Damage(c.Target,1);c.Game.Buff(c.Target,2,0);});Register("EX1_319","NONE",c=>c.Game.Damage(new MatchTarget(c.Seat),3));
  Register("DS1_055","NONE",c=>{foreach(var target in c.Game.Characters(c.Seat))c.Game.Heal(target,2);});Register("EX1_583","NONE",c=>c.Game.Heal(new MatchTarget(c.Seat),4));Register("EX1_593","NONE",c=>c.Game.Damage(new MatchTarget(1-c.Seat),3));
  foreach(string id in new[]{"EX1_170","EX1_556","EX1_096","EX1_029","EX1_012","CS2_033","EX1_162","CS2_122","DS1_175"})Register(id,"NONE",c=>{});
  foreach(string id in EnrageRules.Ids)Register(id,"NONE",c=>{});
  // Truesilver Champion's heal and Doomhammer's windfury are implemented by the engine.
  Register("CS2_097","NONE",c=>{});
 }
 void Register(string id,string target,Action<EffectContext> action,Func<MatchEngine,int,string> requirement=null){effects[id]=new CardEffect{Target=target,Apply=action,Requirement=requirement};}
 void Damage(string id,int amount,string target="ANY_CHARACTER"){Register(id,target,c=>Hit(c,amount));}
 static void Hit(EffectContext context,int amount){context.Game.Damage(context.Target,amount+context.Game.SpellPower(context.Seat));}
 static void Kill(EffectContext context){var unit=context.Game.Unit(context.Target);unit.DamageTaken=unit.MaxHealth;}
 static void Area(EffectContext context,int seat,int amount,bool hero){foreach(var target in context.Game.Characters(seat,hero))context.Game.Damage(target,amount+context.Game.SpellPower(context.Seat));}
 static void Missiles(EffectContext context,int amount){for(int n=0;n<amount+context.Game.SpellPower(context.Seat);n++){var target=context.Game.RandomTarget(context.Game.Characters(1-context.Seat).Where(t=>t.Hero||context.Game.Unit(t).Health>0));if(target!=null)context.Game.Damage(target,1);}}
 static void Adjacent(EffectContext context,int attack,int health,bool taunt){var board=context.Game.Players[context.Seat].Board;int index=board.IndexOf(context.Summoned);foreach(int place in new[]{index-1,index+1})if(place>=0&&place<board.Count){context.Game.Buff(new MatchTarget(context.Seat,board[place].Id),attack,health);if(taunt)board[place].Taunt=true;}}
 public bool Supports(CardRecord card){if(card.Id=="GAME_COIN")return true;if(effects.ContainsKey(card.BaseId))return true;if(card.Type!="MINION"&&card.Type!="WEAPON")return false;if(card.Mechanics!=null&&card.Mechanics.Any(m=>!SimpleMechanics.Contains(m)))return false;string text=Regex.Replace(card.Text??"",@"法术伤害\+\d+|过载[：:]?\s*[（(]\d+[）)]|嘲讽|冲锋|圣盾|风怒|剧毒|潜行|无法攻击|不能攻击|扰魔|无法成为法术或英雄技能的目标","");return Regex.Replace(text,@"[\s，。；,:;.（）()]+","").Length==0;}
 public CardEffect Effect(CardRecord card){CardEffect effect;if(effects.TryGetValue(card.BaseId,out effect))return effect;return new CardEffect{Apply=c=>{}};}
 public void Death(MatchEngine game,BattleUnit unit){string id=game.Card(unit.CardId).BaseId;if(id=="EX1_556"){int position=game.Players[unit.Owner].Board.FindIndex(m=>m.Id==unit.DeathAnchor);game.Summon(unit.Owner,"VAN_skele21",position);}if(id=="EX1_096"||id=="EX1_012")game.Draw(unit.Owner,1);if(id=="EX1_029")game.Damage(new MatchTarget(1-unit.Owner),2);}
 public DeckDocument TrainingDeck(string classId){var pool=catalog.Pool("classic-2014");var deck=new DeckDocument{ClassId=classId,PoolId=pool.Id,Name="基础练习 · "+classId};var all=catalog.Deckable(pool);var selected=all.Where(c=>c.CardClass==classId&&c.Rarity!="LEGENDARY"&&Supports(c)).Take(8).Concat(all.Where(c=>c.CardClass=="NEUTRAL"&&c.Rarity!="LEGENDARY"&&c.Cost>=1&&c.Cost<=5&&Supports(c))).Take(15);foreach(var card in selected)deck.Cards[card.Id]=2;DeckRules.Validate(catalog,deck,true);return deck;}
}
}
