using System;
using System.Linq;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Imaging;

namespace Touchfish {
public sealed class MatchVisualAnchor {public Rect Bounds;public FrameworkElement Element;public BitmapSource Snapshot;}
public interface IMatchVisualEffects {
 void Spell(MatchVisualEvent item);
 void SpellCard(MatchVisualEvent item);
 void Discard(MatchVisualEvent item);
 void Emote(MatchVisualEvent item,MatchVisualAnchor anchor);
 void Entrance(MatchVisualEvent item);
 void MinionSpeech(MatchVisualEvent item,MatchVisualAnchor anchor);
 void Damage(MatchVisualEvent item,MatchVisualAnchor anchor,TimeSpan delay);
 void Clear();
}
// Office-style first renderer. Future renderers use the same public event interface.
public sealed partial class OfficeMatchVisualEffects : IMatchVisualEffects {
 readonly Canvas overlay;readonly FrameworkElement screen;readonly Brush ink,surface;readonly Func<bool> enabled,extraEffects;
 readonly HashSet<int> discardSlots=new HashSet<int>();int discardGeneration;
 public const int DiscardDurationMs=2500;public int DiscardCount;
 public int SpellCount,FloatCount,CardShakeCount,ScreenShakeCount,EmoteCount,EntranceCount;
 public const int EntranceDurationMs=2000,EmoteDurationMs=3000,EmoteFadeDelayMs=2000,EmoteFadeDurationMs=500;
 DateTime cinematicUntil=DateTime.MinValue;
 public OfficeMatchVisualEffects(Canvas canvas,FrameworkElement wholeScreen,Brush foreground,Brush background,Func<bool> canPlay,Func<bool> canPlayExtras){overlay=canvas;screen=wholeScreen;ink=foreground;surface=background;enabled=canPlay;extraEffects=canPlayExtras;}
 static void Fade(FrameworkElement element,int duration,int delay,Action remove){var animation=new DoubleAnimationUsingKeyFrames{Duration=TimeSpan.FromMilliseconds(duration),BeginTime=TimeSpan.FromMilliseconds(delay)};animation.KeyFrames.Add(new DiscreteDoubleKeyFrame(1,KeyTime.FromPercent(0)));animation.KeyFrames.Add(new LinearDoubleKeyFrame(1,KeyTime.FromPercent(.55)));animation.KeyFrames.Add(new LinearDoubleKeyFrame(0,KeyTime.FromPercent(1)));animation.Completed+=(s,e)=>remove();element.BeginAnimation(UIElement.OpacityProperty,animation);}
 static void Shake(FrameworkElement element,double amplitude,int delay){var move=new TranslateTransform();element.RenderTransform=move;var animation=new DoubleAnimationUsingKeyFrames{Duration=TimeSpan.FromMilliseconds(220),BeginTime=TimeSpan.FromMilliseconds(delay),FillBehavior=FillBehavior.Stop};double[] values={0,-amplitude,amplitude,-amplitude*.7,amplitude*.5,0};for(int n=0;n<values.Length;n++)animation.KeyFrames.Add(new LinearDoubleKeyFrame(values[n],KeyTime.FromPercent((double)n/(values.Length-1))));move.BeginAnimation(TranslateTransform.XProperty,animation);}
 public void Spell(MatchVisualEvent item){if(!enabled())return;SpellCount++;var text=new TextBlock{Text="玩家 "+(item.Seat+1)+" 使用了 "+item.CardName,FontSize=10,FontWeight=FontWeights.Normal,Foreground=ink,TextAlignment=TextAlignment.Center,TextTrimming=TextTrimming.CharacterEllipsis};var line=new Border{Child=text,Background=surface,Padding=new Thickness(5,2,5,2),MaxWidth=Math.Max(80,overlay.ActualWidth-24)};overlay.Children.Add(line);line.Measure(new Size(overlay.ActualWidth-24,30));Canvas.SetLeft(line,Math.Max(4,(overlay.ActualWidth-line.DesiredSize.Width)/2));Canvas.SetTop(line,Math.Max(22,overlay.ActualHeight/2-10));Fade(line,1000,0,()=>overlay.Children.Remove(line));}
 public void Discard(MatchVisualEvent item){if(!enabled())return;DiscardCount++;int generation=discardGeneration;int slot=0;while(discardSlots.Contains(slot))slot++;discardSlots.Add(slot);var text=new TextBlock{Text="玩家 "+(item.Seat+1)+" 弃掉了 "+item.CardName,FontSize=10,FontWeight=FontWeights.Normal,Foreground=ink,TextAlignment=TextAlignment.Center,TextTrimming=TextTrimming.CharacterEllipsis};var line=new Border{Child=text,Background=surface,Padding=new Thickness(5,1,5,1),MaxWidth=Math.Max(80,overlay.ActualWidth-24),ToolTip=text.Text};overlay.Children.Add(line);line.Measure(new Size(overlay.ActualWidth-24,30));Canvas.SetLeft(line,Math.Max(4,(overlay.ActualWidth-line.DesiredSize.Width)/2));Canvas.SetTop(line,Math.Max(24,overlay.ActualHeight-78-slot*17));var rise=new TranslateTransform();line.RenderTransform=rise;rise.BeginAnimation(TranslateTransform.YProperty,new DoubleAnimation(0,-8,TimeSpan.FromMilliseconds(DiscardDurationMs)));Fade(line,DiscardDurationMs,0,()=>{overlay.Children.Remove(line);if(generation==discardGeneration)discardSlots.Remove(slot);});}
 public void Emote(MatchVisualEvent item,MatchVisualAnchor anchor){if(!enabled()||anchor==null)return;EmoteCount++;var text=new TextBlock{Text=item.UnitId>0?item.CardName:"玩家 "+(item.Seat+1)+"："+item.CardName,FontSize=11,FontWeight=FontWeights.Normal,Foreground=ink,TextWrapping=TextWrapping.Wrap};var bubble=new Border{Child=text,Background=surface,BorderBrush=ink,BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(4),Padding=new Thickness(8,4,8,4),MaxWidth=Math.Max(80,Math.Min(280,overlay.ActualWidth-24))};overlay.Children.Add(bubble);bubble.Measure(new Size(bubble.MaxWidth,70));double x=Math.Max(4,Math.Min(overlay.ActualWidth-bubble.DesiredSize.Width-4,anchor.Bounds.X+anchor.Bounds.Width/2-bubble.DesiredSize.Width/2));bool above=anchor.Bounds.Y>overlay.ActualHeight/2;double y=above?anchor.Bounds.Y-bubble.DesiredSize.Height-6:anchor.Bounds.Bottom+6;Canvas.SetLeft(bubble,x);Canvas.SetTop(bubble,Math.Max(4,y));var tail=new System.Windows.Shapes.Polygon{Fill=surface,Stroke=ink,StrokeThickness=1,Points=above?new PointCollection{new Point(0,0),new Point(8,0),new Point(4,5)}:new PointCollection{new Point(0,5),new Point(8,5),new Point(4,0)}};overlay.Children.Add(tail);Canvas.SetLeft(tail,anchor.Bounds.X+anchor.Bounds.Width/2-4);Canvas.SetTop(tail,above?y+bubble.DesiredSize.Height-1:y-4);Fade(bubble,EmoteFadeDurationMs,EmoteFadeDelayMs,()=>overlay.Children.Remove(bubble));Fade(tail,EmoteFadeDurationMs,EmoteFadeDelayMs,()=>overlay.Children.Remove(tail));}
 public void Entrance(MatchVisualEvent item){if(!enabled()||!extraEffects()||item.CardName!="NEW1_030")return;EntranceCount++;ScreenShakeCount++;cinematicUntil=DateTime.UtcNow.AddMilliseconds(EntranceDurationMs);var move=new TranslateTransform();screen.RenderTransform=move;var shake=new DoubleAnimationUsingKeyFrames{Duration=TimeSpan.FromMilliseconds(EntranceDurationMs),FillBehavior=FillBehavior.Stop};for(int i=0;i<=40;i++)shake.KeyFrames.Add(new LinearDoubleKeyFrame(i==0||i==40?0:(i%2==0?3:-3),KeyTime.FromPercent(i/40.0)));move.BeginAnimation(TranslateTransform.XProperty,shake);double width=Math.Max(80,overlay.ActualWidth),height=Math.Max(80,overlay.ActualHeight);for(int i=0;i<44;i++){var fire=new TextBlock{Text="火",FontSize=12+i%4*2,FontWeight=FontWeights.Normal,Foreground=new SolidColorBrush(Color.FromRgb(190,65,58)),Opacity=0};overlay.Children.Add(fire);double x=8+(i*73%((int)width-24)),y=35+(i*47%Math.Max(1,(int)height-105));Canvas.SetLeft(fire,x);Canvas.SetTop(fire,y);var rise=new TranslateTransform();fire.RenderTransform=rise;rise.BeginAnimation(TranslateTransform.YProperty,new DoubleAnimation(22,-45,TimeSpan.FromMilliseconds(EntranceDurationMs)));Fade(fire,EntranceDurationMs,0,()=>overlay.Children.Remove(fire));}}
 public void MinionSpeech(MatchVisualEvent item,MatchVisualAnchor anchor){if(!enabled()||!extraEffects()||anchor==null)return;Emote(item,anchor);if(item.Kind=="fishing"&&extraEffects()&&anchor.Element!=null){CardShakeCount++;Shake(anchor.Element,2,0);}}
 public void Damage(MatchVisualEvent item,MatchVisualAnchor anchor,TimeSpan delay){if(!enabled()||item.Amount<=0||anchor==null)return;FloatCount++;int start=(int)delay.TotalMilliseconds;FrameworkElement target=anchor.Element;if(target==null&&anchor.Snapshot!=null){var ghost=new Image{Source=anchor.Snapshot,Width=anchor.Bounds.Width,Height=anchor.Bounds.Height};Canvas.SetLeft(ghost,anchor.Bounds.X);Canvas.SetTop(ghost,anchor.Bounds.Y);overlay.Children.Add(ghost);Fade(ghost,450,start,()=>overlay.Children.Remove(ghost));target=ghost;}
  var number=new TextBlock{Text="−"+item.Amount,FontSize=12,FontWeight=FontWeights.Normal,Foreground=ink,Background=surface,Padding=new Thickness(3,1,3,1),Opacity=0};overlay.Children.Add(number);double x=anchor.Bounds.X+anchor.Bounds.Width/2-12,y=anchor.Bounds.Y+Math.Max(2,anchor.Bounds.Height/3);Canvas.SetLeft(number,Math.Max(0,Math.Min(overlay.ActualWidth-34,x)));Canvas.SetTop(number,Math.Max(0,y));var lift=new TranslateTransform();number.RenderTransform=lift;number.BeginAnimation(UIElement.OpacityProperty,null);lift.BeginAnimation(TranslateTransform.YProperty,new DoubleAnimation(0,-23,TimeSpan.FromMilliseconds(1000)){BeginTime=delay,FillBehavior=FillBehavior.Stop});Fade(number,1000,start,()=>overlay.Children.Remove(number));if(extraEffects()&&item.Amount>3&&target!=null){CardShakeCount++;Shake(target,2,start);}if(extraEffects()&&item.Amount>10){ScreenShakeCount++;if(DateTime.UtcNow>=cinematicUntil)Shake(screen,3,start);}}
 public void Clear(){ClearSpellCards();discardGeneration++;discardSlots.Clear();overlay.Children.Clear();screen.RenderTransform=Transform.Identity;cinematicUntil=DateTime.MinValue;}
}
public partial class PanelWindow {
 Canvas matchEffectsCanvas;IMatchVisualEffects matchEffects;readonly MatchVisualCursor visualCursor=new MatchVisualCursor();
 readonly Dictionary<string,FrameworkElement> visualTargets=new Dictionary<string,FrameworkElement>();readonly Dictionary<string,MatchVisualAnchor> previousVisualTargets=new Dictionary<string,MatchVisualAnchor>();
 string visualAnchorSession;
 string VisualKey(int seat,int id){return seat+":"+id;}
 void BuildMatchEffects(){matchEffectsCanvas=new Canvas{IsHitTestVisible=false,ClipToBounds=true,Visibility=Visibility.Collapsed};Put(shell,matchEffectsCanvas,4);Panel.SetZIndex(matchEffectsCanvas,30);matchEffects=new OfficeMatchVisualEffects(matchEffectsCanvas,shell,Ink,B("#F7F8FA"),()=>!minimal&&currentPage=="match"&&!awaitHandoff,()=>fullEffects&&!minimal);}
 void CaptureMatchVisuals(){if(!minimal&&currentPage=="match")livePanel.UpdateLayout();previousVisualTargets.Clear();if(!minimal&&visualAnchorSession==match.VisualSession)foreach(var pair in visualTargets){var element=pair.Value;if(element.ActualWidth<1||element.ActualHeight<1)continue;var rect=element.TransformToVisual(matchEffectsCanvas).TransformBounds(new Rect(0,0,element.ActualWidth,element.ActualHeight));var bitmap=new RenderTargetBitmap(Math.Max(1,(int)Math.Ceiling(element.ActualWidth)),Math.Max(1,(int)Math.Ceiling(element.ActualHeight)),96,96,PixelFormats.Pbgra32);bitmap.Render(element);previousVisualTargets[pair.Key]=new MatchVisualAnchor{Bounds=rect,Snapshot=bitmap};}visualTargets.Clear();visualAnchorSession=match.VisualSession;}
 void RegisterVisualTarget(int seat,int id,FrameworkElement target){visualTargets[VisualKey(seat,id)]=target;}
 void SyncMatchEffectsVisibility(){if(matchEffectsCanvas==null)return;bool show=currentPage=="match"&&!minimal&&!awaitHandoff;matchEffectsCanvas.Visibility=show?Visibility.Visible:Visibility.Collapsed;if(!show)matchEffects.Clear();}
 void PresentMatchVisuals(){var events=visualCursor.Take(match.VisualSession,match.VisualEvents,!minimal&&currentPage=="match"&&!awaitHandoff);SyncMatchEffectsVisibility();if(events.Length==0)return;var old=new Dictionary<string,MatchVisualAnchor>(previousVisualTargets);string session=match.VisualSession;bool playExtras=fullEffects&&!minimal;Dispatcher.BeginInvoke(new Action(()=>{if(match==null||match.VisualSession!=session||minimal||currentPage!="match")return;UpdateLayout();var delays=new Dictionary<string,int>();foreach(var item in events){if(item.Kind=="minion-speech"||item.Kind=="fishing"){if(!playExtras)continue;string speechKey=VisualKey(item.Seat,item.UnitId);FrameworkElement speaker;MatchVisualAnchor speechAnchor;old.TryGetValue(speechKey,out speechAnchor);if(visualTargets.TryGetValue(speechKey,out speaker))speechAnchor=new MatchVisualAnchor{Element=speaker,Bounds=speaker.TransformToVisual(matchEffectsCanvas).TransformBounds(new Rect(0,0,speaker.ActualWidth,speaker.ActualHeight))};matchEffects.MinionSpeech(item,speechAnchor);continue;}if(item.Kind=="entrance"){matchEffects.Entrance(item);continue;}if(item.Kind=="emote"){FrameworkElement hero;if(visualTargets.TryGetValue(VisualKey(item.Seat,0),out hero))matchEffects.Emote(item,new MatchVisualAnchor{Element=hero,Bounds=hero.TransformToVisual(matchEffectsCanvas).TransformBounds(new Rect(0,0,hero.ActualWidth,hero.ActualHeight))});continue;}if(item.Kind=="discard"){matchEffects.Discard(item);continue;}if(item.Kind=="spell"){matchEffects.Spell(item);if(playExtras&&item.Seat!=matchViewSeat)matchEffects.SpellCard(item);continue;}if(item.Kind!="damage")continue;string key=VisualKey(item.Seat,item.UnitId);FrameworkElement element;MatchVisualAnchor anchor;old.TryGetValue(key,out anchor);visualTargets.TryGetValue(key,out element);if(anchor==null&&element!=null)anchor=new MatchVisualAnchor{Bounds=element.TransformToVisual(matchEffectsCanvas).TransformBounds(new Rect(0,0,element.ActualWidth,element.ActualHeight))};if(anchor==null)continue;anchor.Element=element;int hits;delays.TryGetValue(key,out hits);delays[key]=hits+1;matchEffects.Damage(item,anchor,TimeSpan.FromMilliseconds(80+hits*80));}}));}
}
}
