using System;
using System.IO;
using System.Linq;

namespace Touchfish {
public partial class PanelWindow {
 void VerifyMinionSpeech(string folder){
  var game=MatchFixture();game.Summon(0,"VAN_EX1_557");game.Summon(0,"VAN_NEW1_029");game.Summon(0,"VAN_EX1_100");Check(game.VisualEvents.Where(e=>e.Kind=="minion-speech").Select(e=>e.CardName).SequenceEqual(new[]{"我能在河边钓上一整天的鱼。","你等着，等我有十点法力值的时候！","愿青龙指引你。"}),"Three minions have the requested entrance lines with 河边 corrected");
  var remote=LanProtocol.ReadView(catalog,LanProtocol.Copy(LanProtocol.View(game,1,"speech",1)));Check(remote.VisualEvents.Select(e=>e.UnitId).SequenceEqual(game.VisualEvents.Select(e=>e.UnitId)),"Minion speech retains source identity in public snapshots");
  match=MatchFixture();matchViewSeat=0;lanMode=false;awaitHandoff=false;localTest=false;inspectMatch=false;ClearPending();ApplyMode(false);ApplyTheme(true,true);SetFullEffects(false);ShowPage("match");var renderer=(OfficeMatchVisualEffects)matchEffects;int bubbles=renderer.EmoteCount,shakes=renderer.CardShakeCount;var nat=match.Summon(0,"VAN_EX1_557");RenderMatch();Check(renderer.EmoteCount==bubbles&&matchEffectsCanvas.Children.Count==0,"Nat entrance bubble is hidden with extra effects disabled");Check(renderer.CardShakeCount==shakes,"Entrance speech does not add an unrequested shake");renderer.Clear();bubbles=renderer.EmoteCount;match.FishingDraw(nat);RenderMatch();Check(renderer.EmoteCount==bubbles&&matchEffectsCanvas.Children.Count==0,"Fishing bubble is hidden with extra effects disabled");Check(renderer.CardShakeCount==shakes,"Fishing shake respects disabled effects");
  SetFullEffects(true);int beforeEnable=renderer.EmoteCount;RenderMatch();UpdateLayout();Check(renderer.EmoteCount==beforeEnable,"Enabling effects does not replay disabled speech");match.Players[0].Board.Remove(nat);nat=match.Summon(0,"VAN_EX1_557");RenderMatch();PumpLan(()=>renderer.EmoteCount==beforeEnable+1,"Enabled Nat entrance displays the correct bubble");Render(Path.Combine(folder,"90-nat-entrance-speech.png"));renderer.Clear();bubbles=renderer.EmoteCount;shakes=renderer.CardShakeCount;match.FishingDraw(nat);RenderMatch();PumpLan(()=>renderer.EmoteCount==bubbles+1&&renderer.CardShakeCount==shakes+1,"Enabled fishing feedback adds exactly one minion shake");Render(Path.Combine(folder,"91-nat-fishing-speech.png"));RenderMatch();UpdateLayout();Check(renderer.EmoteCount==bubbles+1&&renderer.CardShakeCount==shakes+1,"Repeated snapshot does not replay fishing feedback");
  ApplyMode(true);bubbles=renderer.EmoteCount;shakes=renderer.CardShakeCount;match.FishingDraw(nat);RenderMatch();UpdateLayout();Check(renderer.EmoteCount==bubbles&&renderer.CardShakeCount==shakes&&matchEffectsCanvas.Children.Count==0,"Minimal suppresses fishing and entrance speech regardless of effects");ApplyMode(false);RenderMatch();UpdateLayout();Check(renderer.EmoteCount==bubbles,"Hidden minion speech never replays after mode change");int events=match.VisualEvents.Count;match.Players[0].Deck.Clear();match.FishingDraw(nat);Check(match.VisualEvents.Skip(events).All(e=>e.Kind!="fishing"),"Empty deck fatigue does not claim a successful catch");SetFullEffects(false);RenderMatch();
 }
}
}
