using System;
using System.IO;
using System.Linq;

namespace Touchfish {
public partial class PanelWindow {
 public void PreviewOverloadScope(string folder){
  previewRun=true;Directory.CreateDirectory(folder);var cards=catalog.Deckable(catalog.Pool("classic-2014")).Where(c=>c.Overload>0).ToArray();Check(cards.Length==9&&cards.All(c=>matchRules.Supports(c)),"All nine frozen Classic overload cards are supported");
  foreach(var card in cards){var sample=MatchFixture("SHAMAN");if(card.BaseId=="EX1_251"){sample.Summon(1,"VAN_CS2_182");sample.Summon(1,"VAN_CS2_182");}int id=Inject(sample,card.BaseId);string mask=sample.Rules.Target(card,null);Check(sample.Play(0,id,mask=="ANY_CHARACTER"?new MatchTarget(1):null).Success&&sample.Players[0].Overload==card.Overload&&sample.Players[0].LockedMana==0,"Played overload card queues its frozen magnitude: "+card.Name);}
  var g=MatchFixture("SHAMAN");int bolt=Inject(g,"EX1_238"),burst=Inject(g,"EX1_241");g.Play(0,bolt,new MatchTarget(1));g.Play(0,burst,new MatchTarget(1));Check(g.Players[0].Overload==3&&g.Players[0].Mana==6&&g.Players[0].LockedMana==0,"Multiple overload cards stack without locking current mana");g.EndTurn();Check(g.Players[0].Overload==3&&g.Players[1].LockedMana==0,"Overload waits through the opponent turn and does not affect opponent");g.EndTurn();Check(g.Players[0].Overload==0&&g.Players[0].LockedMana==3&&g.Players[0].Mana==7,"Next own turn consumes the queue and locks three crystals");bolt=Inject(g,"EX1_238");g.Play(0,bolt,new MatchTarget(1));Check(g.Players[0].LockedMana==3&&g.Players[0].Overload==1,"Current lock and next-turn queue remain independent");g.EndTurn();g.EndTurn();Check(g.Players[0].LockedMana==1&&g.Players[0].Mana==9&&g.Players[0].Overload==0,"New overload replaces rather than adds to expired previous lock");g.EndTurn();g.EndTurn();Check(g.Players[0].LockedMana==0&&g.Players[0].Mana==10,"Mana fully unlocks on following turn without new overload");
  g=MatchFixture("SHAMAN");g.Players[0].MaxMana=g.Players[0].Mana=2;OverloadRules.Queue(g,0,8);g.EndTurn();g.EndTurn();Check(g.Players[0].MaxMana==3&&g.Players[0].LockedMana==3&&g.Players[0].Mana==0,"Overload beyond available crystals clamps the actual locked count");g.EndTurn();g.EndTurn();Check(g.Players[0].LockedMana==0&&g.Players[0].Mana==4,"Excess queued overload does not spill into an extra turn");
  g=MatchFixture("SHAMAN");g.Players[0].LockedMana=3;g.Players[0].Mana=7;int coin=Inject(g,"GAME_COIN");g.Play(0,coin);int innervate=Inject(g,"EX1_169");g.Play(0,innervate);Check(g.Players[0].Mana==7&&g.Players[0].LockedMana==3,"Coin and Innervate cannot fill locked crystals at ten total crystals");g.Players[0].MaxMana=5;g.Players[0].LockedMana=2;g.Players[0].Mana=3;innervate=Inject(g,"EX1_169");g.Play(0,innervate);Check(g.Players[0].Mana==5&&g.Players[0].LockedMana==2&&g.Players[0].MaxMana==5,"Temporary mana may add available temporary crystals below the ten-crystal cap");Check(Enumerable.Range(0,10).Count(n=>OverloadRules.IsFilled(g.Players[0],n))==5&&!OverloadRules.IsFilled(g.Players[0],3)&&!OverloadRules.IsFilled(g.Players[0],4),"Crystal display fills temporary slots without coloring locked slots as usable");
  g=MatchFixture("SHAMAN");g.Summon(0,"VAN_EX1_243");Check(g.Players[0].Overload==0,"Summoned overload minion does not count as a played overload card");bolt=Inject(g,"EX1_238");g.Players[0].Mana=0;Check(!g.Play(0,bolt,new MatchTarget(1)).Success&&g.Players[0].Overload==0&&g.Players[0].Hand.Count==1,"Insufficient mana rejects without queuing overload");g.Players[0].Mana=10;Check(!g.Play(0,bolt).Success&&g.Players[0].Overload==0&&g.Players[0].Mana==10,"Invalid target rejects without cost or overload");
  g=MatchFixture("WARRIOR");bolt=Inject(g,"EX1_238");Check(g.Play(0,bolt,new MatchTarget(1)).Success&&g.Players[0].Overload==1,"Foreign hand spell overload applies to actual caster");
  g=MatchFixture("SHAMAN");int fork=Inject(g,"EX1_251");g.Summon(1,"VAN_CS2_182");Check(!g.Play(0,fork).Success&&g.Players[0].Mana==10&&g.Players[0].Overload==0,"Forked Lightning requires two enemy minions before spending");g.Summon(1,"VAN_CS2_182");g.Summon(1,"VAN_CS2_182");Check(g.Play(0,fork).Success&&g.Players[1].Board.Count(u=>u.DamageTaken==2)==2&&g.Players[1].Board.Count(u=>u.DamageTaken==0)==1&&g.Players[0].Overload==2,"Forked Lightning hits two distinct random minions and queues two overload");
  g=MatchFixture("SHAMAN");g.Summon(0,"VAN_EX1_563");g.Summon(1,"VAN_CS2_182");g.Summon(1,"VAN_CS2_182");fork=Inject(g,"EX1_251");g.Play(0,fork);Check(g.Players[1].Board.Count==0&&g.VisualEvents.Count(e=>e.Kind=="damage"&&e.Amount==7)==2,"Forked Lightning adds spell power separately to both hits");
  g=MatchFixture("SHAMAN");g.Players[0].Mana=0;TimedCostRules.GrantFreeSpells(g,0,g.Turn);g.Summon(1,"VAN_CS2_182");g.Summon(1,"VAN_CS2_182");fork=Inject(g,"EX1_251");Check(g.Play(0,fork).Success&&g.Players[0].Mana==0&&g.Players[0].Overload==2,"Zero-cost spell still applies its printed overload");
  VerifyOverloadTcp(folder);var coverage=catalog.Deckable(catalog.Pool("classic-2014")).Select(c=>new{Id=c.Id,Name=c.Name,Supported=matchRules.Supports(c)}).ToArray();JsonData.Write(Path.Combine(folder,"match-rule-coverage.json"),new{SupportedCards=coverage.Count(c=>c.Supported),TotalCards=382,Cards=coverage,Scope="Registry coverage; focused overload and Forked Lightning checks"});File.WriteAllText(Path.Combine(folder,"overload-verification.txt"),"PASS: "+checks+" targeted assertions. All nine Classic overload cards, queue/lock/restore, crystal cap, no overflow carry, current and future locks, temporary mana, invalid play, generated foreign/free spells, distinct Forked Lightning targets, spell damage, authoritative real TCP and WPF previews.");
 }
 void VerifyOverloadTcp(string folder){
  LeaveLan();ApplyTheme(true,true);ApplyMode(false);SetFullEffects(false);var guest=new PanelWindow(true){previewRun=true,ShowInTaskbar=false,Opacity=0};guest.Show();guest.ApplyTheme(true,true);guest.ApplyMode(false);
  try{lanPort.Text=FreeLanPort().ToString();lanDeck.SelectedIndex=0;lanClass.SelectedItem=Classes.First(c=>c.Key=="MAGE");BeginLan(true);guest.lanDeck.SelectedIndex=0;guest.lanClass.SelectedItem=Classes.First(c=>c.Key=="SHAMAN");guest.lanAddress.Text="127.0.0.1:"+lanPort.Text;guest.BeginLan(false);PumpLan(()=>lanReady&&guest.lanReady,"Overload fixture connects real TCP peers");DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>guest.match.Players[0].MulliganDone,"Host mulligan synchronized");guest.DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>match.MulliganComplete&&!guest.lanWaiting,"Guest mulligan starts fixture");DoMatch("end");PumpLan(()=>guest.match.Active==1,"Guest overload turn begins");var game=lanAuthority.Game;foreach(var p in game.Players){p.Hand.Clear();p.Board.Clear();}game.Players[1].Mana=game.Players[1].MaxMana=10;game.Summon(0,"VAN_CS2_182");game.Summon(0,"VAN_CS2_182");int fork=Inject(game,"EX1_251",1);PublishLan();PumpLan(()=>guest.match.Players[1].Hand.Any(h=>h.Id==fork),"Forked Lightning hand fixture reaches guest");guest.BeginCard(fork);PumpLan(()=>!guest.lanWaiting&&guest.match.Players[1].Overload==2,"Host queues guest overload and publishes it");Check(game.Players[1].Mana==9&&guest.match.Players[1].Mana==9&&game.Players[1].LockedMana==0,"Current mana pays cost but remains unlocked");Check(enemyHandStatus.Text.Contains("下回合锁2")&&OverloadRules.ResourceLabel(guest.match.Players[1],false).Contains("下回合锁2"),"Both views expose upcoming overload");guest.Opacity=1;guest.Render(Path.Combine(folder,"98-overload-pending-normal.png"));guest.Opacity=0;guest.DoMatch("end");PumpLan(()=>!guest.lanWaiting&&match.Active==0,"Host turn begins while guest overload waits");DoMatch("end");PumpLan(()=>guest.match.Active==1&&guest.match.Players[1].LockedMana==2,"Next guest turn activates two locked crystals on both peers");Check(game.Players[1].Mana==8&&guest.match.Players[1].Mana==8&&game.Players[1].Overload==0&&guest.match.Players[1].Overload==0,"Authoritative lock and available mana agree");guest.Opacity=1;guest.Render(Path.Combine(folder,"99-overload-locked-normal.png"));guest.ApplyMode(true);guest.Render(Path.Combine(folder,"100-overload-locked-minimal.png"));guest.Opacity=0;Check(guest.Width==392&&guest.Height==300,"Overload markers fit minimal office window");guest.DoMatch("end");PumpLan(()=>!guest.lanWaiting&&match.Active==0,"Following host turn synchronized");DoMatch("end");PumpLan(()=>guest.match.Active==1&&guest.match.Players[1].LockedMana==0,"Following guest turn restores locked crystals");Check(game.Players[1].Mana==10&&guest.match.Players[1].Mana==10&&game.Log.SequenceEqual(guest.match.Log),"Restored mana and public history agree across peers");
  }finally{guest.LeaveLan();guest.Close();LeaveLan();}
 }
}
}
