using System;
using System.IO;
using System.Linq;
using System.Windows;
namespace Touchfish {
public partial class PanelWindow {
 void VerifyOnyxia(string folder){int before=checks;Check(matchRules.Supports(catalog.Card("VAN_EX1_562")),"Onyxia supported");
  var game=MatchFixture();int hand=Inject(game,"EX1_562");Check(game.Play(0,hand).Success,"Onyxia battlecry succeeds");var board=game.Players[0].Board;Check(board.Count==7&&board[3].CardId=="VAN_EX1_562"&&board.Count(u=>u.CardId=="GAME_WHELP")==6,"Empty board creates three Whelps on each side");Check(board.Where(u=>u.CardId=="GAME_WHELP").All(u=>u.BaseAttack==1&&u.MaxHealth==1&&u.Race=="DRAGON"),"Whelps are 1/1 Dragons");Check(DeckRules.CanAdd(catalog,new DeckDocument(),game.Card("GAME_WHELP"))!=null,"Whelps cannot be included in decks");Check(!game.Attack(0,board[0].Id,new MatchTarget(1)).Success,"Whelps obey summoning sickness");
  for(int existing=0;existing<=6;existing++)for(int position=0;position<=existing;position++){game=MatchFixture();for(int n=0;n<existing;n++)game.Summon(0,"VAN_CS2_182");var original=game.Players[0].Board.Select(u=>u.Id).ToArray();hand=Inject(game,"EX1_562");Check(game.Play(0,hand,null,position).Success,"Onyxia valid insertion "+existing+"/"+position);board=game.Players[0].Board;int wings=6-existing,left=(wings+1)/2,right=wings/2;int anchor=board.FindIndex(u=>u.CardId=="VAN_EX1_562");Check(board.Count==7&&anchor==position+left&&board.Take(anchor).Count(u=>u.CardId=="GAME_WHELP")==left&&board.Skip(anchor+1).Count(u=>u.CardId=="GAME_WHELP")==right,"Alternating sides fill only available slots");Check(board.Where(u=>u.CardId=="VAN_CS2_182").Select(u=>u.Id).SequenceEqual(original),"Existing unit relative order preserved");}
  game=MatchFixture();for(int n=0;n<7;n++)game.Summon(0,"VAN_CS2_182");hand=Inject(game,"EX1_562");Check(!game.Play(0,hand).Success&&game.Players[0].Mana==10&&game.Players[0].Hand.Count==1,"Full board rejects Onyxia before spending");game=MatchFixture();hand=Inject(game,"EX1_562");game.Players[0].Mana=8;Check(!game.Play(0,hand).Success&&game.Players[0].Board.Count==0&&game.Players[0].Hand.Count==1,"Insufficient mana never summons");
  game=MatchFixture();var champion=game.Summon(0,"VAN_CS2_222");hand=Inject(game,"EX1_562");game.Play(0,hand,null,0);Check(game.Players[0].Board.Where(u=>u.CardId=="GAME_WHELP").All(u=>game.AttackValue(u)==2&&u.MaxHealth==2),"Whelps inherit active external auras");var masked=LanProtocol.ReadView(catalog,LanProtocol.Copy(LanProtocol.View(game,1,"onyxia",1)));Check(masked.Players[0].Board.Select(u=>u.CardId).SequenceEqual(game.Players[0].Board.Select(u=>u.CardId))&&masked.Players[0].Hand.Count==0,"Masked snapshot preserves Whelp order without hand disclosure");
  match=MatchFixture();hand=Inject(match,"EX1_562");match.Play(0,hand);matchViewSeat=0;awaitHandoff=false;ClearPending();inspectMatch=false;fullEffects=false;ApplyTheme(true,true);ApplyMode(false);RenderMatch();ShowPage("match");Render(Path.Combine(folder,"73-onyxia-normal.png"));Check(liveUnits.Count==7&&Width==548&&Height==474,"Normal seven minions remain visible");ApplyMode(true);RenderMatch();Render(Path.Combine(folder,"74-onyxia-minimal.png"));Check(Width==392&&Height==300&&liveUnits.Count==7,"Minimal retains seven fixed slots");foreach(var unit in liveUnits){var bounds=unit.TransformToAncestor(livePanel).TransformBounds(new Rect(0,0,unit.ActualWidth,unit.ActualHeight));Check(bounds.Right<=livePanel.ActualWidth+1,"Whelp slots fit narrow window");}JsonData.Write(Path.Combine(folder,"onyxia-verification.json"),new{Assertions=checks-before,AlternatingLeftRight=true,EmptyBoardEachSide=3,BoardCap=7,PrintedTokenStats="1/1 Dragon",ExistingOrderPreserved=true,MaskedSnapshot=true});
 }
 public void PreviewSummonScope(string folder){previewRun=true;Directory.CreateDirectory(folder);VerifyOnyxia(folder);var coverage=catalog.Deckable(catalog.Pool("classic-2014")).Select(c=>new{Id=c.Id,Name=c.Name,Supported=matchRules.Supports(c)}).ToArray();JsonData.Write(Path.Combine(folder,"match-rule-coverage.json"),new{SupportedCards=coverage.Count(c=>c.Supported),TotalCards=382,Cards=coverage,Scope="Coverage registry snapshot; focused Onyxia checks only"});File.WriteAllText(Path.Combine(folder,"summon-verification.txt"),"PASS: "+checks+" assertions. Focused Onyxia alternating-side summons, placement, capacity, cost, external auras, masked snapshot and actual WPF previews. No physical mouse or TCP test in this scope.");}
}
}
