using System;
using System.IO;
using System.Linq;
using System.Windows;
namespace Touchfish {
public partial class PanelWindow {
 void VerifyTurnEnd(string folder){int before=checks;Check(TurnEndRules.Ids.All(id=>matchRules.Supports(catalog.Card("VAN_"+id))),"All frozen turn-end cards have registered effects");
  foreach(string id in new[]{"CS2_059","EX1_004","NEW1_037"}){var g=MatchFixture();var source=g.Summon(0,"VAN_"+id);var ally=g.Summon(0,"VAN_CS2_182");int attack=g.AttackValue(ally),health=ally.MaxHealth;g.EndTurn();Check(g.AttackValue(ally)==attack+(id=="NEW1_037"?1:0)&&ally.MaxHealth==health+(id=="NEW1_037"?0:1),"End buff affects another friendly unit "+id);Check(source.BuffAttack==0&&source.BuffHealth==0,"End buff excludes itself");g.EndTurn();Check(ally.BuffAttack+ally.BuffHealth==1,"Own-end buff does not fire on opponent end");}
  var game=MatchFixture();var gruul=game.Summon(1,"VAN_NEW1_038");game.EndTurn();Check(game.AttackValue(gruul)==8&&gruul.MaxHealth==8,"Gruul grows on opponent end");game.EndTurn();Check(gruul.MaxHealth==9,"Gruul grows on own end");game.Silence(new MatchTarget(1,gruul.Id));game.EndTurn();Check(gruul.MaxHealth==7,"Silenced Gruul stops growing");
  game=MatchFixture();var rag=game.Summon(0,"VAN_EX1_298");game.Summon(0,"VAN_EX1_563");Check(!game.Attack(0,rag.Id,new MatchTarget(1)).Success,"Ragnaros cannot attack");game.EndTurn();Check(game.Players[1].Health==22,"Ragnaros deals exactly eight without spell power");game=MatchFixture();game.Players[1].Health=8;game.Summon(0,"VAN_EX1_298");int deck=game.Players[1].Deck.Count;game.EndTurn();Check(game.Finished&&game.Winner==0&&game.Active==0&&game.Turn==1&&game.Players[1].Deck.Count==deck,"Turn-end lethal prevents next turn and draw");
  game=MatchFixture();var baron=game.Summon(0,"VAN_EX1_249");var late=game.Summon(0,"VAN_EX1_004");var body=game.Summon(0,"VAN_CS2_182");game.EndTurn();Check(baron.Health==5&&body.Health==3&&!game.Players[0].Board.Contains(late)&&body.BuffHealth==0&&game.Players[0].Health==28&&game.Players[1].Health==28,"Baron excludes himself and killed later trigger is skipped");game=MatchFixture();game.Summon(0,"VAN_EX1_004");baron=game.Summon(0,"VAN_EX1_249");game.Summon(0,"VAN_CS2_182");game.EndTurn();Check(game.Log.FindIndex(s=>s.Contains("触发：年轻"))<game.Log.FindIndex(s=>s.Contains("触发：迦顿")),"Older friendly triggers resolve first");
  game=MatchFixture();var hogger=game.Summon(0,"VAN_NEW1_040");game.EndTurn();Check(game.Players[0].Board.Count==2&&game.Players[0].Board[1].CardId=="GAME_GNOLL"&&game.Players[0].Board[1].Taunt,"Hogger summons taunt Gnoll beside source");game=MatchFixture();hogger=game.Summon(0,"VAN_NEW1_040");for(int n=0;n<6;n++)game.Summon(0,"VAN_CS2_182");game.EndTurn();Check(game.Players[0].Board.Count==7,"Hogger obeys full board");
  game=MatchFixture();var master=game.Summon(0,"VAN_EX1_597");master.DamageTaken=master.MaxHealth-1;for(int n=0;n<6;n++)game.Summon(0,"VAN_CS2_182");game.EndTurn();Check(game.Players[0].Board.Count==7&&!game.Players[0].Board.Contains(master)&&game.Players[0].Board.Any(u=>u.CardId=="VAN_EX1_598"),"Dying Imp Master frees slot before creating Imp");
  game=MatchFixture();var totem=game.Summon(0,"VAN_NEW1_009");var second=game.Summon(0,"VAN_NEW1_009");body=game.Summon(0,"VAN_CS2_182");body.DamageTaken=3;game.EndTurn();Check(body.Health==4,"Each Healing Totem heals independently");game=MatchFixture();var arcanist=game.Summon(0,"VAN_EX1_274");game.EndTurn();Check(arcanist.BuffAttack==0,"Arcanist does nothing without active secret");game.EndTurn();game.Players[0].SecretCount=1;game.EndTurn();Check(arcanist.BuffAttack==2&&arcanist.BuffHealth==2,"Arcanist reacts to host secret count contract");Check(!matchRules.Supports(catalog.Card("VAN_EX1_287")),"Unimplemented secret card remains unavailable");
  game=MatchFixture("WARLOCK");body=game.Summon(0,"VAN_CS2_182");int hand=Inject(game,"EX1_316");game.Play(0,hand,new MatchTarget(0,body.Id));game.EndTurn();Check(!game.Players[0].Board.Contains(body),"Power Overwhelming destroys buffed target at end");game=MatchFixture("WARLOCK");body=game.Summon(0,"VAN_CS2_182");hand=Inject(game,"EX1_316");game.Play(0,hand,new MatchTarget(0,body.Id));game.Silence(new MatchTarget(0,body.Id));game.EndTurn();Check(game.Players[0].Board.Contains(body)&&body.MaxHealth==5,"Silence removes delayed Power Overwhelming destruction");
  game=MatchFixture("DRUID");hand=Inject(game,"EX1_571");Check(game.Play(0,hand).Success&&game.Players[0].Board.Count==3&&game.Players[0].Board.All(u=>u.Charge),"Classic Force of Nature creates three charge Treants");game.EndTurn();Check(game.Players[0].Board.Count==0,"Force of Nature Treants die at end");
  game=MatchFixture("PRIEST");body=game.Summon(1,"VAN_CS2_179");hand=Inject(game,"EX1_334");Check(game.Play(0,hand,new MatchTarget(1,body.Id)).Success&&body.Owner==0&&game.HasCharge(body),"Shadow Madness temporarily steals valid minion");game.EndTurn();Check(body.Owner==1&&game.Players[1].Board.Contains(body)&&body.ReturnTurn==-1,"Temporary control returns at end");game=MatchFixture("PRIEST");body=game.Summon(1,"VAN_CS2_179");hand=Inject(game,"EX1_334");game.Play(0,hand,new MatchTarget(1,body.Id));game.ReturnToHand(new MatchTarget(0,body.Id));Check(game.Players[0].Hand.Count==0&&game.Players[1].Hand.Any(h=>h.CardId=="VAN_CS2_179"),"Bounce returns stolen card to original owner");
  game=MatchFixture();var ysera=game.Summon(0,"VAN_EX1_572");game.EndTurn();Check(game.Players[0].Hand.Count==1&&TurnEndRules.DreamIds.Contains(game.Players[0].Hand[0].CardId),"Ysera creates known frozen Dream card");Check(TurnEndRules.DreamIds.Where(id=>game.Card(id).Name!="梦境").All(id=>!game.Log.Any(line=>line.Contains(game.Card(id).Name))),"Generated Dream identity is not exposed in shared log");var masked=LanProtocol.ReadView(catalog,LanProtocol.Copy(LanProtocol.View(game,1,"turn-end",1)));Check(masked.Players[0].Hand.Count==0&&masked.Players[0].HandCount==1,"Dream hand is masked in remote snapshot");game=MatchFixture();game.Summon(0,"VAN_EX1_572");for(int n=0;n<10;n++)Inject(game,"CS2_182");game.EndTurn();Check(game.Players[0].Hand.Count==10&&game.Log.Any(line=>line.Contains("未获得梦境牌")),"Ysera respects hand cap");
  foreach(string id in TurnEndRules.DreamIds){game=MatchFixture("WARRIOR");game.Players[0].Hand.Add(new HandCard{Id=testHandId++,CardId=id});hand=game.Players[0].Hand[0].Id;body=game.Summon(0,"VAN_CS2_182");Check(game.Play(0,hand,id.EndsWith("04")||id.EndsWith("05")?new MatchTarget(0,body.Id):null).Success,"Any class may play generated Dream "+id);}
  game=MatchFixture();body=game.Summon(1,"VAN_CS2_182");game.Players[0].Hand.Add(new HandCard{Id=testHandId++,CardId="VAN_DREAM_05"});game.Play(0,game.Players[0].Hand[0].Id,new MatchTarget(1,body.Id));game.EndTurn();Check(game.Players[1].Board.Contains(body),"Nightmare does not expire at immediate end");game.EndTurn();Check(!game.Players[1].Board.Contains(body),"Nightmare expires at caster next turn start");
  match=MatchFixture();match.Summon(0,"VAN_NEW1_040");match.Summon(0,"VAN_EX1_572");match.Summon(1,"VAN_NEW1_038");match.EndTurn();matchViewSeat=0;awaitHandoff=false;ClearPending();inspectMatch=false;ApplyTheme(true,true);ApplyMode(false);RenderMatch();ShowPage("match");Render(Path.Combine(folder,"77-turn-end-normal.png"));ApplyMode(true);RenderMatch();Render(Path.Combine(folder,"78-turn-end-minimal.png"));Check(Width==392&&Height==300&&liveUnits.Count==4,"Focused end-turn preview keeps fixed window and board");JsonData.Write(Path.Combine(folder,"turn-end-verification.json"),new{Assertions=checks-before,OwnEndAndEveryEnd=true,Silence=true,Ordering=true,LethalStopsTurn=true,DelayedDestruction=true,TemporaryControl=true,DreamsPrivate=true,SecretCondition="Secret count hook verified; secret activation not implemented"});
 }
 void VerifyTurnEndNetwork(){LeaveLan();var guest=new PanelWindow(true){previewRun=true,ShowInTaskbar=false,Opacity=0};guest.Show();try{lanPort.Text=FreeLanPort().ToString();lanClass.SelectedItem=Classes.First(c=>c.Key=="MAGE");lanDeck.SelectedIndex=0;BeginLan(true);guest.lanClass.SelectedItem=Classes.First(c=>c.Key=="WARRIOR");guest.lanDeck.SelectedIndex=0;guest.lanAddress.Text="127.0.0.1:"+lanPort.Text;guest.BeginLan(false);PumpLan(()=>lanReady&&guest.lanReady,"Focused real TCP peers connect");var authority=lanAuthority.Game;authority.Players[0].Hand.Clear();authority.Summon(0,"VAN_EX1_572");authority.Summon(0,"VAN_EX1_575");var enemy=authority.Summon(1,"VAN_NEW1_038");PublishLan();PumpLan(()=>guest.match.Players[0].Board.Count==2,"End-turn fixture synchronized");int revision=lanRevision;DoMatch("end");PumpLan(()=>guest.lanRevision==revision+1,"End triggers settle once on host");Check(authority.Players[0].Hand.Count==2&&guest.match.Players[0].HandCount==2&&guest.match.Players[0].Hand.Count==0,"Dream and draw counts synchronize without secret hand");Check(enemy.MaxHealth==8&&guest.match.Players[1].Board[0].MaxHealth==8&&authority.Log.SequenceEqual(guest.match.Log),"Both turn-end state and public history agree");}finally{guest.LeaveLan();guest.Close();LeaveLan();}}
 public void PreviewTurnEndScope(string folder){previewRun=true;Directory.CreateDirectory(folder);VerifyTurnEnd(folder);VerifyTurnEndNetwork();var coverage=catalog.Deckable(catalog.Pool("classic-2014")).Select(c=>new{Id=c.Id,Name=c.Name,Supported=matchRules.Supports(c)}).ToArray();JsonData.Write(Path.Combine(folder,"match-rule-coverage.json"),new{SupportedCards=coverage.Count(c=>c.Supported),TotalCards=382,Cards=coverage,Scope="Registry coverage; focused turn-end checks"});File.WriteAllText(Path.Combine(folder,"turn-end-verification.txt"),"PASS: "+checks+" assertions. Focused turn-end effects, expiry, generated Dreams, public snapshots, real TCP and WPF previews. Secret activation remains unavailable.");}
}
}
