using System;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Collections.Generic;

namespace Touchfish {
public partial class PanelWindow {
 void VerifyUpdates(string folder){int before=checks;string root=Path.Combine(folder,"update-fixture-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);Directory.CreateDirectory(Path.Combine(root,"data"));Directory.CreateDirectory(Path.Combine(root,"decks"));File.WriteAllText(Path.Combine(root,"Touchfish.exe"),"old-app");File.WriteAllText(Path.Combine(root,"VERSION"),"0.1.1");File.WriteAllText(Path.Combine(root,"data","pools.json"),"old-pool");File.WriteAllText(Path.Combine(root,"decks","draft.json"),"private-deck");File.WriteAllText(Path.Combine(root,"preferences.ini"),"personal-theme");string stage=Path.Combine(root,"_updates","downloads","test");Directory.CreateDirectory(Path.Combine(stage,"files","data"));File.WriteAllText(Path.Combine(stage,"files","Touchfish.exe"),"new-app");File.WriteAllText(Path.Combine(stage,"files","VERSION"),"0.2.0");File.WriteAllText(Path.Combine(stage,"files","data","pools.json"),"new-pool");var manifest=new UpdateManifest{Version="v0.2.0",Files=new[]{"Touchfish.exe","VERSION","data/pools.json"}.Select(p=>new UpdateFile{Path=p,Sha256=UpdateCore.Hash(UpdateCore.Under(Path.Combine(stage,"files"),p))}).ToArray()};UpdateCore.Write(Path.Combine(stage,"manifest.json"),manifest);
  Check(UpdateCore.VersionOf("v0.2.0")>UpdateCore.VersionOf("v0.1.1")&&UpdateCore.VersionOf("v0.1")==UpdateCore.VersionOf("0.1.0"),"Update versions compare semantically");Check(!UpdateCore.Allowed("preferences.ini")&&!UpdateCore.Allowed("decks/draft.json")&&!UpdateCore.Allowed("../Touchfish.exe")&&!UpdateCore.Allowed("data/../../secret.json")&&!UpdateCore.Allowed("data\\x.json")&&!UpdateCore.Allowed("data/file.json "),"Update paths cannot replace private files or escape root");string planPath=UpdateCore.Prepare(root,stage,0);var plan=UpdateCore.Read<UpdatePlan>(planPath);bool failed=false;try{UpdateCore.Apply(plan,n=>{if(n==2)throw new IOException("Injected replacement failure");});}catch(IOException){failed=true;}Check(failed&&File.ReadAllText(Path.Combine(root,"Touchfish.exe"))=="old-app"&&File.ReadAllText(Path.Combine(root,"data","pools.json"))=="old-pool","Partial installation failure restores original app and data");Check(!File.Exists(Path.Combine(root,"_updates","pending.json"))&&!Directory.Exists(plan.Backup),"Recovery removes temporary old-version data");
  plan=UpdateCore.Read<UpdatePlan>(UpdateCore.Prepare(root,stage,0));string temporary=UpdateCore.Apply(plan);Check(File.ReadAllText(Path.Combine(root,"Touchfish.exe"))=="new-app"&&File.ReadAllText(Path.Combine(root,"data","pools.json"))=="new-pool","Validated installation replaces managed files");Check(File.ReadAllText(Path.Combine(root,"decks","draft.json"))=="private-deck"&&File.ReadAllText(Path.Combine(root,"preferences.ini"))=="personal-theme","Update preserves deck and theme bytes");UpdateCore.Finish(root);Check(!Directory.Exists(temporary)&&!Directory.Exists(Path.Combine(root,"_updates","backups")),"Successful update retains no historical local backup");
  string zip=Path.Combine(root,"test.zip");using(var archive=ZipFile.Open(zip,ZipArchiveMode.Create)){foreach(var file in manifest.Files)archive.CreateEntryFromFile(UpdateCore.Under(Path.Combine(stage,"files"),file.Path),file.Path);}UpdateCore.Extract(zip,Path.Combine(root,"extracted"),manifest);Check(File.ReadAllText(Path.Combine(root,"extracted","Touchfish.exe"))=="new-app","ZIP file hashes and full manifest validated");var damaged=UpdateCore.Json().Deserialize<UpdateManifest>(UpdateCore.Json().Serialize(manifest));damaged.Files[0].Sha256=new string('0',64);failed=false;try{UpdateCore.Extract(zip,Path.Combine(root,"damaged"),damaged);}catch(InvalidDataException){failed=true;}Check(failed,"Tampered package rejected before installed files change");string malicious=Path.Combine(root,"bad.zip");using(var archive=ZipFile.Open(malicious,ZipArchiveMode.Create)){using(var writer=new StreamWriter(archive.CreateEntry("../escape.txt").Open()))writer.Write("bad");}failed=false;try{UpdateCore.Extract(malicious,Path.Combine(root,"blocked"),manifest);}catch(InvalidDataException){failed=true;}Check(failed&&!File.Exists(Path.Combine(root,"escape.txt")),"ZIP traversal rejected");
  OpenUpdates();Render(Path.Combine(folder,"52-github-updates.png"));ApplyMode(false);Render(Path.Combine(folder,"53-github-updates-normal.png"));ApplyMode(true);ShowPage("lan");JsonData.Write(Path.Combine(folder,"update-verification.json"),new {Assertions=checks-before,PreservesUserData=true,RemoteHistoryOnly=true,TemporaryRecoveryCleaned=true,HashVerification=true,TraversalBlocked=true});
 }
}
}
