using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;

namespace Touchfish {
public partial class PanelWindow {
 Grid updatesPanel;ComboBox updateVersions;TextBlock updateNotice,updateDescription;Button checkUpdateButton,downloadUpdateButton,installUpdateButton,cancelUpdateButton;CancellationTokenSource updateCancel;string updateStage;bool updateBusy,updateInstalling;
 void BuildUpdates(){updatesPanel=new Grid{Margin=new Thickness(12,8,12,8),Visibility=Visibility.Collapsed};foreach(double h in new[]{22.0,28,-1,32,26})updatesPanel.RowDefinitions.Add(new RowDefinition{Height=h<0?new GridLength(1,GridUnitType.Star):new GridLength(h)});Put(shell,updatesPanel,4);updatesPanel.Children.Add(T("版本更新 · 当前 "+AppRelease.Version,12,Ink));updateVersions=Picker(new Choice[0]);updateVersions.ToolTip="选择 GitHub 版本，较旧版本用于回退。";Put(updatesPanel,updateVersions,1);updateDescription=T("检查 GitHub 最新版本，或选择历史版本回退。卡组、草稿与设置保留；历史版本包仅存放在 GitHub。",10,Ink);updateDescription.TextWrapping=TextWrapping.Wrap;Put(updatesPanel,new ScrollViewer{Content=updateDescription,VerticalScrollBarVisibility=ScrollBarVisibility.Auto},2);updateNotice=T("尚未检查。",9,Muted);updateNotice.TextWrapping=TextWrapping.Wrap;Put(updatesPanel,updateNotice,3);
  var actions=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};var back=Btn("返回",36);back.Click+=(s,e)=>OpenReleaseNotes();actions.Children.Add(back);cancelUpdateButton=Btn("取消",36);cancelUpdateButton.Click+=(s,e)=>{if(updateCancel!=null)updateCancel.Cancel();};actions.Children.Add(cancelUpdateButton);checkUpdateButton=Btn("检查更新",64);checkUpdateButton.Click+=(s,e)=>CheckUpdates();actions.Children.Add(checkUpdateButton);downloadUpdateButton=Btn("下载",36);downloadUpdateButton.Click+=(s,e)=>DownloadUpdate();actions.Children.Add(downloadUpdateButton);installUpdateButton=Btn("安装重启",64);installUpdateButton.Click+=(s,e)=>InstallUpdate();actions.Children.Add(installUpdateButton);Put(updatesPanel,actions,4);updateVersions.SelectionChanged+=(s,e)=>{if(updateBusy)return;ClearDownloadedUpdate();var release=updateVersions.SelectedItem as GitHubRelease;if(release!=null)updateDescription.Text=release.tag_name+"\n"+(release.body??"暂无说明。");UpdateButtons();};UpdateButtons();Closed+=(s,e)=>{if(updateCancel!=null)updateCancel.Cancel();if(!updateInstalling)ClearDownloadedUpdate();};}
 void ClearDownloadedUpdate(){if(updateStage!=null){try{UpdateCore.ClearTemporary(AppDomain.CurrentDomain.BaseDirectory,updateStage);}catch(IOException){}updateStage=null;}}
 void OpenUpdates(){ApplyFonts(updatesPanel);UpdateButtons();ShowPage("updates");}
 void UpdateButtons(){if(checkUpdateButton==null)return;checkUpdateButton.IsEnabled=!updateBusy;updateVersions.IsEnabled=!updateBusy;cancelUpdateButton.IsEnabled=updateBusy;downloadUpdateButton.IsEnabled=!updateBusy&&updateVersions.SelectedItem!=null;installUpdateButton.IsEnabled=!updateBusy&&updateStage!=null;}
 async void CheckUpdates(){if(updateBusy)return;updateBusy=true;updateCancel=new CancellationTokenSource();UpdateButtons();updateNotice.Text="正在检查 GitHub…";try{var releases=await Task.Run(()=>UpdateCore.Releases(updateCancel.Token));updateVersions.ItemsSource=releases;updateVersions.SelectedIndex=releases.Length>0?0:-1;ClearDownloadedUpdate();if(releases.Length==0)updateNotice.Text="暂未发布可更新版本。";else{var latest=releases[0];updateDescription.Text=latest.tag_name+"\n"+(latest.body??"");updateNotice.Text=UpdateCore.VersionOf(latest.tag_name)>UpdateCore.VersionOf(AppRelease.Version)?"发现新版，可下载后安装。":"当前已是最新版本，可选择历史版本回退。";}}catch(Exception ex){updateNotice.Text=updateCancel.IsCancellationRequested?"已取消。":"检查失败："+ex.Message;}finally{updateBusy=false;UpdateButtons();}}
 async void DownloadUpdate(){var selected=updateVersions.SelectedItem as GitHubRelease;if(updateBusy||selected==null)return;ClearDownloadedUpdate();updateBusy=true;updateCancel=new CancellationTokenSource();UpdateButtons();updateNotice.Text="正在下载并校验…";try{updateStage=await Task.Run(()=>UpdateCore.Download(selected,AppDomain.CurrentDomain.BaseDirectory,updateCancel.Token,(done,total)=>Dispatcher.BeginInvoke(new Action(()=>updateNotice.Text=total>0?"下载 "+(done*100/total)+"%":"正在下载…"))));updateNotice.Text="校验通过，点“安装重启”应用 "+selected.tag_name+"。";}catch(Exception ex){updateNotice.Text=updateCancel.IsCancellationRequested?"已取消，当前版本保留。":"下载失败："+ex.Message;}finally{updateBusy=false;UpdateButtons();}}
 void InstallUpdate(){if(updateBusy||updateStage==null)return;if(match!=null&&!match.Finished&&(lanMode||localTest)){updateNotice.Text="请先结束对局或离开房间，再安装。";return;}try{string root=AppDomain.CurrentDomain.BaseDirectory;string plan=UpdateCore.Prepare(root,updateStage,System.Diagnostics.Process.GetCurrentProcess().Id);UpdateCore.LaunchInstaller(root,plan);updateInstalling=true;Close();}catch(Exception ex){updateNotice.Text="安装未启动："+ex.Message;}}
}
}
