using System;
using System.IO;
using System.IO.Compression;
using System.Net;
using System.Linq;
using System.Text;
using System.Diagnostics;
using System.Threading;
using System.Collections.Generic;
using System.Security.Cryptography;
using System.Web.Script.Serialization;
using System.Xml;
using System.Xml.Linq;
using System.Text.RegularExpressions;

namespace Touchfish {
public sealed class UpdateFile {public string Path,Sha256;}
public sealed class UpdateManifest {public int Schema=1;public string Version,ZipName,ZipSha256;public bool HealthCheck;public UpdateFile[] Files;}
public sealed class GitHubAsset {public string name,browser_download_url;public long size;}
public sealed class GitHubRelease {public string tag_name,name,body,html_url;public bool draft,prerelease;public GitHubAsset[] assets;public override string ToString(){return tag_name;}}
public sealed class UpdateBackup {public string Version,Created;public UpdateFile[] Files;public string[] Absent;public bool HealthCheck;}
public sealed class UpdatePlan {public string Root,Stage,Token,Backup,Phase;public int ParentPid,InstallerPid;public UpdateManifest Manifest;}
public static class UpdateCore {
 public const string Repository="YuziPlus/touchfish",Api="https://api.github.com/repos/YuziPlus/touchfish/releases?per_page=100";
 public const string Feed="https://github.com/YuziPlus/touchfish/releases.atom";public static string LastUpdateSource;
 public static JavaScriptSerializer Json(){return new JavaScriptSerializer{MaxJsonLength=4*1024*1024};}
 public static T Read<T>(string path){return Json().Deserialize<T>(File.ReadAllText(path));}
 public static void Write(string path,object data){Directory.CreateDirectory(Path.GetDirectoryName(path));string temp=path+".tmp";File.WriteAllText(temp,Json().Serialize(data),new UTF8Encoding(false));if(File.Exists(path))File.Replace(temp,path,null);else File.Move(temp,path);}
 public static Version VersionOf(string text){Version value;if(!Version.TryParse((text??"").Trim().TrimStart('v','V'),out value))throw new InvalidDataException("版本号无效。");return new Version(value.Major,value.Minor,Math.Max(0,value.Build),Math.Max(0,value.Revision));}
 public static string Hash(string path){using(var sha=SHA256.Create())using(var input=File.OpenRead(path))return BitConverter.ToString(sha.ComputeHash(input)).Replace("-","").ToLowerInvariant();}
 public static bool Allowed(string name){if(String.IsNullOrWhiteSpace(name)||name.Contains('\\')||name.Contains(':')||name.StartsWith("/")||name.Split('/').Any(p=>p=="."||p==".."||p.Length==0||p.TrimEnd(' ','.')!=p))return false;return new[]{"Touchfish.exe","Touchfish.Update.exe","README.md","CHANGELOG.md","VERSION"}.Contains(name)||name.StartsWith("data/",StringComparison.Ordinal)&&name.EndsWith(".json",StringComparison.OrdinalIgnoreCase)||name=="data/README.md";}
 public static string Under(string root,string name){if(!Allowed(name))throw new InvalidDataException("更新包包含不允许替换的路径："+name);string basePath=Path.GetFullPath(root).TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar;string path=Path.GetFullPath(Path.Combine(basePath,name.Replace('/',Path.DirectorySeparatorChar)));if(!path.StartsWith(basePath,StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("更新路径越界。");return path;}
 public static void Validate(UpdateManifest manifest){if(manifest==null||manifest.Schema!=1||manifest.Files==null||manifest.Files.Length==0||manifest.Files.Length>1000)throw new InvalidDataException("更新清单无效。");VersionOf(manifest.Version);if(manifest.Files.Any(f=>f==null||!Allowed(f.Path)||!IsHash(f.Sha256))||manifest.Files.Select(f=>f.Path).Distinct(StringComparer.OrdinalIgnoreCase).Count()!=manifest.Files.Length||!manifest.Files.Any(f=>f.Path=="Touchfish.exe")||!manifest.Files.Any(f=>f.Path=="data/pools.json"))throw new InvalidDataException("更新清单文件无效。");}
 static bool IsHash(string value){return value!=null&&value.Length==64&&value.All(c=>Uri.IsHexDigit(c));}
 static bool AssetUrl(string url){Uri uri;return Uri.TryCreate(url,UriKind.Absolute,out uri)&&uri.Scheme=="https"&&uri.Host=="github.com"&&uri.AbsolutePath.StartsWith("/"+Repository+"/releases/download/",StringComparison.Ordinal);}
 public static byte[] Get(string url,int limit,CancellationToken cancel,Action<long,long> progress=null){if(url!=Api&&url!=Feed&&!AssetUrl(url))throw new InvalidDataException("更新来源不属于指定 GitHub 仓库。");ServicePointManager.SecurityProtocol=SecurityProtocolType.Tls12;var request=(HttpWebRequest)WebRequest.Create(url);request.UserAgent="Touchfish-Updater";request.Accept=url==Feed?"application/atom+xml":"application/vnd.github+json";request.Timeout=15000;request.ReadWriteTimeout=30000;using(cancel.Register(()=>request.Abort()))using(var response=(HttpWebResponse)request.GetResponse())using(var source=response.GetResponseStream())using(var result=new MemoryStream()){if(response.ContentLength>limit)throw new InvalidDataException("下载内容超过大小限制。");var buffer=new byte[32768];int count;while((count=source.Read(buffer,0,buffer.Length))>0){cancel.ThrowIfCancellationRequested();if(result.Length+count>limit)throw new InvalidDataException("下载内容超过大小限制。");result.Write(buffer,0,count);if(progress!=null)progress(result.Length,response.ContentLength);}return result.ToArray();}}
 public static GitHubRelease[] Releases(CancellationToken cancel){return ResolveReleases(url=>Get(url,4*1024*1024,cancel),cancel);}
 public static GitHubRelease[] ResolveReleases(Func<string,byte[]> fetch,CancellationToken cancel){Exception feedError;try{var result=ParseFeed(Encoding.UTF8.GetString(fetch(Feed)));LastUpdateSource="GitHub 版本订阅";return result;}catch(Exception ex){if(!(ex is WebException||ex is InvalidDataException||ex is XmlException||ex is ArgumentException))throw;cancel.ThrowIfCancellationRequested();feedError=ex;}try{var releases=Json().Deserialize<GitHubRelease[]>(Encoding.UTF8.GetString(fetch(Api)));LastUpdateSource="GitHub API";return (releases??new GitHubRelease[0]).Where(r=>!r.draft&&!r.prerelease&&r.assets!=null&&Regex.IsMatch(r.tag_name??"",@"^v?\d+\.\d+(\.\d+)?$")&&r.assets.Any(a=>a.name=="Touchfish-update.json")).OrderByDescending(r=>VersionOf(r.tag_name)).ToArray();}catch(Exception ex){cancel.ThrowIfCancellationRequested();throw new InvalidDataException("两个更新通道均失败。\n版本订阅："+NetworkError(feedError)+"\nAPI："+NetworkError(ex));}}
 public static GitHubRelease[] ParseFeed(string xml){XNamespace ns="http://www.w3.org/2005/Atom";XDocument document;using(var reader=XmlReader.Create(new StringReader(xml),new XmlReaderSettings{DtdProcessing=DtdProcessing.Prohibit,XmlResolver=null}))document=XDocument.Load(reader);if(document.Root==null||document.Root.Name!=ns+"feed")throw new InvalidDataException("版本订阅格式无效。");var result=new List<GitHubRelease>();foreach(var entry in document.Root.Elements(ns+"entry")){var alternate=entry.Elements(ns+"link").FirstOrDefault(e=>(string)e.Attribute("rel")=="alternate");if(alternate==null)continue;string link=(string)alternate.Attribute("href");Uri uri;if(!Uri.TryCreate(link,UriKind.Absolute,out uri)||uri.Scheme!="https"||uri.Host!="github.com"||!uri.AbsolutePath.StartsWith("/"+Repository+"/releases/tag/",StringComparison.Ordinal))continue;string tag=Uri.UnescapeDataString(uri.Segments.Last());if(!Regex.IsMatch(tag,@"^v?\d+\.\d+(\.\d+)?$"))continue;string baseUrl="https://github.com/"+Repository+"/releases/download/"+Uri.EscapeDataString(tag)+"/";string body=WebUtility.HtmlDecode(Regex.Replace((string)entry.Element(ns+"content")??"",@"<[^>]+>","\n"));result.Add(new GitHubRelease{tag_name=tag,name=(string)entry.Element(ns+"title"),body=body.Trim(),html_url=link,assets=new[]{new GitHubAsset{name="Touchfish-update.json",browser_download_url=baseUrl+"Touchfish-update.json"},new GitHubAsset{name="Touchfish-"+tag+"-win.zip",browser_download_url=baseUrl+"Touchfish-"+tag+"-win.zip"}}});}return result.GroupBy(r=>r.tag_name).Select(g=>g.First()).OrderByDescending(r=>VersionOf(r.tag_name)).ToArray();}
 public static string NetworkError(Exception error){var web=error as WebException;var response=web==null?null:web.Response as HttpWebResponse;if(response!=null){string detail="";try{using(var reader=new StreamReader(response.GetResponseStream()))detail=reader.ReadToEnd();}catch{}if(response.StatusCode==HttpStatusCode.Forbidden||((int)response.StatusCode)==429){if(response.Headers["X-RateLimit-Remaining"]=="0"||detail.IndexOf("rate limit",StringComparison.OrdinalIgnoreCase)>=0)return "GitHub API 访问额度已耗尽（403/429）。";return "服务器拒绝访问（"+(int)response.StatusCode+"），请检查网络或代理限制。";}return "HTTP "+(int)response.StatusCode+"："+error.Message;}return error.Message;}
 public static string Download(GitHubRelease release,string root,CancellationToken cancel,Action<long,long> progress=null){var asset=release.assets.Single(a=>a.name=="Touchfish-update.json");var manifest=Json().Deserialize<UpdateManifest>(Encoding.UTF8.GetString(Get(asset.browser_download_url,1024*1024,cancel)));Validate(manifest);if(VersionOf(manifest.Version)!=VersionOf(release.tag_name)||!IsHash(manifest.ZipSha256))throw new InvalidDataException("版本与更新清单不一致。");var zipAsset=release.assets.SingleOrDefault(a=>a.name==manifest.ZipName);if(zipAsset==null||zipAsset.size>32*1024*1024)throw new InvalidDataException("找不到完整更新包。");string stage=Path.Combine(root,"_updates","downloads",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(stage);try{string zip=Path.Combine(stage,"package.zip");File.WriteAllBytes(zip,Get(zipAsset.browser_download_url,32*1024*1024,cancel,progress));if(!Hash(zip).Equals(manifest.ZipSha256,StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("下载包校验失败，未修改当前版本。");Extract(zip,Path.Combine(stage,"files"),manifest);Write(Path.Combine(stage,"manifest.json"),manifest);return stage;}catch{try{ClearTemporary(root,stage);}catch(IOException){}throw;}}
 public static void Extract(string zip,string destination,UpdateManifest manifest){Validate(manifest);Directory.CreateDirectory(destination);var expected=manifest.Files.ToDictionary(f=>f.Path,StringComparer.OrdinalIgnoreCase);var seen=new HashSet<string>(StringComparer.OrdinalIgnoreCase);long total=0;using(var archive=ZipFile.OpenRead(zip))foreach(var entry in archive.Entries){if(entry.FullName.EndsWith("/")){if(!entry.FullName.StartsWith("data/",StringComparison.Ordinal)||entry.FullName.Contains(".."))throw new InvalidDataException("更新包目录无效。");continue;}UpdateFile file;if(!expected.TryGetValue(entry.FullName,out file)||!seen.Add(entry.FullName))throw new InvalidDataException("更新包有未声明或重复文件。");total+=entry.Length;if(total>64*1024*1024||entry.Length>32*1024*1024)throw new InvalidDataException("解压内容超过限制。");string path=Under(destination,file.Path);Directory.CreateDirectory(Path.GetDirectoryName(path));entry.ExtractToFile(path);if(!Hash(path).Equals(file.Sha256,StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("文件校验失败："+file.Path);}if(seen.Count!=manifest.Files.Length)throw new InvalidDataException("更新包缺少文件。");}
 public static string Prepare(string root,string stage,int pid){var manifest=Read<UpdateManifest>(Path.Combine(stage,"manifest.json"));Validate(manifest);foreach(var file in manifest.Files)if(!Hash(Under(Path.Combine(stage,"files"),file.Path)).Equals(file.Sha256,StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("已下载文件发生变化。");var plan=new UpdatePlan{Root=Path.GetFullPath(root),Stage=Path.GetFullPath(stage),ParentPid=pid,Manifest=manifest,Token=Guid.NewGuid().ToString("N"),Phase="prepared"};string path=Path.Combine(root,"_updates","plans",plan.Token+".json");Write(path,plan);return path;}
 public static UpdateBackup Backup(string root,string directory,IEnumerable<string> paths){Directory.CreateDirectory(directory);var files=new List<UpdateFile>();var absent=new List<string>();foreach(string name in paths.Distinct(StringComparer.OrdinalIgnoreCase)){string source=Under(root,name);if(!File.Exists(source)){absent.Add(name);continue;}string target=Under(Path.Combine(directory,"files"),name);Directory.CreateDirectory(Path.GetDirectoryName(target));File.Copy(source,target);files.Add(new UpdateFile{Path=name,Sha256=Hash(target)});}string version=File.Exists(Path.Combine(root,"VERSION"))?File.ReadAllText(Path.Combine(root,"VERSION")).Trim():"0.0";var backup=new UpdateBackup{Version=version,Created=DateTime.UtcNow.ToString("o"),Files=files.ToArray(),Absent=absent.ToArray(),HealthCheck=File.Exists(Path.Combine(root,"_updates","installed.json"))&&Read<UpdateManifest>(Path.Combine(root,"_updates","installed.json")).HealthCheck};Write(Path.Combine(directory,"backup.json"),backup);return backup;}
 public static string Apply(UpdatePlan plan,Action<int> afterCopy=null){Validate(plan.Manifest);foreach(var file in plan.Manifest.Files)if(!Hash(Under(Path.Combine(plan.Stage,"files"),file.Path)).Equals(file.Sha256,StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("安装前校验失败。");string root=Path.GetFullPath(plan.Root);if(File.Exists(Path.Combine(root,"_updates","pending.json")))throw new InvalidOperationException("另一次更新尚未完成。");var old=File.Exists(Path.Combine(root,"_updates","installed.json"))?Read<UpdateManifest>(Path.Combine(root,"_updates","installed.json")).Files.Select(f=>f.Path):new string[0];string backup=Path.Combine(root,"_updates","temporary-"+plan.Token);Backup(root,backup,plan.Manifest.Files.Select(f=>f.Path).Concat(old));plan.Backup=backup;plan.Phase="applying";Write(Path.Combine(root,"_updates","pending.json"),plan);int count=0;try{foreach(var file in plan.Manifest.Files.OrderBy(f=>f.Path=="Touchfish.exe"?0:1)){string target=Under(root,file.Path);Directory.CreateDirectory(Path.GetDirectoryName(target));File.Copy(Under(Path.Combine(plan.Stage,"files"),file.Path),target,true);if(afterCopy!=null)afterCopy(++count);}foreach(string obsolete in old.Except(plan.Manifest.Files.Select(f=>f.Path),StringComparer.OrdinalIgnoreCase)){string path=Under(root,obsolete);if(File.Exists(path)&&obsolete!="Touchfish.Update.exe")File.Delete(path);}Write(Path.Combine(root,"_updates","installed.json"),plan.Manifest);plan.Phase="starting";Write(Path.Combine(root,"_updates","pending.json"),plan);return backup;}catch{Restore(root,backup);throw;}}
 public static void Restore(string root,string backup){var data=Read<UpdateBackup>(Path.Combine(backup,"backup.json"));foreach(var file in data.Files){string original=Under(Path.Combine(backup,"files"),file.Path);if(!Hash(original).Equals(file.Sha256,StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("备份校验失败。");}foreach(var file in data.Files){string target=Under(root,file.Path);if(File.Exists(target)&&Hash(target).Equals(file.Sha256,StringComparison.OrdinalIgnoreCase))continue;Directory.CreateDirectory(Path.GetDirectoryName(target));File.Copy(Under(Path.Combine(backup,"files"),file.Path),target,true);}foreach(string name in data.Absent){string path=Under(root,name);if(File.Exists(path)&&name!="Touchfish.Update.exe")File.Delete(path);}Write(Path.Combine(root,"_updates","installed.json"),new UpdateManifest{Version=data.Version,Files=data.Files,HealthCheck=data.HealthCheck});Finish(root);}
 public static void ClearTemporary(string root,string path){string allowed=Path.GetFullPath(Path.Combine(root,"_updates")).TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar;string target=Path.GetFullPath(path);if(!target.StartsWith(allowed,StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("临时目录越界。");if(Directory.Exists(target))Directory.Delete(target,true);}
 public static void Finish(string root){string pending=Path.Combine(root,"_updates","pending.json");if(File.Exists(pending)){var plan=Read<UpdatePlan>(pending);plan.Phase="committed";Write(pending,plan);if(!String.IsNullOrEmpty(plan.Backup))ClearTemporary(root,plan.Backup);File.Delete(pending);}}
 public static string Quote(string value){return "\""+value+"\"";}
 public static void CleanupRunners(string root){string directory=Path.Combine(root,"_updates");if(!Directory.Exists(directory)||File.Exists(Path.Combine(directory,"pending.json")))return;foreach(string path in Directory.GetFiles(directory,"runner-*.exe",SearchOption.TopDirectoryOnly)){try{File.Delete(path);}catch(IOException){}catch(UnauthorizedAccessException){}}}
 public static void LaunchInstaller(string root,string planPath){var plan=Read<UpdatePlan>(planPath);string executable=Path.Combine(root,"Touchfish.Update.exe");if(!File.Exists(executable))throw new FileNotFoundException("缺少更新器，请先下载完整程序包。");string copy=Path.Combine(root,"_updates","runner-"+plan.Token+".exe");File.Copy(executable,copy);Process.Start(new ProcessStartInfo(copy,"--install "+Quote(planPath)){UseShellExecute=false,CreateNoWindow=true,WorkingDirectory=root});}
 public static bool RecoverBeforeStart(string root){string pending=Path.Combine(root,"_updates","pending.json");if(!File.Exists(pending))return false;var plan=Read<UpdatePlan>(pending);if(plan.Phase=="committed"){try{Finish(root);}catch(IOException){}return false;}string helper=Path.Combine(root,"_updates","runner-"+plan.Token+".exe");if(plan.InstallerPid>0){try{var active=Process.GetProcessById(plan.InstallerPid);if(!active.HasExited&&active.MainModule.FileName.Equals(helper,StringComparison.OrdinalIgnoreCase))return true;}catch(ArgumentException){}catch(System.ComponentModel.Win32Exception){}}if(!File.Exists(helper))helper=Path.Combine(root,"Touchfish.Update.exe");Process.Start(new ProcessStartInfo(helper,"--recover "+Quote(pending)){UseShellExecute=false,CreateNoWindow=true,WorkingDirectory=root});return true;}
 public static void Health(string root,string token){if(String.IsNullOrEmpty(token)||token.Any(c=>!Uri.IsHexDigit(c))||token.Length!=32)return;File.WriteAllText(Path.Combine(root,"_updates","health-"+token),"ok");}
}
}
