using System;
using System.IO;
using System.Linq;
using System.Windows;

namespace Touchfish {
public partial class PanelWindow {
 void VerifyVisualEffects(string folder){int before=checks;fullEffects=true;var game=MatchFixture();var unit=game.Summon(1,"VAN_CS2_182");int spell=Inject(game,"CS2_029");game.Play(0,spell,new MatchTarget(1,unit.Id));Check(game.VisualEvents.Count==2&&game.VisualEvents[0].Kind=="spell"&&game.VisualEvents[0].CardName=="火球术"&&game.VisualEvents[1].Amount==6&&game.VisualEvents[1].UnitId==unit.Id&&game.VisualEvents[1].Slot==0,"Spell and lethal damage preserve public target anchor");var view=LanProtocol.View(game,1,"visual-test",1);var remote=LanProtocol.ReadView(catalog,LanProtocol.Copy(view));Check(remote.VisualSession==game.VisualSession&&remote.VisualEvents.Select(e=>e.Sequence).SequenceEqual(game.VisualEvents.Select(e=>e.Sequence))&&remote.VisualEvents[1].Amount==6,"Visual events survive network serialization");var cursor=new MatchVisualCursor();Check(cursor.Take(remote.VisualSession,remote.VisualEvents,true).Length==2&&cursor.Take(remote.VisualSession,remote.VisualEvents,true).Length==0,"Repeated snapshots never replay effects");game.Damage(new MatchTarget(1),1);Check(cursor.Take(game.VisualSession,game.VisualEvents,false).Length==0&&cursor.Take(game.VisualSession,game.VisualEvents,true).Length==0,"Minimal mode consumes events without delayed replay");
  game=MatchFixture();unit=game.Summon(1,"VAN_EX1_008");game.Damage(new MatchTarget(1,unit.Id),20);Check(game.VisualEvents.Count==0&&!unit.Shield,"Shield blocks damage float and shake");int id=Inject(game,"CS2_029");game.Players[0].Mana=0;game.Play(0,id,new MatchTarget(1));Check(game.VisualEvents.Count==0,"Rejected spell emits no presentation event");for(int n=0;n<150;n++)game.EmitVisual("damage",0,amount:1);Check(game.VisualEvents.Count==128&&game.VisualEvents.Last().Sequence==150,"Bounded event stream retains monotonic sequence");
  match=MatchFixture();matchViewSeat=0;lanMode=false;awaitHandoff=false;inspectMatch=false;ClearPending();ApplyTheme(true,true);ApplyMode(false);RenderMatch();ShowPage("match");UpdateLayout();var renderer=(OfficeMatchVisualEffects)matchEffects;renderer.Clear();var hero=visualTargets[VisualKey(1,0)];var bounds=hero.TransformToVisual(matchEffectsCanvas).TransformBounds(new Rect(0,0,hero.ActualWidth,hero.ActualHeight));var anchor=new MatchVisualAnchor{Bounds=bounds,Element=hero};int cards=renderer.CardShakeCount,screens=renderer.ScreenShakeCount;renderer.Damage(new MatchVisualEvent{Kind="damage",Amount=3},anchor,TimeSpan.Zero);Check(renderer.CardShakeCount==cards&&renderer.ScreenShakeCount==screens,"Damage three does not shake");renderer.Damage(new MatchVisualEvent{Kind="damage",Amount=4},anchor,TimeSpan.Zero);Check(renderer.CardShakeCount==cards+1&&renderer.ScreenShakeCount==screens,"Damage four shakes target only");renderer.Damage(new MatchVisualEvent{Kind="damage",Amount=10},anchor,TimeSpan.Zero);Check(renderer.ScreenShakeCount==screens,"Damage ten does not shake screen");renderer.Damage(new MatchVisualEvent{Kind="damage",Amount=11},anchor,TimeSpan.Zero);Check(renderer.ScreenShakeCount==screens+1,"Damage eleven shakes screen");renderer.Clear();
  unit=match.Summon(1,"VAN_CS2_182");spell=Inject(match,"CS2_029");RenderMatch();UpdateLayout();int floats=renderer.FloatCount;BeginCard(spell);ClickMatchTarget(new MatchTarget(1,unit.Id));PumpLan(()=>renderer.FloatCount>floats,"Lethal target creates floating number after board removal");var animationWatch=System.Diagnostics.Stopwatch.StartNew();PumpLan(()=>animationWatch.ElapsedMilliseconds>=180,"Animation clock advances to visible float frame");Render(Path.Combine(folder,"54-standard-spell-effects.png"));Check(matchEffectsCanvas.Children.Count>0,"Effect overlay is visible without enlarging window");double width=Width,height=Height;Check(width==548&&height==474,"Normal effects preserve office window dimensions");ApplyMode(true);Check(matchEffectsCanvas.Visibility==Visibility.Collapsed&&matchEffectsCanvas.Children.Count==0,"Minimal mode clears ongoing visuals");floats=renderer.FloatCount;spell=Inject(match,"CS2_024");BeginCard(spell);ClickMatchTarget(new MatchTarget(1));UpdateLayout();Check(renderer.FloatCount==floats,"Minimal spells remain silent");renderer.Clear();ApplyMode(false);SetFullEffects(false);int disabledFloats=renderer.FloatCount,disabledShakes=renderer.ScreenShakeCount;renderer.Spell(new MatchVisualEvent{Kind="spell",Seat=0,CardName="火球术"});renderer.Damage(new MatchVisualEvent{Kind="damage",Amount=11},anchor,TimeSpan.Zero);Check(renderer.FloatCount==disabledFloats+1&&renderer.ScreenShakeCount==disabledShakes&&matchEffectsCanvas.Visibility==Visibility.Visible,"Normal base effects remain enabled without full effects");ShowPage("settings");Render(Path.Combine(folder,"61-effects-setting-off.png"));Check(fullEffectsOption.IsChecked==false,"Settings reflect disabled effects");SetFullEffects(true);Check(fullEffectsOption.IsChecked==true,"Settings reflect enabled effects");ApplyMode(true);Check(matchEffectsCanvas.Visibility==Visibility.Collapsed&&matchEffectsCanvas.Children.Count==0,"Minimal hides all effects even with full effects checked");SetFullEffects(false);VerifyDiscardVisuals(folder);ShowPage("lan");JsonData.Write(Path.Combine(folder,"visual-verification.json"),new {Assertions=checks-before,NormalOnly=true,PublicNetworkEvents=true,DuplicateSuppression=true,CardShakeAbove=3,ScreenShakeAbove=10,LethalTargetAnchor=true});
 }
}
}
