using System;
using System.IO;
using System.Linq;
namespace Touchfish {
public partial class PanelWindow {
 public void PreviewWarlockScope(string folder){
  previewRun=true;Directory.CreateDirectory(folder);int before=checks;var all=catalog.Deckable(catalog.Pool("classic-2014"));var cards=all.Where(c=>c.CardClass=="WARLOCK").ToArray();Check(cards.Length==25&&cards.Where(c=>c.BaseId!="EX1_323").All(c=>matchRules.Supports(c))&&!matchRules.Supports(cards.Single(c=>c.BaseId=="EX1_323")),"All 24 Warlock cards supported except Jaraxxus");
  var g=MatchFixture("WARLOCK");var target=g.Summon(1,"VAN_CS2_182");g.Play(0,Inject(g,"CS2_063"),new MatchTarget(1,target.Id));g.EndTurn();Check(g.Players[1].Board.Count==1,"Corruption waits through opponent turn");g.EndTurn();Check(g.Players[1].Board.Count==0,"Corruption destroys at caster turn start");g=MatchFixture("WARLOCK");target=g.Summon(1,"VAN_CS2_182");g.Play(0,Inject(g,"CS2_063"),new MatchTarget(1,target.Id));g.Silence(new MatchTarget(1,target.Id));g.EndTurn();g.EndTurn();Check(g.Players[1].Board.Count==1,"Silence removes Corruption");
  g=MatchFixture("WARLOCK");target=g.Summon(1,"VAN_CS2_182");g.Summon(0,"VAN_EX1_563");g.Play(0,Inject(g,"CS2_064"));Check(g.Players[0].Health==29&&g.Players[1].Health==29&&target.DamageTaken==1&&g.Players[0].Board.Last().Health==6,"Dread Infernal hits all other characters once without spell power");
  g=MatchFixture("WARLOCK");g.Play(0,Inject(g,"EX1_301"));Check(g.Players[0].MaxMana==9&&g.Players[0].Mana==7&&g.Players[0].Board.Single().Taunt,"Felguard removes empty crystal and retains unspent mana");g=MatchFixture("WARLOCK");g.Players[0].MaxMana=0;g.Players[0].Mana=3;Check(g.Play(0,Inject(g,"EX1_301")).Success&&g.Players[0].MaxMana==0,"Felguard at zero permanent crystals still summons");
  g=MatchFixture("WARLOCK");var sacrifice=g.Summon(0,"VAN_CS2_182");sacrifice.DamageTaken=2;target=g.Summon(1,"VAN_CS2_182");g.Summon(0,"VAN_EX1_563");g.Play(0,Inject(g,"EX1_303"),new MatchTarget(0,sacrifice.Id));Check(!g.Players[0].Board.Contains(sacrifice)&&g.Players[1].Board.Count==0&&g.Players[1].Health==30,"Shadowflame snapshots attack, adds spell power and excludes enemy hero");
  g=MatchFixture("WARLOCK");var left=g.Summon(0,"VAN_CS2_182");left.DamageTaken=2;var right=g.Summon(0,"VAN_EX1_556");g.Play(0,Inject(g,"EX1_304"),position:1);var terror=g.Players[0].Board.First();Check(terror.CardId=="VAN_EX1_304"&&g.AttackValue(terror)==9&&terror.MaxHealth==9&&g.Players[0].Board.Count==2&&g.Players[0].Board.Last().CardId=="VAN_skele21","Void Terror consumes adjacent current health and resolves deathrattle");
  g=MatchFixture("WARLOCK");g.Players[0].Armor=3;g.Play(0,Inject(g,"EX1_313"));Check(g.Players[0].Health==28&&g.Players[0].Armor==0,"Pit Lord deals five with armor absorption");
  g=MatchFixture("WARLOCK");g.Players[0].Deck.Clear();g.Players[0].Deck.AddRange(new[]{"VAN_CS2_231","VAN_CS2_065","VAN_EX1_319","VAN_CS2_182"});g.Play(0,Inject(g,"EX1_317"));Check(g.Players[0].Hand.Count==2&&g.Players[0].Hand.All(h=>g.Card(h.CardId).Race=="DEMON")&&g.Players[0].Deck.SequenceEqual(new[]{"VAN_CS2_231","VAN_CS2_182"}),"Sense Demons draws two distinct deck instances without disturbing other order");
  g=MatchFixture("WARLOCK");g.Players[0].Deck.Clear();g.Players[0].Deck.Add("VAN_CS2_065");g.Play(0,Inject(g,"EX1_317"));Check(g.Players[0].Hand.Count(h=>h.CardId=="GAME_WORTHLESS_IMP")==1&&g.Players[0].Fatigue==0,"One missing demon yields one worthless imp without fatigue");g=MatchFixture("PRIEST");g.Players[0].Deck.Clear();g.Play(0,Inject(g,"EX1_317"));Check(g.Players[0].Hand.Count==2&&g.Play(0,g.Players[0].Hand[0].Id).Success&&g.Players[0].Board[0].Race=="DEMON","Foreign Sense Demons generates playable helper imps");
  g=MatchFixture("WARLOCK");target=g.Summon(0,"VAN_CS2_065");g.Summon(0,"VAN_EX1_563");g.Play(0,Inject(g,"EX1_596"),new MatchTarget(0,target.Id));Check(target.BaseAttack+target.BuffAttack==3&&target.MaxHealth==5&&target.DamageTaken==0,"Demonfire buffs friendly demon without damage or spell-power buff");target=g.Summon(1,"VAN_CS2_065");g.Play(0,Inject(g,"EX1_596"),new MatchTarget(1,target.Id));Check(g.Players[1].Board.Count==0,"Demonfire damages enemy demon with spell power");
  g=MatchFixture("WARLOCK");g.Players[0].Health=20;target=g.Summon(1,"VAN_CS2_065");target.Shield=true;g.Play(0,Inject(g,"NEW1_003"),new MatchTarget(1,target.Id));Check(g.Players[1].Board.Count==0&&g.Players[0].Health==25,"Sacrificial Pact destroys demon through shield and heals caster");target=g.Summon(1,"VAN_CS2_182");int pact=Inject(g,"NEW1_003"),mana=g.Players[0].Mana;Check(!g.Play(0,pact,new MatchTarget(1,target.Id)).Success&&g.Players[0].Mana==mana&&g.Players[0].Hand.Any(h=>h.Id==pact),"Sacrificial Pact rejects non-demon before payment");
  g=MatchFixture("WARLOCK");target=g.Summon(1,"VAN_CS2_231");g.Play(0,Inject(g,"EX1_320"),new MatchTarget(1,target.Id));Check(g.Players[0].Board.Count==1&&WarlockRules.BaneDemons.Contains(g.Players[0].Board[0].CardId)&&g.Players[0].Health==30&&g.Players[0].MaxMana==10&&g.Players[0].Hand.Count==0,"Bane of Doom uses frozen summon pool without battlecry");g=MatchFixture("WARLOCK");target=g.Summon(1,"VAN_CS2_182");target.Shield=true;g.Play(0,Inject(g,"EX1_320"),new MatchTarget(1,target.Id));Check(g.Players[0].Board.Count==0&&!target.Shield,"Bane does not summon through divine shield");g=MatchFixture("WARLOCK");for(int n=0;n<7;n++)g.Summon(0,"VAN_CS2_231");target=g.Players[0].Board[0];g.Play(0,Inject(g,"EX1_320"),new MatchTarget(0,target.Id));Check(g.Players[0].Board.Count==7&&g.Players[0].Board.Any(u=>WarlockRules.BaneDemons.Contains(u.CardId)),"Bane frees killed friendly slot before summoning");
  foreach(int prior in new[]{4,5,6}){g=MatchFixture("ROGUE");g.CardsPlayed=prior;g.EntranceAnimationsEnabled=true;g.Play(0,Inject(g,"EX1_613"));Check(g.AnimationPlaying==(prior>=5)&&g.VisualEvents.Any(v=>v.Kind=="entrance"&&v.CardName=="EX1_613")== (prior>=5),"Edwin entrance threshold at combo twelve attack");if(prior>=5)Check(!g.EndTurn().Success,"Edwin entrance gates game actions");}
  g=MatchFixture("ROGUE");g.CardsPlayed=5;g.Play(0,Inject(g,"EX1_613"));Check(!g.AnimationPlaying&&g.VisualEvents.Any(v=>v.CardName=="EX1_613"),"Edwin event remains public while disabled effects do not wait");
  VerifyWarlockTcp(folder);VerifyEdwinRenderer(folder);var coverage=all.Select(c=>new{Id=c.Id,Name=c.Name,Supported=matchRules.Supports(c)}).ToArray();JsonData.Write(Path.Combine(folder,"match-rule-coverage.json"),new{SupportedCards=coverage.Count(c=>c.Supported),TotalCards=382,Cards=coverage,Scope="Warlock and Edwin focused verification"});File.WriteAllText(Path.Combine(folder,"warlock-verification.txt"),"PASS: "+(checks-before)+" targeted Warlock and Edwin checks; real loopback TCP and WPF previews.");
 }
 void VerifyEdwinRenderer(string folder){LeaveLan();ApplyTheme(true,true);ApplyMode(false);SetFullEffects(true);match=MatchFixture("ROGUE");var edwin=match.Summon(0,"VAN_EX1_613");edwin.BuffAttack=edwin.BuffHealth=10;matchViewSeat=0;awaitHandoff=false;ClearPending();ShowPage("match");RenderMatch();var renderer=(OfficeMatchVisualEffects)matchEffects;renderer.Clear();int count=renderer.EntranceCount;renderer.Entrance(new MatchVisualEvent{Kind="entrance",CardName="EX1_613"});Check(renderer.EntranceCount==count+1&&renderer.ScreenShakeCount>0&&matchEffectsCanvas.Children.Count==0,"Edwin shakes without Deathwing fire glyphs");Render(Path.Combine(folder,"112-edwin-entrance-codex.png"));ApplyMode(true);renderer.Entrance(new MatchVisualEvent{Kind="entrance",CardName="EX1_613"});Check(renderer.EntranceCount==count+1,"Minimal never shakes for Edwin");ApplyMode(false);SetFullEffects(false);renderer.Entrance(new MatchVisualEvent{Kind="entrance",CardName="EX1_613"});Check(renderer.EntranceCount==count+1,"Extras disabled never shakes for Edwin");}
 void VerifyWarlockTcp(string folder){
  LeaveLan();ApplyMode(false);SetFullEffects(false);var guest=new PanelWindow(true){ShowInTaskbar=false,Opacity=0};guest.Show();guest.ApplyMode(false);guest.SetFullEffects(true);
  try{lanPort.Text=FreeLanPort().ToString();lanDeck.SelectedIndex=0;lanClass.SelectedItem=Classes.First(c=>c.Key=="WARLOCK");BeginLan(true);guest.lanDeck.SelectedIndex=0;guest.lanClass.SelectedItem=Classes.First(c=>c.Key=="ROGUE");guest.lanAddress.Text="127.0.0.1:"+lanPort.Text;guest.BeginLan(false);PumpLan(()=>lanReady&&guest.lanReady,"Warlock TCP peers connect");DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>guest.match.Players[0].MulliganDone,"Host mulligan reaches guest");guest.DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>match.MulliganComplete&&!guest.lanWaiting,"Guest mulligan starts game");var game=lanAuthority.Game;foreach(var p in game.Players){p.Hand.Clear();p.Board.Clear();}game.Players[0].Mana=game.Players[0].MaxMana=10;game.Players[0].Deck.Clear();game.Players[0].Deck.AddRange(new[]{"VAN_CS2_065","VAN_EX1_319","VAN_CS2_231"});int sense=Inject(game,"EX1_317");PublishLan();BeginCard(sense);PumpLan(()=>guest.match.Players[0].HandCount==2,"Sense Demons count synchronizes over TCP");Check(guest.match.Players[0].Hand.Count==0&&game.Players[0].Hand.All(h=>game.Card(h.CardId).Race=="DEMON"),"Sense Demons hides identities from opponent");var enemy=game.Summon(1,"VAN_CS2_182");int corruption=Inject(game,"CS2_063");PublishLan();BeginCard(corruption);ClickMatchTarget(new MatchTarget(1,enemy.Id));DoMatch("end");PumpLan(()=>guest.match.Active==1,"Guest turn starts");game.Players[1].Mana=10;game.CardsPlayed=5;int edwin=Inject(game,"EX1_613",1);PublishLan();PumpLan(()=>guest.match.Players[1].Hand.Any(h=>h.Id==edwin),"Edwin combo fixture reaches guest");guest.BeginCard(edwin);guest.ClickEmptySlot(1,1);PumpLan(()=>game.AnimationPlaying&&guest.match.AnimationPlaying&&!guest.lanWaiting,"Edwin enables two-second shared wait with host extras off");Check(match.AnimationPlaying&&status.Text.Contains("动画")&&game.Players[1].Board.Any(u=>u.CardId=="VAN_EX1_613"&&u.BaseAttack+u.BuffAttack==12),"Both peers wait for twelve-attack Edwin");SetFullEffects(true);SetFullEffects(false);Check(match.AnimationPlaying,"Settings cannot bypass Edwin wait");Render(Path.Combine(folder,"113-edwin-animation-wait.png"));PumpLan(()=>!game.AnimationPlaying&&!guest.match.AnimationPlaying,"Edwin animation lock expires");guest.DoMatch("end");PumpLan(()=>!guest.lanWaiting&&game.Active==0,"Corruption returns to caster turn");Check(game.Players[1].Board.All(u=>u.Id!=enemy.Id)&&guest.match.Players[1].Board.All(u=>u.Id!=enemy.Id)&&game.Log.SequenceEqual(guest.match.Log),"Delayed destruction and history synchronize");
  }finally{guest.LeaveLan();guest.Close();LeaveLan();}
 }
}
}
